MATCH (n)
DETACH DELETE n;

// chefs
CREATE (seonkyoungLongest:Person { name: 'Seonkyoung Longest', urls: ["https://www.recipetineats.com", ""] })
CREATE (recipetineats:Person { name: 'Recipetineats', urls: ["https://www.recipetineats.com", ""] })
CREATE (marionsKitchen:Person { name: 'Marionskitchen', ytb: 'https://www.youtube.com/@Marionskitchen'})
CREATE (hanaAsbrink:Person { name: "Hana Asbrink", urls: ['https://www.youtube.com/@Marionskitchen',"https://www.youtube.com/c/HanaAsbrink","https://www.instagram.com/hanaasbrink/"]})
CREATE (joshuaweissman:Person { name: "Joshua Weissman", urls: ['https://www.youtube.com/@JoshuaWeissman']})
CREATE (subha:Person { name: 'Subha', urls: ["https://theflavoursofkitchen.com/about/"] })
CREATE (pailinChongchitnant:Person { name: 'Pailin Chongchitnant', urls: [] })
CREATE (eliseBauer:Person {name: 'Elise Bauer', urls: ['https://www.simplyrecipes.com/recipes/tomatillo_salsa_verde/']})

// recipes
CREATE (salsaVerde:Recipe {name: 'Tomatillo Salsa Verde', urls: ['https://www.simplyrecipes.com/recipes/tomatillo_salsa_verde/?print']})
CREATE (yellowCurry:Recipe { name: 'Yellow Curry with Chicken', urls: ['https://www.templeofthai.com/recipes/yellow_chicken_curry.php'] })
CREATE (padThai:Recipe { name: 'Pad Thai', urls: ['https://www.foodnetwork.com/recipes/pad-thai-7112938?soc=youtube']})
CREATE (redCurry:Recipe { name: 'Vegan Thai Red Curry', urls: ['https://hot-thai-kitchen.com/red-curry-paste/print/6752/']})
CREATE (yellowCoconutCurry:Recipe { name: 'Yellow Coconut Curry Chicken', urls: ['https://lifemadesimplebakes.com/wprm_print/25731']})
CREATE (thaiCurry1:Recipe { name: "The Best Green Curry", urls: ["https://www.joshuaweissman.com/post/easy-authentic-thai-green-curry", "https://photos.google.com/photo/AF1QipMJV_m1w-qezTjSZAmu6Vam_PKMR6GICW6TJ883"]})
CREATE (thaiEggplantRecipe:Recipe { name: "Thai Eggplant Recipe", urls: ["https://www.myfoodchannel.com/thai-eggplant-recipe/","https://www.youtube.com/watch?v=7a0IAC7pCgA"]})
CREATE (yellowThaiCurry:Recipe { name: 'Yellow Thai Curry', urls: ['https://www.youtube.com/watch?v=JaB3T4HpGE8']})
CREATE (thaiPanangChickenCurry:Recipe { name: "Thai Panang Chicken Curry", urls: "https://www.youtube.com/watch?v=QraggvxNMrk"})
CREATE (coldSobaWithPerillaOilDressing:Recipe { name: "Cold Soba With Periall Oil dresssing"})
CREATE (sesameNoodleRecipe:Recipe { name: "The Best Sesame Noodles From Korea Under 6 Minutes!",urls:["https://www.youtube.com/watch?v=HZ1VIYNAeR0", "https://seonkyounglongest.com/korean-sesame-noodles/print/46266/"]})
CREATE (koreanSesameNoodles:Recipe {name: 'Korean Sesame Noodles', urls: ['https://seonkyounglongest.com/korean-sesame-noodles/print/46266/']})
CREATE (chickenThaiRedCurry:Recipe { name: 'Chicken Thai Red Curry', urls: ['https://theflavoursofkitchen.com/wprm_print/104534'] })
CREATE (phadThai:Recipe { name: 'Phad Thai', urls: ['https://www.youtube.com/watch?v=dBSmCwUXZF0'] })
CREATE (sobaNoodlesRecipe:Recipe { name: 'Sugar Snap Pea and Carrot Soba Noodles', urls: ['https://cookieandkate.com/sugar-snap-pea-and-carrot-soba-noodles/print/23556/']} )

// stores
CREATE (thanhSonTofu:Store { name: "Thanh Son Tofu" , urls:["https://www.yelp.com/biz/thanh-son-tofu-seattle-3"]})
CREATE (dummy:Store { name: "dummy place holder" })
CREATE (amazon:Store { name: "Amazon" })
CREATE (bartell:Store { name: "Bartell" })
CREATE (centralCoop:Store { name: "Central Co-op" })
CREATE (einsteinBrothersBagels:Store { name: "Einstein Brotheres Bagels" })
CREATE (franzBakery:Store { name: "Franz Bakery" })
CREATE (fredMeyer:Store { name: "Fred Meyer" })
CREATE (groceryOutlet:Store { name: "Grocery Outlet" })
CREATE (groceryOutletBargainMarket:Store { name: "Grocery Outlet Bargain Market" })
CREATE (hardwareStore:Store { name: "Hardware Store" })
CREATE (hauHauMarket:Store { name: "Hau Hau Market" })
CREATE (m2mMart:Store { name: "M2M Mart", notes: ["Korean Grocer"], urls: ["https://www.google.com/search?q=m2m+mart&oq=m2&gs_lcrp=EgZjaHJvbWUqCQgAECMYJxiKBTIJCAAQIxgnGIoFMhAIARAuGK8BGMcBGIAEGI4FMgoIAhAuGLEDGIAEMgoIAxAAGLEDGIAEMg0IBBAuGLEDGIAEGOUEMg0IBRAAGIMBGLEDGIAEMgoIBhAAGLEDGIAEMgoIBxAAGLEDGIAEMgcICBAAGIAEMgcICRAAGI8C0gEIMjI1N2owajeoAgCwAgA&sourceid=chrome&ie=UTF-8#lpg=cid:CgIgAQ%3D%3D,ik:CAoSLEFGMVFpcE15YzlKMF9jRTJzMFVUUHJjaFlvSUVLcnlCcnlXOFo5akpsR0dD"] })
CREATE (macrinaBakery:Store { name: "Macrina Bakery" })
CREATE (madisonCoop:Store { name: "Madison Co-op"})
CREATE (nakedGrocer:Store { name: "Naked Grocer" })
CREATE (pcc:Store { name: "PCC" })
CREATE (qfc:Store { name: "QFC" })
CREATE (safeway:Store { name: "Safeway" })
CREATE (seattleSeafood:Store { name: "Seattle Seafood" })
CREATE (traderJoes:Store { name: "Trader Joe's" })
CREATE (uwajimaya:Store { name: "Uwajimaya", urls: ["https://www.uwajimaya.com/"] })
CREATE (wholeFoods:Store { name: "Whole Foods" })

// products
CREATE (chiliGarlicSauce:Product { name: 'Chili Garlic Sauce', type: "Chili Sauce"})
CREATE (chiliSauce:Product { name: 'chili sauce', type: "Chili Sauce"})
CREATE (yellowCurryPaste:Product { name: 'Yellow Curry Paste', type: 'Curry Paste'})
CREATE (potatoes:Product { name: 'Potatoes', type: 'Potatoe'})
CREATE (driedChilis:Product { name: 'Dried Thai Chilis', type: 'Thai Chilies'})
CREATE (chiliOil:Product {name: 'Chili Oil', type: "Condiment"})
CREATE (chiliPepperAnchoGround:Product { name: "Chili Pepper, Ancho, Ground", type: "Spice" })
CREATE (chiliPepperChipotleGround:Product { name: "Chili Pepper, Chipotle, Ground", type: "Spice" })
CREATE (chiliPowder:Product { name: "Chili powder", type: "Spice" })
CREATE (chiliThai:Product { name: "Thai Chili", type: "Thai Chilies" })
CREATE (seaSalt:Product { name: 'Sea Salt', type: 'Seasoning'})
CREATE (shallots:Product { name: 'Shallots', type: 'Shallots'})
CREATE (galangal:Product { name: "Galangal", type: "Galangal" })
CREATE (a1Sauce:Product { name: "A.1. Sauce", type: "Sauce" })
CREATE (allspice:Product { name: "Allspice", type: "Spice" })
CREATE (almondMilksPlease:Product { name: "Almond milks please", type: "Almond Milk" })
CREATE (almondsBulkRoastedOrRawWhicheverIsCheaper:Product { name: "Almonds - bulk roasted or raw -- whichever is cheaper", type: "Almonds" })
CREATE (angkorCambodianFoodPasteLemongrass:Product { name: "Angkor Cambodian Food Paste Lemongrass", type: "Food Paste" })
CREATE (apples:Product { name: "Apples", type: "Fruit" })
CREATE (artichokeHearts:Product { name: "Artichoke Hearts", type: "Artichokes" })
CREATE (asparagus:Product { name: "Asparagus", type: "Vegetable" })
CREATE (avocadosNotInBagStupid:Product { name: "Avocados (not in bag stupid)", type: "Avocados" })
CREATE (bacon:Product { name: "Bacon", type: "Bacon" })
CREATE (bakedTofu:Product { name: "Baked Tofu", type: "Tofu", urls:["https://www.google.com/search?sca_esv=579179295&sxsrf=AM9HkKnAjZCHvxR_pYrcL19p0l0Qjk1Zjg:1699032994034&q=Baked+Tofu&tbm=isch&source=lnms&sa=X&ved=2ahUKEwiwrsiQr6iCAxXHHjQIHVGWDjkQ0pQJegQIDRAB&biw=1440&bih=758&dpr=2"]})
CREATE (bakersDozen:Product { name: "Bakers Dozen", type: "Baked Goods" })
CREATE (bakingCupsInCakeMixflourAisle:Product { name: "Baking Cups in cake mix/flour aisle", type: "Baking Supplies" })
CREATE (bakingSoda:Product { name: "Baking Soda", type: "Baking Supplies" })
CREATE (ballPowderSmellsNice:Product { name: "Ball powder, smells nice", type: "Ball Powder" })
CREATE (bambooShoots:Product { name: "Bamboo Shoots", type: "Vegetables" })
CREATE (bananaLeaf:Product { name: 'banana leaf', type: "Leaves" })
CREATE (bananasOrganic:Product { name: "Bananas organic", type: "Fruit" })
CREATE (barbecueSauceBabyRaysBbqSauce:Product { name: "Barbecue sauce - Baby Rays bbq sauce", type: "Barbecue Sauce" })
CREATE (barley:Product { name: "Barley", type: "Grains" })
CREATE (basilDry:Product { name: "Basil - Dry", type: "Herbs" })
CREATE (basilFresh:Product { name: "Basil - Fresh", type: "Herbs" })
CREATE (bayLeaf:Product { name: "Bay Leaf", type: "Herbs" })
CREATE (beanCannelloniWhite:Product { name: "Bean - Cannelloni White", type: "Beans" })
CREATE (beanGreatNorthernWhite:Product { name: "Bean - Great Northern White", type: "Beans" })
CREATE (beanNavyBean:Product { name: "Bean - Navy Bean", type: "Beans" })
CREATE (beanSprouts:Product { name: 'bean sprouts', type: "Vegetables" })
CREATE (beansBlack15OzCan:Product { name: "Beans - Black 15 oz can", type: "Beans" })
CREATE (beansBlackBulk:Product { name: "Beans - Black, Bulk", type: "Beans" })
CREATE (beansGreen:Product { name: "Beans - Green", type: "Beans" })
CREATE (beansKidneyBulk:Product { name: "Beans - Kidney (Bulk)", type: "Beans" })
CREATE (beefChuck:Product { name: "Beef Chuck", type: "Beef" })
CREATE (beefChuckShoulderClod:Product { name: "Beef Chuck Shoulder clod", type: "Beef" })
CREATE (beerLagger:Product { name: "Beer - Lagger", type: "Beer" })
CREATE (beerSessionLager:Product { name: "Beer - Session Lager", type: "Beer" })
CREATE (beets:Product { name: "Beets", type: "Vegetables" })
CREATE (beetsCanned:Product { name: "Beets - Canned", type: "Canned Beets" })
CREATE (bellPepper:Product { name: 'Bell Pepper', type: "Vegetables" })
CREATE (blueberriesFrozenUponinaBag:Product { name: "Blueberries - frozen uponina bag", type: "Blueberries" })
CREATE (bokChoy:Product { name: "Bok Choy", type: "Vegetables" })
CREATE (bonelessChickenThighs:Product {name: 'Boneless Chicken Thighs', type: "Chicken"})
CREATE (bonitoFlakes:Product { name: "Bonito Flakes", type: "Flakes", urls: ["https://chefjacooks.com/en/wprm_print/7506", "https://www.amazon.com/Kaneso-Tokuyou-Hanakatsuo-Bonito-Flakes/dp/B0052BGLMS", "https://www.google.com/search?sca_esv=577907868&sxsrf=AM9HkKmChgo0Ktu9IlnGTSWuzmK5YqQsiQ:1698696041201&q=Bonito+Flakes&tbm=isch&source=lnms&sa=X&ved=2ahUKEwjy0Pfwx56CAxUBODQIHey0BwcQ0pQJegQIDhAB&biw=1440&bih=758&dpr=2" ]})
CREATE (boullionBeef:Product { name: "Boullion - Beef", type: "Bouillon" })
CREATE (boullionVegetableBrothPowdered:Product { name: "Boullion - Vegetable Broth Powdered", type: "Bouillon" })
CREATE (breadDavesYumsSeedBread:Product { name: "Bread - Dave's Yums Seed Bread", type: "Bread" })
CREATE (breadFrench:Product { name: "Bread - French", type: "Bread" })
CREATE (breadOlive:Product { name: "Bread - Olive", type: "Bread" })
CREATE (breadPurpleNutsAndGrain:Product { name: "Bread - Purple Nuts And Grain", type: "Bread" })
CREATE (breadSoda:Product { name: "Soda Bread", type: "Bread" })
CREATE (brewersYeast:Product { name: "Brewers Yeast", type: "Yeast" })
CREATE (broccoli:Product { name: "Broccoli", type: "Vegetable" })
CREATE (broccolini:Product { name: "Broccolini", type: "Vegetable" })
CREATE (brothBeefLowSodium:Product { name: "Broth - Beef - low sodium", type: "Broth" })
CREATE (brownSugar:Product { name: 'Brown Sugar', type: "Sugar" })
CREATE (brownieClifBar:Product { name: "brownie clif bar", type: "clif bar" })
CREATE (brownieMixBettyCrocker:Product { name: "Betty Crocker Brownie Mix", type: "Baking Mix" })
CREATE (brownieMixDuncanHines:Product { name: "Duncan Hines Brownie Mix", type: "Baking Mix" })
CREATE (brownieMixGhirardelli:Product { name: "Ghirardelli Brownie Mix", type: "Baking Mix" })
CREATE (brownieMixPillsbury:Product { name: "Pillsbury Brownie Mix", type: "Baking Mix" })
CREATE (buckwheatSoba:Product { name: "Buckwheat Soba Nodles", type: "Noodle", urls: ["https://www.amazon.com/gp/product/B00101YEBO", "https://veggiekinsblog.com/2020/01/13/vegan-zaru-soba/"]})
CREATE (bulgurWheat:Product { name: "Bulgur Wheat", type: "Grain" })
CREATE (butterUnsalted:Product { name: "Unsalted Butter", type: "Butter" })
CREATE (cabbageGreenSmall:Product { name: "Small, Green Cabbage", type: "Cabbage" })
CREATE (cabbageRedSmall:Product { name: "Cabbage, Red, small", type: "Cabbage" })
CREATE (calamari:Product { name: "Calamari", type: "Seafood" })
CREATE (carrots:Product { name: 'Carrots', type: "Vegetable" })
CREATE (cauliflower:Product { name: "Cauliflower", type: "Vegetable" })
CREATE (cayennePepper:Product { name: "Cayenne Pepper", type: "Spice" })
CREATE (celery:Product { name: "Celery", type: "Vegetable" })
CREATE (chardonnayTerresDorees:Product { name: "chardonnay - terres dorees", type: "Wine" })
CREATE (cheddarSharp:Product { name: "Cheddar - Sharp", type: "Cheese" })
CREATE (cheeseBlue:Product { name: "Cheese - blue", type: "Cheese" })
CREATE (cheeseExtraSharpCheddar:Product { name: "Cheese - Extra Sharp Cheddar", type: "Cheese" })
CREATE (cheeseGruyere:Product { name: "Cheese - Gruyere", type: "Cheese" })
CREATE (cheesePecorino:Product { name: "Cheese - Pecorino", type: "Cheese" })
CREATE (cheeseSharpSwiss:Product { name: "Cheese - Sharp Swiss", type: "Cheese" })
CREATE (cheeseShreddedMozzarella8Oz:Product { name: "Cheese - Shredded Mozzarella - 8 oz", type: "Cheese" })
CREATE (chicken34Lb:Product { name: "Chicken (3-4 lb)", type: "Chicken" })
CREATE (chicken:Product { name: 'chicken', type: "Chicken"})
CREATE (chickenBreast:Product { name: "Chicken Breast", type: "Chicken" })
CREATE (chickenBroth16Oz:Product { name: "Chicken Broth - 16 Oz", type: "Broth" })
CREATE (chickenBroth32Oz:Product { name: "Chicken Broth - 32 Oz", type: "Broth" })
CREATE (chickenBroth:Product { name: 'Chicken Broth', type: "Broth" })
CREATE (chickenBrothSwanson145Oz:Product { name: "Chicken Broth - Swanson, 14.5 Oz", type: "Broth" })
CREATE (chickenElectricRotisserie:Product { name: "chicken - electric - rotisserie", type: "Chicken" })
CREATE (chickenStock:Product { name: "Chicken stock", type: "Stock" })
CREATE (chickenTenderloinsRubberDuckies1BagOnly:Product { name: "Chicken Tenderloins / Rubber Duckies / 1 BAG ONLY", type: "Chicken" })
CREATE (chickenThigh:Product { name: "Chicken thigh", type: "Chicken" })
CREATE (chilesChipotleInAdobo:Product { name: "Chiles - Chipotle in adobo", type: "Peppers" })
CREATE (chineseBroccoli:Product { name: "Chinese Broccoli", type: "Vegetable" })
CREATE (chips:Product { name: "Chips", type: "Snack" })
CREATE (chocolateCoveredCherriesForJoyce:Product { name: "Chocolate covered cherries for Joyce", type: "Candy" })
CREATE (choppedCalabrianPeppers:Product { name: "Chopped Calabrian Peppers", type: "Peppers" })
CREATE (cilantro:Product { name: 'Cilantro', type: "Herb" })
CREATE (cilantroRoots:Product { name: "Cilantro roots", type: "Cilantro"})
CREATE (cinamon:Product { name: "Cinamon", type: "Spice" })
CREATE (cinnamon:Product { name: "Cinnamon", type: "Spice" })
CREATE (clamChowder:Product { name: "Clam Chowder", type: "Soup" })
CREATE (clamJuice:Product { name: "Clam Juice", type: "Juice" })
CREATE (clams:Product { name: "Clams", type: "Seafood" })
CREATE (cleanserBonAmi:Product { name: "Cleanser - Bon Ami", type: "Cleanser" })
CREATE (clovesGarlic:Product { name: "Garlic cloves", type: "Garlic" })
CREATE (cocoaPowderUnsweetenedHersheysNatural8Oz:Product { name: "Cocoa Powder, Unsweetened, Hersheys Natural - 8 Oz", type: "Cocoa" })
CREATE (coconutFlakes:Product { name: "Coconut Flakes", type: "Coconut" })
CREATE (coconutMilk135OzCan:Product { name: "Coconut Milk - 13.5 oz can", type: "Coconut Milk" })
CREATE (coconutMilk:Product { name: "Full fat coconut milk", type: "Coconut Milk" })
CREATE (coconutOil:Product { name: 'Coconut Oil', type: "Cooking Oil" })
CREATE (coffeeBbPlu8875LessYumsThan8863:Product { name: "Coffee - BB - PLU 8875 (less yums than 8863)", type: "Coffee" })
CREATE (coffeeBbs1stPreferenceBbPlu8863EqualExchangePeruvian:Product { name: "Coffee / BB's 1st preference / BB / PLU 8863 / Equal Exchange / Peruvian", type: "Coffee" })
CREATE (coffeeBbs2ndPreferenceBbPlu3794KalaniCoffeeIndonesianEnyanaSumatra:Product { name: "Coffee / BB's 2nd preference / BB / PLU 3794 / Kalani Coffee / Indonesian Enyana Sumatra", type: "Coffee" })
CREATE (coffeeMtmKivuDarkEspressoRoast:Product { name: "Coffee - MTM - Kivu Dark Espresso Roast", type: "Coffee" })
CREATE (coffeeMtmPlu1859FidalgoBayOrganicFairTradeFrenchRoastExtraDark:Product { name: "Coffee - MTM - PLU 1859 - Fidalgo Bay Organic Fair Trade French Roast - Extra Dark", type: "Coffee" })
CREATE (coffeeMtmPlu5820KivuKivuDarkFrenchRoast:Product { name: "Coffee / MTM / PLU 5820 / Kivu / Kivu Dark French Roast", type: "Coffee" })
CREATE (coffeeMtmPlu8368DecafDecafDecafKindUnknown:Product { name: "Coffee / MTM / PLU 8368 / Decaf / Decaf / Decaf Kind Unknown", type: "Decaf Coffee" })
CREATE (coffeeTDecaf:Product { name: "Coffee - T - Decaf", type: "Decaf Coffee" })
CREATE (coffeeTPlu8852TLikesItBbSaysYux:Product { name: "Coffee - T - PLU 8852 T likes it, BB says YUX!", type: "Coffee" })
CREATE (coffeeTPlu8853:Product { name: "Coffee - T - PLU 8853", type: "Coffee" })
CREATE (coffeeTaylorPlu8868:Product { name: "Coffee - Taylor - PLU 8868", type: "Coffee" })
CREATE (cokeZero:Product { name: "Coke Zero", type: "Soda" })
CREATE (collardGreens:Product { name: "Collard Greens", type: "Vegetable" })
CREATE (coolMintChocolateClifBar:Product { name: "cool mint chocolate clif bar", type: "Snack" })
CREATE (coriander:Product { name: "Coriander", type: "Spice" })
CREATE (corianderPowder:Product { name: "Coriander powder", type: "Spice" })
CREATE (corianderSeeds:Product { name: "Coriander seeds", type: "Spice" })
CREATE (cornFrozen:Product { name: "Frozen Corn", type: "Corn" })
CREATE (cornOnCob:Product { name: "Corn on cob", type: "Corn" })
CREATE (cornStarch:Product { name: "Corn Starch", type: "Corn Starch" })
CREATE (cornmeal:Product { name: "Cornmeal", type: "Cornmeal" })
CREATE (cornstarchBabyPowderNotJohnsonsTheyreBaddies:Product { name: "Cornstarch Baby Powder (not Johnson's, they're baddies)", type: "Baby Powder" })
CREATE (cottageCheeseLargeCurd:Product { name: "Large Curd Cottage Cheese", type: "Cottage Cheese" })
CREATE (couscous:Product { name: "Couscous", type: "Couscous" })
CREATE (couscousIsraeli:Product { name: "Israeli Couscous", type: "Couscous" })
CREATE (cranberriesDried:Product { name: "Dried Cranberries", type: "Dried Cranberries" })
CREATE (creamHeavy:Product { name: "Heavy Cream", type: "Cream" })
CREATE (crest:Product { name: "Crest", type: "Toothpaste" })
CREATE (cucumber:Product { name: "Cucumber", type: "Vegetable" })
CREATE (cucumbersEnglish:Product { name: "Cucumbers - English", type: "Vegetable" })
CREATE (cucumbersPersian:Product { name: "Cucumbers - Persian", type: "Vegetable" })
CREATE (cuminGround:Product { name: "Cumin - Ground", type: "Spice" })
CREATE (cuminSeedNotGrounddog:Product { name: "Cumin - Seed (not grounddog)", type: "Spice" })
CREATE (cuminSeeds:Product { name: "Cumin seeds", type: "Spice" })
CREATE (curryPowder:Product { name: "Curry Powder", type: "Spice" })
CREATE (dates:Product { name: "Dates", type: "Fruit" })
CREATE (dill:Product { name: "Dill", type: "Herb" })
CREATE (dillPickles:Product { name: "Dill pickles", type: "Pickles" })
CREATE (dinoKaleUglySpinach:Product { name: "Dino Kale (ugly spinach)", type: "Kale" })
CREATE (driedSeaweed:Product { name: "WEL-PAC Dashi Kombu Dried Seaweed", type: "Seaweed" })
CREATE (driedShrimp:Product { name: "Dried Shrimp", type: "Seafood" })
CREATE (driedThaiShrimpPaste:Product { name: "Dried Thai shrimp paste", type: "Condiment" })
CREATE (dukesMayonnaise:Product { name: "Duke's Mayonnaise", type: "Condiment" })
CREATE (edamame:Product { name: 'Edamame', type: "Edamame"})
CREATE (edamameShelled:Product { name: "Edamame - Shelled", type: "Vegetable" })
CREATE (eggplant:Product { name: "Eggplant", type: "Vegetable" })
CREATE (eggplantChinese:Product { name: "Chinese Eggplant", type: "Eggplant" })
CREATE (eggplantThai:Product { name: "Eggplant - Thai", type: "Vegetable" })
CREATE (eggs:Product { name: 'eggs', type: "Eggs"})
CREATE (eggsDozen:Product { name: "Eggs (Dozen)", type: "Eggs" })
CREATE (eggsLiquidEggWhitesBlueChikn:Product { name: "Eggs - Liquid Egg Whites (Blue Chikn)", type: "Eggs" })
CREATE (enchiladaSauceRed:Product { name: "Enchilada Sauce - Red", type: "Sauce" })
CREATE (endiveOrEscaroleLettce:Product { name: "Endive or Escarole lettce", type: "Lettuce" })
CREATE (englishMuffins:Product { name: "English Muffins", type: "Bread" })
CREATE (farro:Product { name: "Farro", type: "Grain" })
CREATE (fetaYums:Product { name: "Feta Yums", type: "Cheese" })
CREATE (filtersCoffeeSize2:Product { name: "Filters - Coffee size #2", type: "Coffee Filter" })
CREATE (fishSauce:Product { name: "Fish sauce", type: "Sauce" })
CREATE (fishSauceRedBoatPremium:Product { name: "Fish Sauce - Red Boat Premium", type: "Sauce" })
CREATE (fishTilapia:Product { name: "Fish - Tilapia", type: "Seafood" })
CREATE (flourWhiteAllpurposeUnbleachedIfPossibleButNoBigs:Product { name: "Flour - White, all-purpose (Unbleached if possible but no bigs)", type: "Flour" })
CREATE (flourWholeWheatAllpurpose:Product { name: "Flour - Whole wheat, all-purpose", type: "Flour" })
CREATE (franciscoInternationalFrenchSandwichRolls6Count:Product { name: "Francisco International French Sandwich Rolls 6 Count", type: "Bread" })
CREATE (friedShallots:Product { name: "Fried shallots", type: "Condiment" })
CREATE (frozenMangos:Product { name: "Frozen Mangos", type: "Frozen Fruit" })
CREATE (frozenPeas:Product { name: "Frozen Peas", type: "Frozen Vegetable" })
CREATE (garamMasala:Product { name: "Garam Masala", type: "Spice" })
CREATE (garbanzoBeansDry:Product { name: "Garbanzo Beans - Dry", type: "Beans" })
CREATE (garlic:Product { name: 'Garlic', type: "Herb" })
CREATE (garlicChives:Product { name: 'garlic chives', type: "Chives"})
CREATE (garlicChivesAlternativeChives:Product { name: "Garlic Chives (alternative: chives)", type: "Herb" })
CREATE (garlicPowder:Product { name: "Garlic Powder", type: "Spice" })
CREATE (ginger:Product { name: 'Ginger', type: 'Ginger'})
CREATE (gingerPowder:Product { name: "Ginger Powder", type: "Spice" })
CREATE (gingerRoot:Product { name: "Ginger root", type: "Herb" })
CREATE (gochugaru:Product { name: "Gochugaru", type: "Spice" })
CREATE (grainsOfParadiseSpice:Product { name: "Grains Of Paradise spice", type: "Spice" })
CREATE (granolaCookies:Product { name: "Granola 'cookies'", type: "Snack" })
CREATE (grapesGrapeShaped:Product { name: "Grapes, grape shaped", type: "Fruit" })
CREATE (greenOnion:Product {name: 'Green Onion', type: "Vegetable" })
CREATE (gritsQuick:Product { name: "Grits - Quick", type: "Grain" })
CREATE (groundBeef:Product { name: "Ground Beef", type: "Meat" })
CREATE (habanero:Product { name: "Habanero", type: "Pepper" })
CREATE (halfgallonHalfHalf:Product { name: "Half-gallon half & half", type: "Dairy" })
CREATE (hamSliced:Product { name: "ham sliced", type: "Meat" })
CREATE (heavyCream:Product { name: "Heavy Cream", type: "Dairy" })
CREATE (herbsOrSuperGreensLettuce:Product { name: "Herbs or super greens lettuce", type: "Lettuce" })
CREATE (herbsOrSuperGreensLettucesBucket:Product { name: "Herbs or super greens lettuces bucket", type: "Lettuce" })
CREATE (honey:Product { name: 'Honey', type: "Honey"})
CREATE (honeyInGlassJar:Product { name: "Honey in glass jar?", type: "Honey" })
CREATE (iceCreamChocolateSignatureBrand:Product { name: "Signature brand Chocolate Ice cream", type: "Ice Cream"})
CREATE (iceCreamCones:Product { name: "Ice Cream Cones", type: "Ice Cream Cones"})
CREATE (iceCreamDoublefudgeBrownieDreyersSlowchurned:Product { name: "Ice cream double-fudge brownie Dreyer's slow-churned", type: "Ice Cream"})
CREATE (italianSeasoning:Product { name: "Italian Seasoning", type: "Italian Seasoning"})
CREATE (japaneseNori:Product { name: "Japanese Nori", urls: ["https://www.google.com/search?client=emacs&sca_esv=577922779&sxsrf=AM9HkKkUxzT-KjHg9ziVgvqz5Zsqmn7xdw:1698703946500&q=Japanese+nori&tbm=isch&source=lnms&sa=X&ved=2ahUKEwi647yq5Z6CAxVxMjQIHRW8BBYQ0pQJegQIChAB&biw=1440&bih=758&dpr=2"], type: "Nori"})
CREATE (johnsonsCreamyBabyOil:Product { name: "Johnsons Creamy Baby Oil", type: "Baby Oil"})
CREATE (kaffirLime:Product { name: "Kaffir Lime", urls: ["https://www.google.com/search?sca_esv=579007228&sxsrf=AM9HkKkqQcpTokvs8EUmjT-DnZNXV9I6Lw:1698970375605&q=kaffir+lime&tbm=isch&source=lnms&sa=X&ved=2ahUKEwiH6eLtxaaCAxVnMDQIHZ94DUYQ0pQJegQIDhAB&biw=1440&bih=758&dpr=2"], type: "Kaffir Lime"})
CREATE (kaffirLimeLeaves:Product { name: "Kaffir lime leaves", urls: ["https://www.wholefoodsmarket.com/product/kaffir-lime%20leaves-b07q8ldbvj", "https://www.youtube.com/watch?v=4Qz5nC-DcKk", "https://www.safeway.com/shop/marketplace/product-details.970537048.html", "https://photos.google.com/photo/AF1QipPI_6_YxYIuCSAvP93sDoRcyFDjekCQjNSb3Ln0", "https://photos.google.com/photo/AF1QipPd_yNuI9VcQAFOwMSuvBx40o_sl4gAmCgBYNIQ", "https://www.youtube.com/watch?v=SB3AV7oHKiE"], type: "Kaffir Lime Leaves"})
CREATE (kale:Product { name: "Kale", type: "Kale"})
CREATE (katchup:Product { name: "Katchup", type: "Katchup"})
CREATE (kidneyBeansRedOrganic15Oz:Product { name: "Kidney Beans, Red, Organic, 15 Oz", type: "Kidney Beans"})
CREATE (kidneyBeansSw:Product { name: "Kidney Beans - S&W", type: "Kidney Beans"})
CREATE (kikkomanJapaneseNoodleSoupBaseHonTsuyu:Product { name: "Kikkoman Japanese Noodle Soup Base (Hon Tsuyu)", manufacturer: "Kikkoman", type: "Sauce", urls: ["https://www.amazon.com/Kikkoman-Japanese-Noodle-Soup-Tsuyu/dp/B002Z3F0IW",  "https://www.google.com/search?q=kikkoman+japanese+noodle+soup+base(hon+tsuyu)&oq=Kikkoman+Japanese+Noodle+Soup+Base(Hon+Tsuyu)&gs_lcrp=EgZjaHJvbWUqBwgAEAAYgAQyBwgAEAAYgAQyBwgBEAAYgAQyCggCEAAYhgMYigUyCggDEAAYhgMYigUyBggEEEUYPDIGCAUQRRg9MgYIBhBFGD3SAQc0NzBqMGo0qAIAsAIA&sourceid=chrome&ie=UTF-8", "https://www.youtube.com/watch?v=61nPpDkz1AI"] })
CREATE (kombucha:Product { name: "Kombucha", type: "Kombucha"})
CREATE (leeKumKeeSoySaucePremiumDarkBottle:Product { name: "Lee Kum Kee Soy Sauce Premium Dark Bottle", urls:["https://www.safeway.com/shop/product-details.960097003.html","https://www.amazon.com/Lee-Kum-Kee-Premium-16-9-Ounce/dp/B003U2AAQY/ref=sr_1_5?keywords=dark+soy+sauce&qid=1669684317&sprefix=dark+soy%2Caps%2C145&sr=8-5"], type: "Soy Sauce"})
CREATE (lemon:Product { name: "Lemon", type: "Lemon"})
CREATE (lemonJuice:Product { name: "Lemon Juice", type: "Lemon Juice"})
CREATE (lemonZestGratedLemonRind:Product { name: "Lemon Zest (grated lemon rind)", type: "Lemon Zest"})
CREATE (lemongrass:Product { name: 'Lemongrass', type: 'Lemongrass'})
CREATE (lentilsBlackBeluga:Product { name: "Black, Beluga Lentils", type: "Lentils"})
CREATE (lentilsBrown:Product { name: "Brown Lentils", type: "Lentils"})
CREATE (lentilsGreen:Product { name: "Green Lentils", type: "Lentils"})
CREATE (lettucesRomaine:Product { name: "Romaine Lettuce", type: "Romaine"})
CREATE (lightBrownSugar:Product {name: 'Light Brown Sugar', type: "Brown Sugar"})
CREATE (lime:Product { name: "Lime", type: "Lime"})
CREATE (limeJuice:Product { name: "Lime juice", type: "Lime juice"})
CREATE (limeLeavesKaffir:Product { name: "Kaffir Lime Leaves", type: "Lime Leaves"})
CREATE (limes:Product { name: "Limes", type: "Limes"})
CREATE (lobsterCornChowder:Product { name: "Lobster Corn Chowder", type: "Corn Chowder"})
CREATE (maesriThaiRedCurryPaste:Product { name: 'Maesri Thai Red Curry Paste', urls:["https://www.wholefoodsmarket.com/product/maesri-red-curry-paste-b0013esw84", "https://www.safeway.com/shop/product-details.970519982.html?cmpid=ps_swy_sea_ecom_goo_20200924_71700000073186042_58700007112018081_92700063963421736&r=https%3A%2F%2Fwww.google.com%2F"], type: "Curry Paste"})
CREATE (makrutLimeZest:Product { name: "Makrut lime zest", type: "Makrut Lime",urls:["https://www.google.com/search?client=emacs&sca_esv=579520937&sxsrf=AM9HkKlUrnbTZeiuHkGuxjA6wsla9_IkfQ:1699140927441&q=Makrut+Lime&tbm=isch&source=lnms&sa=X&ved=2ahUKEwir5pybwauCAxXfLTQIHYj1DqQQ0pQJegQICxAB&biw=1440&bih=758&dpr=2"]})
CREATE (maltomeal:Product { name: "Malt-o-Meal", type: "Malt-o-Meal"})
CREATE (marjoramLeaves:Product { name: "Marjoram Leaves", type: "Marjoram Leaves"})
CREATE (marketspiceTeaDecaf2OzForMommy:Product { name: "Marketspice Tea Decaf - 2 Oz for Mommy", type: "Marketspice Tea"})
CREATE (martianmallowsLargeButNotGigantic:Product { name: "Martianmallows - Large but not gigantic", type: "Marshmellos"})
CREATE (meatSliced:Product { name: "Sliced Meat", type: "Sandwitch Meat"})
CREATE (merlot:Product { name: "Merlot", type: "Merlot"})
CREATE (mildDriedChilies:Product { name: "Mild dried red chilies", type: "Dry Chilies"})
CREATE (mintOrMintExtract:Product { name: "Mint or Mint Extract", type: "Mint Extract"})
CREATE (miso:Product { name: 'Miso', type: "Miso"})
CREATE (misoPaste:Product { name: "Miso Paste", type: "Miso"})
CREATE (misoSweetWhite:Product { name: "Sweet White Miso", type: "Miso"})
CREATE (molasses:Product { name: "Molasses", type: "Molasses"})
CREATE (mouthwashActRestoring:Product { name: "ACT Restoring Mouthwash", type: "Mouthwash"})
CREATE (mushroomsCrimini:Product { name: "Crimini Mushrooms", type: "Mushrooms"})
CREATE (mushroomsPortobello:Product { name: "Portobello Mushrooms", type: "Mushrooms"})
CREATE (mustardGermanMediumHotInJarWHandle:Product { name: "German Mustard medium hot in jar w/ handle", type: "Mustard"})
CREATE (mustardSpicyBrownInGlassJarPlease:Product { name: "Spicy Brown Mustard in glass jar please", type: "Mustard"})
CREATE (myntzes:Product { name: "Myntzes", type: "Myntzes"})
CREATE (noodlesLasagna:Product { name: "Lasagna Noodles", type: "Lasagna Noodles"})
CREATE (nutmeg:Product { name: "Nutmeg", type: "Nutmeg"})
CREATE (oOrganicsOrganicCoconutOilVirginUnrefined:Product { name: "O Organics Organic Coconut Oil Virgin Unrefined", type: "Coconut Oil"})
CREATE (oil:Product {name: 'Cooking Oil', type: "Oil"})
CREATE (oilAvocado:Product { name: "Avocado Oil", type: "Avocado Oil"})
CREATE (oilOliveExtraVirgin:Product { name: "Extra Virgin Olive Oil", type: "Olive Oil"})
CREATE (oliveOrCoconutOil:Product { name: "Olive or coconut oil", type: "Olive Oil"})
CREATE (olivesCastelvetrano:Product { name: "Castelvetrano Olives", type: "Olives"})
CREATE (olivesKalamataPitted:Product { name: "Pitted Kalamata Olives", type: "Olives"})
CREATE (onePercentMilkYellowCarton:Product { name: "One Percent Milk yellow carton", type: "Milk"})
CREATE (onePercentOr2PercentMilkInGlassJarNotRedCapWholeMilk:Product { name: "One Percent or 2 Percent Milk in Glass Jar (Not Red Cap Whole Milk)", type: "Milk" })
CREATE (tomatillos:Product {name: 'Tomatillos', type:"Tomatillos" })
CREATE (whiteOnion:Product {name: 'White Onion', type: "Onion"})
CREATE (jalapeno:Product {name: 'Jalapeño', type:"Jalapeño"})
CREATE (onion:Product { name: "Onion", type: "Vegetable" })
CREATE (onionPowder:Product { name: "Onion Powder", type: "Seasoning" })
CREATE (onionRed:Product { name: "Red Onion", type: "Vegetable" })
CREATE (onionSweet:Product { name: "Sweet Onion", type: "Vegetable" })
CREATE (onionWhite1:Product { name: "White Onion (1)", type: "Vegetable" })
CREATE (onions:Product { name: "Onions", type: "Vegetable" })
CREATE (orangeJuice:Product { name: "Orange Juice", type: "Beverage" })
CREATE (oranges:Product { name: "Oranges", type: "Fruit" })
CREATE (oregano:Product { name: "Oregano", type: "Seasoning" })
CREATE (organicSaladFreshHerbBlend:Product { name: "Organic Salad Fresh Herb Blend", type: "Salad" })
CREATE (oysterMushrooms:Product { name: "Oyster Mushrooms", type: "Mushroom" })
CREATE (oysterSauce:Product { name: "Oyster Sauce", type: "Sauce" })
CREATE (padThaiSauce:Product { name: "Pad Thai Sauce", type: "Sauce" })
CREATE (palmSugar:Product { name: "Palm Sugar", type: "Sugar" })
CREATE (pancakeMixSnoqualmieFallsLodge:Product { name: "Pancake Mix - Snoqualmie Falls Lodge", type: "Mix" })
CREATE (sweetPaprika:Product { name: 'sweet paprika', type: "Paprika"})
CREATE (paprika:Product { name: "Paprika", type: "Seasoning" })
CREATE (paprikaSmoked:Product { name: "Smoked Paprika", type: "Seasoning" })
CREATE (parmesanCheese:Product { name: "Parmesan Cheese", type: "Cheese" })
CREATE (parsley:Product { name: "Parsley", type: "Herb" })
CREATE (pastaFettuccine:Product { name: "Fettuccine", type: "Pasta" })
CREATE (pastaLinguine:Product { name: "Linguine", type: "Pasta" })
CREATE (pastaRigatoni:Product { name: "Rigatoni", type: "Pasta" })
CREATE (pastaTrottole:Product { name: "Trottole", type: "Pasta" })
CREATE (peanutButterAdamsUnsalted:Product { name: "Adams Peanut Butter", type: "Peanut Butter" })
CREATE (peanutButterBulk:Product { name: "Bulk Peanut Butter", type: "Peanut Butter" })
CREATE (peanutOil:Product { name: "Peanut Oil", type: "Oil" })
CREATE (peanuts:Product { name: "Dry-Roasted Unsalted Peanuts", type: "Nuts" })
CREATE (pearsAnjou:Product { name: "Anjou Pears", type: "Pear" })
CREATE (pearsBartlett:Product { name: "Bartlett Pears", type: "Pear" })
CREATE (pearsBosc:Product { name: "Bosc Pears", type: "Pear" })
CREATE (pepperBlackBulk:Product { name: "Black Pepper, Bulk", type: "Spice" })
CREATE (pepperChipotle:Product { name: "Chipotle Pepper", type: "Spice" })
CREATE (pepperFlakesSpiceyRedPepperFlakes:Product { name: "Spicy Red Pepper Flakes", type: "Spice" })
CREATE (pepperJalapeno:Product { name: "Jalapeno Pepper", type: "Pepper" })
CREATE (pepperSerrano:Product { name: "Serrano Pepper", type: "Pepper" })
CREATE (peppercornsWholeBlack:Product { name: "Whole Black Peppercorns", type: "Spice" })
CREATE (periPeriSauceGarlic:Product { name: "Garlic Peri Peri Sauce", type: "Sauce" })
CREATE (perillaOil:Product { name: "Perilla Oil", type: "Oil", urls: ["https://www.youtube.com/watch?v=VpAS3RarPi8", "https://megakfood.com/products/8801045448503", "https://photos.google.com/photo/AF1QipNe7d-KXSpC90FJ1uJNMnH1fMFZ6E8Qlzr_j3Q0", "https://photos.google.com/photo/AF1QipOLrXnJ8Bj20xFh5lg5yhm71ApUoRlT1z6_ZqnB", "https://photos.google.com/photo/AF1QipP8OZZvarZPkNnnaOOv3k_ng9doQzMeVZgONlxK"] })
CREATE (pineNuts:Product { name: "Pine Nuts", type: "Pine nuts" })
CREATE (pinotGrigioDryWhiteWine:Product { name: "Pinot Grigio - Dry White Wine", type: "Wine" })
CREATE (pistachios:Product { name: "Pistachios", type: "Pistachios" })
CREATE (plums:Product { name: "Plums", type: "Plumbs" })
CREATE (polenta:Product { name: "Polenta", type: "Polenta" })
CREATE (popcorn:Product { name: "Popcorn", type: "Popcorn" })
CREATE (pork:Product { name: "Pork", type: "Pork" })
CREATE (potatoesBabyTriColor:Product { name: "Potatoes - Baby / Tri Color", type: "Potatoe" })
CREATE (potatoesRusset:Product { name: "Russet Potatoes", type: "Russet Potatoe" })
CREATE (primoTaglioCheeseGoat4Oz:Product { name: "Primo Taglio Cheese Goat - 4 Oz", type: "Goat Cheese" })
CREATE (prunes:Product { name: "Prunes", type: "Prune" })
CREATE (pumpkinSeedsSalted:Product { name: "Salted Pumpkin seeds", type: "Pumpkin seed" })
CREATE (quickRolledOatsOatsPlu8485:Product { name: "Quick Rolled Oats / Oats PLU 8485", type: "Rolled Oats" })
CREATE (quinoaRed:Product { name: "Quinoa - Red", type: "Grain" })
CREATE (quinoaWhite:Product { name: "Quinoa - White", type: "Quinoa" })
CREATE (radish:Product { name: "Radish", type: "Radish" })
CREATE (raisinsBulkBabyBulk:Product { name: "Raisins - Bulk baby, bulk", type: "Raisins" })
CREATE (ramenNoodlesDry:Product { name: "Ramen Noodles - Dry", type: "Ramen Noodles" })
CREATE (redBellPepper:Product { name: "Red Bell Pepper", type: "Bell Pepper" })
CREATE (redChili:Product { name: 'Red Chili', type: "Pepper" })
CREATE (redChilliPeppers:Product { name: "Red Chilli Peppers", type: "Chilli Pepper" })
CREATE (redCurryPaste:Product { name: 'Red Curry Paste', type: "Curry Paste" })
CREATE (redGreenYellaPeppers:Product { name: "Red, Green, Yella Peppers", type: "Bell Pepper" })
CREATE (redLentils:Product { name: "Red Lentils", type: "Legumes", urls: ["https://images.albertsons-media.com/is/image/ABS/127100073-ECOM","https://www.google.com/search?q=don+pancho+gorditas&sxsrf=ALiCzsbRwUHe7CL6uuSFX0okDfWkDvjqnQ:1665076315963&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjO0djSjMz6AhVLMjQIHZGcAbAQ_AUoAXoECAIQAw&biw=1107&bih=574&dpr=2.5#imgrc=Z2KBPh70c6uKAM"] })
CREATE (refriedBeans:Product { name: "Vegitarian Beans in can", type: "Beans in can" })
CREATE (reynoldsParchmentPaperGenuineNonstick45SqFt:Product { name: "Reynolds Parchment Paper Genuine Non-Stick 45 Sq. Ft.", type: "Kitchen Supplies" })
CREATE (rice:Product { name: 'Rice', type: "Rice" })
CREATE (riceBrown:Product { name: "Rice - Brown", type: "Rice" })
CREATE (riceNikoNikoSushiShortGrainRice:Product { name: "Rice - Niko Niko - Sushi - Short Grain Rice", type: "Rice" })
CREATE (riceNoodleSheets:Product { name: "Rice Noodle Sheets", type: "Rice Noodles" })
CREATE (riceSticks:Product { name: "Rice Sticks", type: "Rice Noodles", urls:["https://www.google.com/search?q=Rice%20Sticks"] })
CREATE (riceWhiteBasmati:Product { name: "White Basmati Rice", type: "Basmati Rice" })
CREATE (riceWild:Product { name: "Rice - Wild", type: "Rice" })
CREATE (riceWineVinegar:Product { name: "Rice Wine Vinegar", type: "Vinegar" })
CREATE (riceWineVinegarKikkomanMirin:Product { name: "Rice Wine Vinegar - Kikkoman Mirin", type: "Vinegar" })
CREATE (riceWineVinegarSake:Product { name: "Sake Rice Wine Vinegar", type: "Rice Wine Vinegar" })
CREATE (ricottaCheese15Oz:Product { name: "Ricotta Cheese", type: "Cheese" })
CREATE (roastBeef:Product { name: "Roast Beef", type: "Beef" })
CREATE (roastedUnsaltedPeanuts:Product { name: "Roasted Unsalted Peanuts", type: "Peanuts" })
CREATE (rolledOatsOatsOldFashionedPlu8490:Product { name: "Rolled Oats / Oats / Old Fashioned / PLU 8490", type: "Oats" })
CREATE (romaineLettuceHearts:Product { name: "Romaine Lettuce Hearts", type: "Romain" })
CREATE (russetPotatoes:Product { name: 'Russet Potatoes', type: "Potatoes" })
CREATE (sage:Product { name: "Sage", type: "Herb" })
CREATE (salmonCanned:Product { name: "Canned Salmon", type: "Salmon" })
CREATE (salmonFresh:Product { name: "Fresh Salmon", type: "Salmon" })
CREATE (salmonSmoked:Product { name: "Smoked Salmon", type: "Salmon" })
CREATE (salmonStillFrozenInTheShrinkWrap2Or3Lbs:Product { name: "Salmon - Still Frozen in the Shrink Wrap, 2 or 3 lbs", type: "Salmon" })
CREATE (salt:Product { name: "Salt", type: "Salt" })
CREATE (saltedTurnip:Product { name: 'Salted Turnip', type: "Salted Turnip" })
CREATE (saltinesUnsalted:Product { name: "Saltines - Unsalted", type: "Saltines" })
CREATE (sauceForSpaghettis:Product { name: "Sauce for Spaghettis", type: "Spaghetti Sauce" })
CREATE (sausage:Product { name: "Sausage", type: "Sausage" })
CREATE (savoySpinachUglySpinach:Product { name: "Savoy Spinach - Ugly Spinach", type: "Spinach" })
CREATE (scallionsOrChives:Product { name: "Scallions or Chives", type: "Scalions" })
CREATE (seaweed:Product {name: 'Toasted Seaweed', type: "Seaweed"})
CREATE (seedsSunflower:Product { name: "Sunflower Seeds", type: "Sunflower Seeds"})
CREATE (semiSweetChocolateChips:Product { name: "Semi Sweet Chocolate Chips", type: "Chocolate Chips"})
CREATE (serranos:Product { name: "Serranos", type: "Serrano Peppers"})
CREATE (sesameButterTahini:Product { name: "Sesame Butter Tahini", type: "Tahini"})
CREATE (sesameOil:Product {name: 'Korean Wild Sesame Oil', type: "Sesame Oil"})
CREATE (sesameOilToasted:Product { name: "Toasted Sesame Oil", type: "Sesame Oil"})
CREATE (sesameSeeds:Product { name: "Sesame Seeds", type: "Sesame Seeds"})
CREATE (sesameSeedsToasted:Product { name: "Toasted Sesame Seeds", type: "Sesame Seeds"})
CREATE (shallotsFried:Product { name: "Fried Shallots", type: "Fried Shallots"})
CREATE (shawarmaBeefSirloin:Product { name: "Shawarma Beef Sirloin", type: "Beef"})
CREATE (shrimp:Product { name: 'Shrimp', type: "Shrimp"})
CREATE (shrimpFrozen:Product { name: "Frozen Shrimp", type: "Shrimp"})
CREATE (shrimpLargeNotFrozen:Product { name: "Large Shrimp (not frozen)", type: "Shrimp"})
CREATE (shrimpPaste:Product { name: 'Shrimp Paste', type: 'Shrimp Paste'})
CREATE (signatureSelectBeansGarbanzo15Oz:Product { name: "Signature Select Garbanzo Beans - 15 Oz", type: "Garbanzo Beans"})
CREATE (signatureSelectCrackersGrahamHoney:Product { name: "Signature Select Honey Graham Crackers", type: "Graham Crackers"})
CREATE (snowPeas:Product { name: "Snow peas", type: "Snow Peas"})
CREATE (dishSoap:Product { name: "Dish Soap", type: "Dish Soap"})
CREATE (sobaNoodles:Product { name: 'Soba Noodles', type: "Soba Noodles"})
CREATE (sonicareSoftBristles:Product { name: "Sonicare soft bristles", type: "Sonicare Bristles"})
CREATE (sourdoughBread:Product { name: "Sourdough bread", type: "Bread" })
CREATE (soySauceLiquidAminos:Product { name: "Soy Sauce - Liquid Aminos", type: "Sauce" })
CREATE (spicyDriedChilies:Product { name: "Spicy dried red chilies", type: "Dry Chilies"})
CREATE (spinach:Product { name: "Spinach", type: "Spinach" })
CREATE (spinachFrozen:Product { name: "Frozen Spinach", type: "Spinach" })
CREATE (squashButternut:Product { name: "Butternut Squash", type: "Squash" })
CREATE (squashYellowCrookneck:Product { name: "Yellow Crookneck Squash", type: "Squash" })
CREATE (squid:Product { name: "Squid", type: "Seafood" })
CREATE (sriracha:Product { name: 'Sriracha', type: "Sriracha"})
CREATE (stockVegetableDry:Product { name: "Dry Vegetable bouillon", type: "bouillon" })
CREATE (stockWater:Product {name: 'Stock / Water', type: 'Liquid Stock/Water'})
CREATE (strongRootsKaleQuinoaBurger:Product { name: "Strong Roots Kale & Quinoa Burger", type: "Burger" })
CREATE (sugar:Product { name: 'Sugar', type: "sugar"})
CREATE (sugarPalm:Product { name: "Sugar - Palm", type: "Sugar" })
CREATE (sugarPureCane:Product { type: "Sugar", name: "Pure Cane Sugar" })
CREATE (sugarSnapPeas:Product { name: 'Sugar Snap Peas', type:  "Snow Peas"})
CREATE (sundriedTomatoes:Product { name: "Sundried Tomatoes", type: "Sundried Tomatoes"})
CREATE (superGreensBabySpinachBabyChardBabyKale:Product { name: "Super Greens Baby Spinach Baby Chard Baby Kale", type: "Kale"})
CREATE (syrupMaple:Product { name: "Maple Syrup" , type: "Maple Syrup"})
CREATE (tamari:Product { name: 'Tamari', type: "Tamari"})
CREATE (tamarindPaste:Product { name: 'Tamarind Paste', type: "Tamarind Paste"})
CREATE (tapatioHotSauce:Product { name: "Tapatio Hot Sauce", type: "Tapatio Hot Sauce"})
CREATE (tapePainters:Product { name: "Painters Tape", type: "Household utilities" })
CREATE (tarragon:Product { name: "Tarragon", type: "Tarragon" })
CREATE (teffFlour:Product { name: "Teff flour", type: "Teff flour" })
CREATE (texturizedVegetableProtein:Product { name: "texturized vegetable protein", type: "Protein" })
CREATE (thaiBasil:Product { name: "Thai basil", type: "Herb", urls: ["https://www.fredmeyer.com/p/simple-truth-organic-thai-basil/0001111001922"] })
CREATE (thaiChilies:Product { name: "Thai chilies", type: "Pepper" })
CREATE (thaiEggplant:Product { name: "Thai Eggplant", type: "Vegetable" })
CREATE (thaiFishSauce:Product { name: 'Thai Fish Sauce', type: "Thai Fish Sauce"})
CREATE (thaiKitchenRiceNoodlesStirFry:Product { name: "Thai Kitchen Rice Noodles Stir Fry", type: "Noodles" })
CREATE (thaiRedCurrySauce:Product { name: "Thai Red Curry Sauce", type: "Sauce" })
CREATE (thaiShrimpPaste:Product { name: "Dried Thai shrimp paste", type: "Condiment", urls: ["https://www.eatingthaifood.com/thai-nam-prik-kapi-recipe/"], comments: ["thaiShrimpPasteComment1", "thaiShrimpPasteComment2"], google: ["shrimp paste kapi OR gabi OR gkabi"] })
CREATE (thinMiniRiceCrackerSnackers:Product { name: "Thin mini rice cracker snackers", type: "Snack" })
CREATE (thinSlicerForShallots:Product { name: "Thin slicer for Shallots", type: "Kitchen Tool" })
CREATE (thyme:Product { name: "Thyme", type: "Herb" })
CREATE (thymeFresh:Product { name: "Thyme - Fresh", type: "Herb" })
CREATE (toastedSesameOil:Product { name: 'Toasted Sesame Oil', type: "Sesame Oil"})
CREATE (tofu:Product { name: 'Thai-style Baked Tofu', type: "Tofu"})
CREATE (tofuBaked:Product { name: "Tofu - Baked", type: "Tofu" })
CREATE (tofuExtraFirm:Product { name: "Tofu - extra firm", type: "Tofu" })
CREATE (tofuSweetBbqPremarinatedSuperFirmBakedTofu:Product { name: "Tofu - Sweet BBQ Pre-Marinated Super Firm Baked Tofu", type: "Tofu" })
CREATE (toiletPaperBathTissue:Product { name: "Toilet Paper bath tissue", type: "Household" })
CREATE (tomatillo:Product { name: "Tomatillo", type: "Tomatillo" })
CREATE (tomatoPaste6OzCan:Product { name: "Tomato Paste - 6 oz can", type: "Tomato Paste" })
CREATE (tomatoSauce15OzCan:Product { name: "Tomato Sauce - 15 oz can", type: "Tomato Sauce" })
CREATE (tomatoSauce29OzCan:Product { name: "Tomato Sauce - 29 oz can", type: "Tomato Sauce" })
CREATE (tomatoesBeefsteak:Product { name: "Beefsteak Tomatoes", type: "Tomatoes" })
CREATE (tomatoesCherry:Product { name: "Tomatoes - Cherry", type: "Vegetable" })
CREATE (tomatoesCrushedInCan28Oz:Product { name: "Tomatoes - Crushed in can 28 Oz", type: "Canned Goods" })
CREATE (tomatoesDicedInBigCan28Oz:Product { name: "Tomatoes - Diced in big can 28 Oz", type: "Canned Goods" })
CREATE (tomatoesHeirloom:Product { name: "Tomatoes - Heirloom", type: "Vegetable" })
CREATE (tomatoesPeeledInCan28Oz:Product { name: "Tomatoes - Peeled in can 28 Oz", type: "Canned Goods" })
CREATE (tomatoesRoma:Product { name: "Tomatoes - Roma", type: "Vegetable" })
CREATE (tomatoesSunDriedRealBigJar:Product { name: "Tomatoes - sun dried - real big jar", type: "Canned Goods" })
CREATE (tomatosInCan15OzCan:Product { name: "Tomatos in can (15 oz can)", type: "Canned Goods" })
CREATE (tortellini:Product { name: "Tortellini", type: "Pasta" })
CREATE (tortillaFlourLargeDiameterDonPanchoOrSafewayBrand:Product { name: "Tortilla - Flour large diameter Don Pancho or Safeway brand", type: "Tortilla" })
CREATE (tsuyu:Product { name: 'Tsuyu', type: "Sauce", googleSearch: "tsuyu, soup seasoning sauce", urls:["https://www.google.com/search?q=tsuyu+soup+seasoning+sauce&oq=tsuyu+soup+seasoning+sauce"] })
CREATE (tumeric:Product { name: "Tumeric", type: "Spice" })
CREATE (tumericPowder:Product { name: "Tumeric Powder", type: "Spice" })
CREATE (tunaInACan:Product { name: "Tuna in a can", type: "Seafood" })
CREATE (tunaSteak:Product { name: "Tuna Steak", type: "Seafood", urls:["https://www.google.com/search?sca_esv=579460677&sxsrf=AM9HkKkoi0-mYGSGw3hXPB2zr6WuVWirbw:1699111461041&q=Tuna+Steak&tbm=isch&source=lnms&sa=X&ved=2ahUKEwiitca406qCAxXOITQIHfJnBXsQ0pQJegQIDRAB&biw=1440&bih=758&dpr=2"] })
CREATE (turkey:Product { name: "Turkey", type: "Poultry" })
CREATE (turkeyBacon:Product { name: "Turkey Bacon", type: "Poultry" })
CREATE (turkeyGround:Product { name: "Ground Turkey", type: "Poultry" })
CREATE (turkeyWhole:Product { name: "Whole Turkey", type: "Poultry" })
CREATE (turmeric:Product { name: "Turmeric", type: "Spice" })
CREATE (unsaltedTopsUnsaltedSalteens:Product { name: "Unsalted Tops (Unsalted Salteens)", type: "Snack" })
CREATE (vegenaise:Product { name: "Vegenaise", type: "Condiment", detail: "Vegenaise - Follow Your Heart Dressing Vegenaise For Vegetarians - 16 Fl. Oz.", urls: ["https://www.qfc.com/p/duke-s-real-mayonnaise/0005250005005?fulfillment=PICKUP&searchType=mktg+attribute","https://www.youtube.com/watch?v=dZLkmXCAK8w"] })
CREATE (vegetableOil:Product { name: 'Vegetable Oil', type: "Cooking Oil" })
CREATE (vinegarAppleCider:Product { name: "Apple Cider Vinegar", type: "Vinegar" })
CREATE (vinegarAppleCiderInGlassBottleNonOrganic:Product { name: "Apple Cider Vinegar in Glass Bottle (Non-Organic)", type: "Vinegar" })
CREATE (vinegarBalsamic:Product { name: "Balsamic Vinegar", type: "Vinegar" })
CREATE (vinegarRedWine:Product { name: "Red Wine Vinegar", type: "Vinegar" })
CREATE (vinegarRiceVinegar:Product { name: "Rice Vinegar", type: "Vinegar" })
CREATE (vinegarWhite:Product { name: "White Vinegar", type: "Vinegar" })
CREATE (watermelon:Product { name: "Watermelon", type: "Fruit" })
CREATE (wheatBerries:Product { name: "Wheat Berries", type: "Grain" })
CREATE (whitePeppercorns:Product { name: "White Peppercorns", type: "Spice" })
CREATE (wineCharlesShaw:Product { name: "Charles Shaw Wine", type: "Wine" })
CREATE (worcestershireSauce:Product { name: "Worcestershire Sauce", type: "Condiment" })
CREATE (yams:Product { name: "Yams", type: "Yam" })
CREATE (yeastActivedry:Product { name: "Yeast (Active Dry)", type: "Yeast" })
CREATE (yellowCurryPowder:Product { name: 'Yellow Curry Powder', type: "Spice", urls: ["https://www.google.com/search?q=Yellow+Curry+Powder+near+me&tbm=isch&ved=2ahUKEwiVxLm7h6mCAxWIFjQIHTNwBKoQ2-cCegQIABAA&oq=Yellow+Curry+Powder+near+me&gs_lcp=CgNpbWcQAzIHCAAQGBCABDoECCMQJzoGCAAQBxAeOgYIABAIEB46BAgAEB46BggAEAUQHlDIBViIEGD3EWgAcAB4AIABS4gBkQSSAQE5mAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=QoxFZZWbEYit0PEPs-CR0Ao&bih=758&biw=1440&client=emacs"] })
CREATE (yellowOnion:Product { name: 'Yellow Onion', type: "Onion" })
CREATE (yogurtFlyingCowCreameryYogurtInReturnableGlassContainer:Product { name: "Yogurt in Returnable Glass Container", type: "Yogurt" })
CREATE (yogurtNonfatPlainblueBucket:Product { name: "Nonfat Yogurt (Plain/Blue Bucket)", type: "Yogurt" })
CREATE (yukonGoldPotatoes:Product { name: "Yukon Gold Potatoes", type: "Potatoes" })
CREATE (zucchini:Product { name: "Zucchini", type: "Zucchini" })

CREATE (salsaVerde)-[:CONTAINS {quantity: '1 1/2 pounds'}]->(tomatillos)
CREATE (salsaVerde)-[:CONTAINS {quantity: '1/2 cup'}]->(whiteOnion)
CREATE (salsaVerde)-[:CONTAINS {quantity: '2 cloves (or more)'}]->(garlic)
CREATE (salsaVerde)-[:CONTAINS {quantity: '1/2 cup'}]->(cilantro)
CREATE (salsaVerde)-[:CONTAINS {quantity: '1 tablespoon'}]->(limeJuice)
CREATE (salsaVerde)-[:CONTAINS {quantity: '2'}]->(jalapeno)
CREATE (salsaVerde)-[:CONTAINS {quantity: 'Salt to taste'}]->(salt)
CREATE (yellowCurry)-[:CONTAINS { quantity: '3 tbsp' }]->(yellowCurryPaste)
CREATE (yellowCurry)-[:CONTAINS { quantity: '1 lb' }]->(chicken)
CREATE (yellowCurry)-[:CONTAINS { quantity: '2-3 small' }]->(potatoes)
CREATE (yellowCurry)-[:CONTAINS { quantity: '1/2 can (16oz)' }]->(coconutMilk)
CREATE (yellowCurry)-[:CONTAINS { quantity: '2 tbsp' }]->(friedShallots)
CREATE (yellowCurry)-[:CONTAINS { quantity: '1 tsp' }]->(fishSauce)
CREATE (yellowCurry)-[:CONTAINS { quantity: '12' }]->(driedChilis)
CREATE (yellowCurry)-[:CONTAINS { quantity: '2 tsp' }]->(seaSalt)
CREATE (yellowCurry)-[:CONTAINS { quantity: '2' }]->(shallots)
CREATE (yellowCurry)-[:CONTAINS { quantity: '4' }]->(garlic)
CREATE (yellowCurry)-[:CONTAINS { quantity: '1 slice' }]->(galangal)
CREATE (yellowCurry)-[:CONTAINS { quantity: '1 stalk' }]->(lemongrass)
CREATE (yellowCurry)-[:CONTAINS { quantity: '1 slice' }]->(ginger)
CREATE (yellowCurry)-[:CONTAINS { quantity: '1 tbsp' }]->(corianderSeeds)
CREATE (yellowCurry)-[:CONTAINS { quantity: '1 tsp' }]->(cuminSeeds)
CREATE (yellowCurry)-[:CONTAINS { quantity: '2 tsp' }]->(curryPowder)
CREATE (yellowCurry)-[:CONTAINS { quantity: '1 tsp' }]->(shrimpPaste)
CREATE (redCurry)-[:CONTAINS { quantity: '¾ ounce' }]->(mildDriedChilies)
CREATE (redCurry)-[:CONTAINS { quantity: '½ ounce' }]->(spicyDriedChilies)
CREATE (redCurry)-[:CONTAINS { quantity: '½ teaspoon' }]->(whitePeppercorns)
CREATE (redCurry)-[:CONTAINS { quantity: '1 stalk' }]->(lemongrass)
CREATE (redCurry)-[:CONTAINS { quantity: '2 tablespoons' }]->(galangal)
CREATE (redCurry)-[:CONTAINS { quantity: '4 cilantro roots' }]->(cilantroRoots)
CREATE (redCurry)-[:CONTAINS { quantity: '2 teaspoons' }]->(makrutLimeZest)
CREATE (redCurry)-[:CONTAINS { quantity: '6 cloves' }]->(garlic)
CREATE (redCurry)-[:CONTAINS { quantity: '½ cup' }]->(shallots)
CREATE (redCurry)-[:CONTAINS { quantity: '2 teaspoons' }]->(shrimpPaste)
CREATE (redCurry)-[:CONTAINS { quantity: '2 teaspoons' }]->(corianderSeeds)
CREATE (redCurry)-[:CONTAINS { quantity: '1 teaspoon' }]->(cuminSeeds)
CREATE (sobaNoodlesRecipe)-[:CONTAINS { quantity: '6 ounces' }]->(sobaNoodles)
CREATE (sobaNoodlesRecipe)-[:CONTAINS { quantity: '2 cups' }]->(edamame)
CREATE (sobaNoodlesRecipe)-[:CONTAINS { quantity: '10 ounces' }]->(sugarSnapPeas)
CREATE (sobaNoodlesRecipe)-[:CONTAINS { quantity: '6 medium-sized' }]->(carrots)
CREATE (sobaNoodlesRecipe)-[:CONTAINS { quantity: '1/2 cup' }]->(cilantro)
CREATE (sobaNoodlesRecipe)-[:CONTAINS { quantity: '1/4 cup' }]->(sesameSeeds)
CREATE (sobaNoodlesRecipe)-[:CONTAINS { quantity: '1/4 cup' }]->(tamari)
CREATE (sobaNoodlesRecipe)-[:CONTAINS { quantity: '2 tablespoons' }]->(peanutOil)
CREATE (sobaNoodlesRecipe)-[:CONTAINS { quantity: '1 small' }]->(lime)
CREATE (sobaNoodlesRecipe)-[:CONTAINS { quantity: '1 tablespoon' }]->(toastedSesameOil)
CREATE (sobaNoodlesRecipe)-[:CONTAINS { quantity: '1 tablespoon' }]->(honey)
CREATE (sobaNoodlesRecipe)-[:CONTAINS { quantity: '2 teaspoons' }]->(ginger)
CREATE (sobaNoodlesRecipe)-[:CONTAINS { quantity: '1 tablespoon' }]->(miso)
CREATE (sobaNoodlesRecipe)-[:CONTAINS { quantity: '1 teaspoon' }]->(chiliGarlicSauce)

// Create Product nodes for ingredients without quantities
CREATE (sobaNoodlesRecipe)-[:CONTAINS]->(miso)
CREATE (sobaNoodlesRecipe)-[:CONTAINS]->(sriracha)
CREATE (sobaNoodlesRecipe)-[:CONTAINS]->(bellPepper)
CREATE (sobaNoodlesRecipe)-[:CONTAINS { quantity: '2 handfuls' }]->(cilantro)
CREATE (sobaNoodlesRecipe)-[:CONTAINS { quantity: 'about 4 to 5 minutes' }]->(sesameSeeds)
CREATE (sobaNoodlesRecipe)-[:CONTAINS { quantity: 'emulsified' }]->(tamari)
CREATE (sobaNoodlesRecipe)-[:CONTAINS { quantity: 'juiced' }]->(lime)
CREATE (sobaNoodlesRecipe)-[:CONTAINS { quantity: 'to make popping noises' }]->(sesameSeeds)
CREATE (sobaNoodlesRecipe)-[:CONTAINS { quantity: 'al dente' }]->(sobaNoodles)
CREATE (sobaNoodlesRecipe)-[:CONTAINS { quantity: 'about 4 to 6 minutes' }]->(edamame)
CREATE (sobaNoodlesRecipe)-[:CONTAINS { quantity: 'about 20 seconds' }]->(sugarSnapPeas)
CREATE (sobaNoodlesRecipe)-[:CONTAINS { quantity: 'decently well' }]->(sobaNoodles)
CREATE (sobaNoodlesRecipe)-[:CONTAINS { quantity: 'a couple of days' }]->(sobaNoodles)
CREATE (sobaNoodlesRecipe)-[:CONTAINS { quantity: 'a dash' }]->(tamari)
CREATE (sobaNoodlesRecipe)-[:CONTAINS { quantity: 'additional' }]->(tamari)
CREATE (sobaNoodlesRecipe)-[:CONTAINS { quantity: 'a nice addition this summer' }]->(bellPepper)
CREATE (padThai)-[:CONTAINS { quantity: '4 tablespoons' }]->(thaiFishSauce)
CREATE (padThai)-[:CONTAINS { quantity: '4 tablespoons' }]->(sugar)
CREATE (padThai)-[:CONTAINS { quantity: '3 tablespoons' }]->(tamarindPaste)
CREATE (padThai)-[:CONTAINS { quantity: '1 tablespoon' }]->(limeJuice)
CREATE (padThai)-[:CONTAINS { quantity: '1 tablespoon' }]->(riceWineVinegar)
CREATE (padThai)-[:CONTAINS { quantity: '1 tablespoon' }]->(sweetPaprika)
CREATE (padThai)-[:CONTAINS { quantity: '2 teaspoons' }]->(chiliSauce)
CREATE (padThai)-[:CONTAINS { quantity: '3 to 4 cups' }]->(riceSticks)
CREATE (padThai)-[:CONTAINS { quantity: '' }]->(bananaLeaf)
CREATE (padThai)-[:CONTAINS { quantity: '2 tablespoons' }]->(vegetableOil)
CREATE (padThai)-[:CONTAINS { quantity: '' }]->(garlic)
CREATE (padThai)-[:CONTAINS { quantity: '1/2 cup' }]->(tofu)
CREATE (padThai)-[:CONTAINS { quantity: '1 teaspoon' }]->(driedShrimp)
CREATE (padThai)-[:CONTAINS { quantity: '1/2 cup' }]->(chicken)
CREATE (padThai)-[:CONTAINS { quantity: '2' }]->(eggs)
CREATE (padThai)-[:CONTAINS { quantity: '4 teaspoons' }]->(saltedTurnip)
CREATE (padThai)-[:CONTAINS { quantity: '8' }]->(shrimp)
CREATE (padThai)-[:CONTAINS { quantity: '1 cup' }]->(beanSprouts)
CREATE (padThai)-[:CONTAINS { quantity: '1/4 cup' }]->(peanuts)
CREATE (padThai)-[:CONTAINS { quantity: '' }]->(garlicChives)
CREATE (padThai)-[:CONTAINS { quantity: '' }]->(lime)

CREATE (coldSobaWithPerillaOilDressing)-[:CONTAINS]->(buckwheatSoba)
CREATE (coldSobaWithPerillaOilDressing)-[:CONTAINS]->(japaneseNori)
CREATE (coldSobaWithPerillaOilDressing)-[:CONTAINS]->(perillaOil)

CREATE (koreanSesameNoodles)-[:CONTAINS {quantity: '1 portion'}]->(sobaNoodles)
CREATE (koreanSesameNoodles)-[:CONTAINS {quantity: '1 1/2 tbsp'}]->(tsuyu)
CREATE (koreanSesameNoodles)-[:CONTAINS {quantity: '1 tbsp'}]->(sesameOil)
CREATE (koreanSesameNoodles)-[:CONTAINS {quantity: '1 green onion or chive, chopped'}]->(greenOnion)
CREATE (koreanSesameNoodles)-[:CONTAINS {quantity: '1 tsp'}]->(sesameSeedsToasted)
CREATE (koreanSesameNoodles)-[:CONTAINS {quantity: '1 sheet (optional)'}]->(seaweed)
CREATE (koreanSesameNoodles)-[:CONTAINS {quantity: '1 tbsp'}]->(chiliOil)
CREATE (koreanSesameNoodles)-[:CONTAINS {quantity: '1 green onion or chive, chopped'}]->(greenOnion)
CREATE (koreanSesameNoodles)-[:CONTAINS {quantity: '1 tsp'}]->(sesameSeeds)
CREATE (koreanSesameNoodles)-[:CONTAINS {quantity: 'a few slices (optional)'}]->(redChili)

CREATE (chickenThaiRedCurry)-[:CONTAINS { quantity: '500 grams' }]->(bonelessChickenThighs)
CREATE (chickenThaiRedCurry)-[:CONTAINS { quantity: '2 tablespoons' }]->(oil)
CREATE (chickenThaiRedCurry)-[:CONTAINS { quantity: '4 tablespoons' }]->(redCurryPaste)
CREATE (chickenThaiRedCurry)-[:CONTAINS { quantity: '½ Onion sliced' }]->(onion)
CREATE (chickenThaiRedCurry)-[:CONTAINS { quantity: '½ tablespoon Garlic minced' }]->(garlic)
CREATE (chickenThaiRedCurry)-[:CONTAINS { quantity: '1 teaspoon Ginger minced' }]->(ginger)
CREATE (chickenThaiRedCurry)-[:CONTAINS { quantity: '1 stalk' }]->(lemonGrass)
CREATE (chickenThaiRedCurry)-[:CONTAINS { quantity: '2 teaspoon' }]->(fishSauce)
CREATE (chickenThaiRedCurry)-[:CONTAINS { quantity: '½ tablespoon' }]->(lightBrownSugar)
CREATE (chickenThaiRedCurry)-[:CONTAINS { quantity: '1 Red Bell Pepper' }]->(redBellPepper)
CREATE (chickenThaiRedCurry)-[:CONTAINS { quantity: '1 cup' }]->(zucchini)
CREATE (chickenThaiRedCurry)-[:CONTAINS { quantity: '1.5 cup' }]->(coconutMilk)
CREATE (chickenThaiRedCurry)-[:CONTAINS { quantity: '½ cup' }]->(stockWater)
CREATE (chickenThaiRedCurry)-[:CONTAINS { quantity: '2 teaspoon' }]->(lemonJuice)
CREATE (chickenThaiRedCurry)-[:CONTAINS { quantity: '8-10 leaves' }]->(thaiBasil)
CREATE (yellowCoconutCurry)-[:CONTAINS { quantity: '1 tbsp.' }]->(coconutOil)
CREATE (yellowCoconutCurry)-[:CONTAINS { quantity: '1/2' }]->(yellowOnion)
CREATE (yellowCoconutCurry)-[:CONTAINS { quantity: '2 cloves' }]->(garlic)
CREATE (yellowCoconutCurry)-[:CONTAINS { quantity: '1 lb.' }]->(chickenBreast)
CREATE (yellowCoconutCurry)-[:CONTAINS { quantity: '3' }]->(carrots)
CREATE (yellowCoconutCurry)-[:CONTAINS { quantity: '2' }]->(russetPotatoes)
CREATE (yellowCoconutCurry)-[:CONTAINS { quantity: '3 tbsp.' }]->(yellowCurryPowder)
CREATE (yellowCoconutCurry)-[:CONTAINS { quantity: '1 1/2 tbsp.' }]->(maesriThaiRedCurryPaste)
CREATE (yellowCoconutCurry)-[:CONTAINS { quantity: '1 14 oz. can' }]->(coconutMilk)
CREATE (yellowCoconutCurry)-[:CONTAINS { quantity: '3 c.' }]->(chickenBroth)
CREATE (yellowCoconutCurry)-[:CONTAINS { quantity: '2 tbsp.' }]->(brownSugar)
CREATE (yellowCoconutCurry)-[:CONTAINS { quantity: '1 tsp.' }]->(fishSauce)
CREATE (yellowCoconutCurry)-[:CONTAINS { quantity: 'if desired' }]->(cilantro)
CREATE (yellowCoconutCurry)-[:CONTAINS { quantity: 'with rice' }]->(rice)
CREATE (thaiCurry1)-[:CONTAINS]->(cilantro)
CREATE (thaiCurry1)-[:CONTAINS]->(clovesGarlic)
CREATE (thaiCurry1)-[:CONTAINS]->(chickenStock)
CREATE (thaiCurry1)-[:CONTAINS]->(chickenThigh)
CREATE (thaiCurry1)-[:CONTAINS]->(coconutMilk)
CREATE (thaiCurry1)-[:CONTAINS]->(corianderSeeds)
CREATE (thaiCurry1)-[:CONTAINS]->(fishSauce)
CREATE (thaiCurry1)-[:CONTAINS]->(friedShallots)
CREATE (thaiCurry1)-[:CONTAINS]->(galangal)
CREATE (thaiCurry1)-[:CONTAINS]->(kaffirLime)
CREATE (thaiCurry1)-[:CONTAINS]->(cuminSeeds)
CREATE (thaiCurry1)-[:CONTAINS]->(kaffirLimeLeaves)
CREATE (thaiCurry1)-[:CONTAINS]->(lemongrass)
CREATE (thaiCurry1)-[:CONTAINS]->(lime)
CREATE (thaiCurry1)-[:CONTAINS]->(palmSugar)
CREATE (thaiCurry1)-[:CONTAINS]->(serranos)
CREATE (thaiCurry1)-[:CONTAINS]->(shallots)
CREATE (thaiCurry1)-[:CONTAINS]->(snowPeas)
CREATE (thaiCurry1)-[:CONTAINS]->(thaiBasil)
CREATE (thaiCurry1)-[:CONTAINS]->(thaiEggplant)
CREATE (thaiCurry1)-[:CONTAINS]->(thaiShrimpPaste)
CREATE (thaiCurry1)-[:CONTAINS]->(whitePeppercorns)

CREATE (thaiEggplantRecipe)-[:CONTAINS]->(coconutMilk)
CREATE (thaiEggplantRecipe)-[:CONTAINS]->(thaiChilies)
CREATE (thaiEggplantRecipe)-[:CONTAINS]->(chiliPowder)
CREATE (thaiEggplantRecipe)-[:CONTAINS]->(corianderPowder)
CREATE (thaiEggplantRecipe)-[:CONTAINS]->(clovesGarlic)
CREATE (thaiEggplantRecipe)-[:CONTAINS]->(ginger)
CREATE (thaiEggplantRecipe)-[:CONTAINS]->(lemonGrassStalk)
CREATE (thaiEggplantRecipe)-[:CONTAINS]->(chickenStock)
CREATE (thaiEggplantRecipe)-[:CONTAINS]->(limeJuice)
CREATE (thaiEggplantRecipe)-[:CONTAINS]->(oliveOrCoconutOil)
CREATE (thaiEggplantRecipe)-[:CONTAINS]->(onion)
CREATE (thaiEggplantRecipe)-[:CONTAINS]->(redBellPepper)
CREATE (thaiEggplantRecipe)-[:CONTAINS]->(salt)
CREATE (thaiEggplantRecipe)-[:CONTAINS]->(thaiBasil)
CREATE (thaiEggplantRecipe)-[:CONTAINS]->(thaiEggplant)
CREATE (thaiEggplantRecipe)-[:CONTAINS]->(turmeric)

CREATE (yellowThaiCurry)-[:CONTAINS]->(kaffirLime)

CREATE (maesriThaiRedCurryPaste)-[:PURCHASE_AT]->(wholeFoods)
CREATE (a1Sauce)-[:PURCHASE_AT]->(dummy)
CREATE (allspice)-[:PURCHASE_AT]->(centralCoop)
CREATE (almondMilksPlease)-[:PURCHASE_AT]->(traderJoes)
CREATE (almondsBulkRoastedOrRawWhicheverIsCheaper)-[:PURCHASE_AT]->(traderJoes)
CREATE (angkorCambodianFoodPasteLemongrass)-[:PURCHASE_AT]->(qfc)
CREATE (apples)-[:PURCHASE_AT]->(safeway)
CREATE (artichokeHearts)-[:PURCHASE_AT]->(safeway)
CREATE (asparagus)-[:PURCHASE_AT]->(dummy)
CREATE (asparagus)-[:PURCHASE_AT]->(traderJoes)
CREATE (avocadosNotInBagStupid)-[:PURCHASE_AT]->(traderJoes)
CREATE (bacon)-[:PURCHASE_AT]->(safeway)
CREATE (bakedTofu)-[:PURCHASE_AT]->(thanhSonTofu)
CREATE (bakersDozen)-[:PURCHASE_AT]->(einsteinBrotheresBagels)
CREATE (bakingCupsInCakeMixflourAisle)-[:PURCHASE_AT]->(safeway)
CREATE (bakingSoda)-[:PURCHASE_AT]->(safeway)
CREATE (ballPowderSmellsNice)-[:PURCHASE_AT]->(safeway)
CREATE (bambooShoots)-[:PURCHASE_AT]->(safeway)
CREATE (bananasOrganic)-[:PURCHASE_AT]->(traderJoes)
CREATE (barbecueSauceBabyRaysBbqSauce)-[:PURCHASE_AT]->(safeway)
CREATE (barley)-[:PURCHASE_AT]->(centralCoop)
CREATE (basilDry)-[:PURCHASE_AT]->(centralCoop)
CREATE (basilFresh)-[:PURCHASE_AT]->(hauHauMarket)
CREATE (bayLeaf)-[:PURCHASE_AT]->(dummy)
CREATE (beanCannelloniWhite)-[:PURCHASE_AT]->(centralCoop)
CREATE (beanGreatNorthernWhite)-[:PURCHASE_AT]->(centralCoop)
CREATE (beanNavyBean)-[:PURCHASE_AT]->(dummy)
CREATE (beansBlack15OzCan)-[:PURCHASE_AT]->(safeway)
CREATE (beansBlackBulk)-[:PURCHASE_AT]->(centralCoop)
CREATE (beansGreen)-[:PURCHASE_AT]->(safeway)
CREATE (beansKidneyBulk)-[:PURCHASE_AT]->(centralCoop)
CREATE (beefChuck)-[:PURCHASE_AT]->(safeway)
CREATE (beefChuckShoulderClod)-[:PURCHASE_AT]->(wholeFoods)
CREATE (beerLagger)-[:PURCHASE_AT]->(safeway)
CREATE (beerSessionLager)-[:PURCHASE_AT]->(traderJoes)
CREATE (beets)-[:PURCHASE_AT]->(safeway)
CREATE (beetsCanned)-[:PURCHASE_AT]->(safeway)
CREATE (blueberriesFrozenUponinaBag)-[:PURCHASE_AT]->(groceryOutletBargainMarketBargainMarket)
CREATE (bokChoy)-[:PURCHASE_AT]->(safeway)
CREATE (bonitoFlakes)-[:PURCHASE_AT]->(m2mMart)
CREATE (boullionBeef)-[:PURCHASE_AT]->(dummy)
CREATE (boullionVegetableBrothPowdered)-[:PURCHASE_AT]->(centralCoop)
CREATE (breadDavesYumsSeedBread)-[:PURCHASE_AT]->(dummy)
CREATE (breadFrench)-[:PURCHASE_AT]->(qfc)
CREATE (breadOlive)-[:PURCHASE_AT]->(centralCoop)
CREATE (breadPurpleNutsAndGrain)-[:PURCHASE_AT]->(safeway)
CREATE (breadSoda)-[:PURCHASE_AT]->(macrinaBakery)
CREATE (brewersYeast)-[:PURCHASE_AT]->(centralCoop)
CREATE (broccoli)-[:PURCHASE_AT]->(safeway)
CREATE (broccoli6oz)-[:PURCHASE_AT]->(safeway)
CREATE (broccolini)-[:PURCHASE_AT]->(safeway)
CREATE (brothBeefLowSodium)-[:PURCHASE_AT]->(safeway)
CREATE (brownieClifBar)-[:PURCHASE_AT]->(traderJoes)
CREATE (brownieMixBettyCrocker)-[:PURCHASE_AT]->(dummy)
CREATE (brownieMixDuncanHines)-[:PURCHASE_AT]->(dummy)
CREATE (brownieMixGhirardelli)-[:PURCHASE_AT]->(dummy)
CREATE (brownieMixPillsbury)-[:PURCHASE_AT]->(dummy)
CREATE (bulgurWheat)-[:PURCHASE_AT]->(centralCoop)
CREATE (butterUnsalted)-[:PURCHASE_AT]->(traderJoes)
CREATE (cabbageGreenSmall)-[:PURCHASE_AT]->(pcc)
CREATE (cabbageRedSmall)-[:PURCHASE_AT]->(pcc)
CREATE (calamari)-[:PURCHASE_AT]->(wholeFoods)
CREATE (carrots)-[:PURCHASE_AT]->(safeway)
CREATE (cauliflower)-[:PURCHASE_AT]->(safeway)
CREATE (cayennePepper)-[:PURCHASE_AT]->(centralCoop)
CREATE (celery)-[:PURCHASE_AT]->(safeway)
CREATE (chardonnayTerresDorees)-[:PURCHASE_AT]->(qfc)
CREATE (cheddarSharp)-[:PURCHASE_AT]->(traderJoes)
CREATE (cheeseBlue)-[:PURCHASE_AT]->(traderJoes)
CREATE (cheeseExtraSharpCheddar)-[:PURCHASE_AT]->(dummy)
CREATE (cheeseGruyere)-[:PURCHASE_AT]->(traderJoes)
CREATE (cheesePecorino)-[:PURCHASE_AT]->(traderJoes)
CREATE (cheeseSharpSwiss)-[:PURCHASE_AT]->(dummy)
CREATE (cheeseShreddedMozzarella8Oz)-[:PURCHASE_AT]->(qfc)
CREATE (chicken34Lb)-[:PURCHASE_AT]->(centralCoop)
CREATE (chickenBreast)-[:PURCHASE_AT]->(qfc)
CREATE (chickenBroth16Oz)-[:PURCHASE_AT]->(safeway)
CREATE (chickenBroth32Oz)-[:PURCHASE_AT]->(safeway)
CREATE (chickenBrothSwanson145Oz)-[:PURCHASE_AT]->(safeway)
CREATE (chickenElectricRotisserie)-[:PURCHASE_AT]->(wholeFoods)
CREATE (chickenStock)-[:PURCHASE_AT]->(safeway)
CREATE (chickenTenderloinsRubberDuckies1BagOnly)-[:PURCHASE_AT]->(traderJoes)
CREATE (chickenThigh)-[:PURCHASE_AT]->(madisonCoop)
CREATE (chilesChipotleInAdobo)-[:PURCHASE_AT]->(dummy)
CREATE (chiliPepperAnchoGround)-[:PURCHASE_AT]->(pcc)
CREATE (chiliPepperChipotleGround)-[:PURCHASE_AT]->(pcc)
CREATE (chiliPowder)-[:PURCHASE_AT]->(centralCoop)
CREATE (chiliPowder)-[:PURCHASE_AT]->(madisonCoop)
CREATE (chiliThai)-[:PURCHASE_AT]->(safeway)
CREATE (chineseBroccoli)-[:PURCHASE_AT]->(hauHauMarket)
CREATE (chips)-[:PURCHASE_AT]->(traderJoes)
CREATE (chocolateCoveredCherriesForJoyce)-[:PURCHASE_AT]->(traderJoes)
CREATE (choppedCalabrianPeppers)-[:PURCHASE_AT]->(wholeFoods)
CREATE (cilantro)-[:PURCHASE_AT]->(safeway)
CREATE (cinamon)-[:PURCHASE_AT]->(centralCoop)
CREATE (cinnamon)-[:PURCHASE_AT]->(centralCoop)
CREATE (clamChowder)-[:PURCHASE_AT]->(dummy)
CREATE (clamJuice)-[:PURCHASE_AT]->(wholeFoods)
CREATE (clams)-[:PURCHASE_AT]->(dummy)
CREATE (cleanserBonAmi)-[:PURCHASE_AT]->(bartell)
CREATE (clovesGarlic)-[:PURCHASE_AT]->(traderJoes)
CREATE (cocoaPowderUnsweetenedHersheysNatural8Oz)-[:PURCHASE_AT]->(safeway)
CREATE (coconutFlakes)-[:PURCHASE_AT]->(centralCoop)
CREATE (coconutMilk135OzCan)-[:PURCHASE_AT]->(safeway)
CREATE (coffeeBbPlu8875LessYumsThan8863)-[:PURCHASE_AT]->(centralCoop)
CREATE (coffeeBbs1stPreferenceBbPlu8863EqualExchangePeruvian)-[:PURCHASE_AT]->(centralCoop)
CREATE (coffeeBbs2ndPreferenceBbPlu3794KalaniCoffeeIndonesianEnyanaSumatra)-[:PURCHASE_AT]->(pcc)
CREATE (coffeeMtmKivuDarkEspressoRoast)-[:PURCHASE_AT]->(qfc)
CREATE (coffeeMtmPlu1859FidalgoBayOrganicFairTradeFrenchRoastExtraDark)-[:PURCHASE_AT]->(pcc)
CREATE (coffeeMtmPlu5820KivuKivuDarkFrenchRoast)-[:PURCHASE_AT]->(fredMeyer)
CREATE (coffeeMtmPlu8368DecafDecafDecafKindUnknown)-[:PURCHASE_AT]->(centralCoop)
CREATE (coffeeTDecaf)-[:PURCHASE_AT]->(safeway)
CREATE (coffeeTPlu8852TLikesItBbSaysYux)-[:PURCHASE_AT]->(centralCoop)
CREATE (coffeeTPlu8853)-[:PURCHASE_AT]->(centralCoop)
CREATE (coffeeTaylorPlu8868)-[:PURCHASE_AT]->(centralCoop)
CREATE (cokeZero)-[:PURCHASE_AT]->(safeway)
CREATE (collardGreens)-[:PURCHASE_AT]->(qfc)
CREATE (coolMintChocolateClifBar)-[:PURCHASE_AT]->(traderJoes)
CREATE (coriander)-[:PURCHASE_AT]->(centralCoop)
CREATE (corianderPowder)-[:PURCHASE_AT]->(madisonCoop)
CREATE (corianderSeeds)-[:PURCHASE_AT]->(madisonCoop)
CREATE (cornFrozen)-[:PURCHASE_AT]->(safeway)
CREATE (cornOnCob)-[:PURCHASE_AT]->(safewqy)
CREATE (cornStarch)-[:PURCHASE_AT]->(dummy)
CREATE (cornmeal)-[:PURCHASE_AT]->(safeway)
CREATE (cornstarchBabyPowderNotJohnsonsTheyreBaddies)-[:PURCHASE_AT]->(qfc)
CREATE (cottageCheeseLargeCurd)-[:PURCHASE_AT]->(safeway)
CREATE (couscous)-[:PURCHASE_AT]->(centralCoop)
CREATE (couscousIsraeli)-[:PURCHASE_AT]->(centralCoop)
CREATE (cranberriesDried)-[:PURCHASE_AT]->(centralCoop)
CREATE (creamHeavy)-[:PURCHASE_AT]->(safeway)
CREATE (crest)-[:PURCHASE_AT]->(bartell)
CREATE (cucumber)-[:PURCHASE_AT]->(safeway)
CREATE (cucumbersEnglish)-[:PURCHASE_AT]->(safeway)
CREATE (cucumbersPersian)-[:PURCHASE_AT]->(traderJoes)
CREATE (cuminGround)-[:PURCHASE_AT]->(centralCoop)
CREATE (cuminSeedNotGrounddog)-[:PURCHASE_AT]->(centralCoop)
CREATE (cuminSeeds)-[:PURCHASE_AT]->(madisonCoop)
CREATE (curryPowder)-[:PURCHASE_AT]->(centralCoop)
CREATE (dates)-[:PURCHASE_AT]->(traderJoes)
CREATE (dill)-[:PURCHASE_AT]->(centralCoop)
CREATE (dillPickles)-[:PURCHASE_AT]->(safeway)
CREATE (dinoKaleUglySpinach)-[:PURCHASE_AT]->(dummy)
CREATE (driedShrimp)-[:PURCHASE_AT]->(safeway)
CREATE (driedThaiShrimpPaste)-[:PURCHASE_AT]->(uwajimaya)
CREATE (dukesMayonnaise)-[:PURCHASE_AT]->(dummy)
CREATE (edamameShelled)-[:PURCHASE_AT]->(safeway)
CREATE (eggplant)-[:PURCHASE_AT]->(safeway)
CREATE (eggplantChinese)-[:PURCHASE_AT]->(uwajimaya)
CREATE (eggplantThai)-[:PURCHASE_AT]->(uwajimaya)
CREATE (eggsDozen)-[:PURCHASE_AT]->(traderJoes)
CREATE (eggsLiquidEggWhitesBlueChikn)-[:PURCHASE_AT]->(safeway)
CREATE (enchiladaSauceRed)-[:PURCHASE_AT]->(dummy)
CREATE (endiveOrEscaroleLettce)-[:PURCHASE_AT]->(safeway)
CREATE (englishMuffins)-[:PURCHASE_AT]->(franzBakery)
CREATE (farro)-[:PURCHASE_AT]->(pcc)
CREATE (fetaYums)-[:PURCHASE_AT]->(traderJoes)
CREATE (filtersCoffeeSize2)-[:PURCHASE_AT]->(qfc)
CREATE (fishSauceRedBoatPremium)-[:PURCHASE_AT]->(safeway)
CREATE (fishTilapia)-[:PURCHASE_AT]->(safeway)
CREATE (flourWhiteAllpurposeUnbleachedIfPossibleButNoBigs)-[:PURCHASE_AT]->(safeway)
CREATE (flourWholeWheatAllpurpose)-[:PURCHASE_AT]->(safeway)
CREATE (franciscoInternationalFrenchSandwichRolls6Count)-[:PURCHASE_AT]->(safeway)
CREATE (frozenMangos)-[:PURCHASE_AT]->(groceryOutletBargainMarketBargainMarket)
CREATE (frozenPeas)-[:PURCHASE_AT]->(safeway)
CREATE (galangal)-[:PURCHASE_AT]->(uwajimaya)
CREATE (galangal)-[:PURCHASE_AT]->(uwajimaya)
CREATE (garamMasala)-[:PURCHASE_AT]->(centralCoop)
CREATE (garbanzoBeansDry)-[:PURCHASE_AT]->(centralCoop)
CREATE (garlic)-[:PURCHASE_AT]->(traderJoes)
CREATE (garlicChivesAlternativeChives)-[:PURCHASE_AT]->(hauHauMarket)
CREATE (garlic)-[:PURCHASE_AT]->(traderJoes)
CREATE (garlicPowder)-[:PURCHASE_AT]->(centralCoop)
CREATE (ginger)-[:PURCHASE_AT]->(safeway)
CREATE (gingerPowder)-[:PURCHASE_AT]->(centralCoop)
CREATE (gingerRoot)-[:PURCHASE_AT]->(traderJoes)
CREATE (gochugaru)-[:PURCHASE_AT]->(amazon)
CREATE (grainsOfParadiseSpice)-[:PURCHASE_AT]->(centralCoop)
CREATE (granolaCookies)-[:PURCHASE_AT]->(centralCoop)
CREATE (grapesGrapeShaped)-[:PURCHASE_AT]->(safeway)
CREATE (gritsQuick)-[:PURCHASE_AT]->(safeway)
CREATE (groundBeef)-[:PURCHASE_AT]->(safeway)
CREATE (habanero)-[:PURCHASE_AT]->(safeway)
CREATE (halfgallonHalfHalf)-[:PURCHASE_AT]->(safeway)
CREATE (hamSliced)-[:PURCHASE_AT]->(safeway)
CREATE (heavyCream)-[:PURCHASE_AT]->(safeway)
CREATE (herbsOrSuperGreensLettuce)-[:PURCHASE_AT]->(centralCoop)
CREATE (herbsOrSuperGreensLettucesBucket)-[:PURCHASE_AT]->(safeway)
CREATE (honeyInGlassJar)-[:PURCHASE_AT]->(traderJoes)
CREATE (iceCreamChocolateSignatureBrand)-[:PURCHASE_AT]->(safeway)
CREATE (iceCreamCones)-[:PURCHASE_AT]->(safeway)
CREATE (iceCreamDoublefudgeBrownieDreyersSlowchurned)-[:PURCHASE_AT]->(safeway)
CREATE (italianSeasoning)-[:PURCHASE_AT]->(centralCoop)
CREATE (johnsonsCreamyBabyOil)-[:PURCHASE_AT]->(dummy)
CREATE (kaffirLimeLeaves)-[:PURCHASE_AT]->(uwajimaya)
CREATE (kale)-[:PURCHASE_AT]->(pcc)
CREATE (katchup)-[:PURCHASE_AT]->(safeway)
CREATE (kidneyBeansRedOrganic15Oz)-[:PURCHASE_AT]->(pcc)
CREATE (kidneyBeansSw)-[:PURCHASE_AT]->(dummy)
CREATE (kombucha)-[:PURCHASE_AT]->(centralCoop)
CREATE (kombucha)-[:PURCHASE_AT]->(groceryOutletBargainMarket)
CREATE (leeKumKeeSoySaucePremiumDarkBottle)-[:PURCHASE_AT {url: "https://www.safeway.com/shop/product-details.960097003.html"}]->(saveway)
CREATE (lemon)-[:PURCHASE_AT]->(traderJoes)
CREATE (lemonJuice)-[:PURCHASE_AT]->(wholeFoods)
CREATE (lemonZestGratedLemonRind)-[:PURCHASE_AT]->(traderJoes)
CREATE (lemongrass)-[:PURCHASE_AT]->(safeway)
CREATE (lemongrassStalk)-[:PURCHASE_AT]->(safeway)
CREATE (lentilsBlackBeluga)-[:PURCHASE_AT]->(pcc)
CREATE (lentilsBrown)-[:PURCHASE_AT]->(pcc)
CREATE (lentilsGreen)-[:PURCHASE_AT]->(centralCoop)
CREATE (lettucesRomaine)-[:PURCHASE_AT]->(safeway)
CREATE (lime)-[:PURCHASE_AT]->(traderJoes)
CREATE (lime)-[:PURCHASE_AT]->(traderJoes)
CREATE (limeJuice)-[:PURCHASE_AT]->(wholeFoods)
CREATE (limeLeavesKaffir)-[:PURCHASE_AT]->(uwajimaya)
CREATE (limes)-[:PURCHASE_AT]->(traderJoes)
CREATE (lobsterCornChowder)-[:PURCHASE_AT]->(wholeFoods)
CREATE (maltomeal)-[:PURCHASE_AT]->(safeway)
CREATE (marjoramLeaves)-[:PURCHASE_AT]->(centralCoop)
CREATE (marketspiceTeaDecaf2OzForMommy)-[:PURCHASE_AT]->(bartell)
CREATE (martianmallowsLargeButNotGigantic)-[:PURCHASE_AT]->(safeway)
CREATE (meatSliced)-[:PURCHASE_AT]->(qfc)
CREATE (merlot)-[:PURCHASE_AT]->(traderJoes)
CREATE (mintOrMintExtract)-[:PURCHASE_AT]->(nakedGrocer)
CREATE (misoPaste)-[:PURCHASE_AT]->(qfc)
CREATE (misoSweetWhite)-[:PURCHASE_AT]->(wholeFoods)
CREATE (molasses)-[:PURCHASE_AT]->(wholeFoods)
CREATE (mouthwashActRestoring)-[:PURCHASE_AT]->(bartell)
CREATE (mushroomsCrimini)-[:PURCHASE_AT]->(safeway)
CREATE (mushroomsPortobello)-[:PURCHASE_AT]->(qfc)
CREATE (mustardGermanMediumHotInJarWHandle)-[:PURCHASE_AT]->(groceryOutletBargainMarket)
CREATE (mustardSpicyBrownInGlassJarPlease)-[:PURCHASE_AT]->(groceryOutletBargainMarketBargainMarket)
CREATE (myntzes)-[:PURCHASE_AT]->(traderJoes)
CREATE (noodlesLasagna)-[:PURCHASE_AT]->(safeway)
CREATE (nutmeg)-[:PURCHASE_AT]->(centralCoop)
CREATE (oOrganicsOrganicCoconutOilVirginUnrefined)-[:PURCHASE_AT]->(safeway)
CREATE (oilAvocado)-[:PURCHASE_AT]->(wholeFoods)
CREATE (oilOliveExtraVirgin)-[:PURCHASE_AT]->(groceryOutletBargainMarket)
CREATE (olivesCastelvetrano)-[:PURCHASE_AT]->(dummy)
CREATE (olivesKalamataPitted)-[:PURCHASE_AT]->(groceryOutletBargainMarket)
CREATE (onePercentMilkYellowCarton)-[:PURCHASE_AT]->(safeway)
CREATE (onePercentOr2PercentMilkInGlassJarNotRedCapWholeMilk)-[:PURCHASE_AT]->(centralCoop)
CREATE (onion)-[:PURCHASE_AT]->(traderJoes)
CREATE (onionPowder)-[:PURCHASE_AT]->(centralCoop)
CREATE (onionRed)-[:PURCHASE_AT]->(traderJoes)
CREATE (onionSweet)-[:PURCHASE_AT]->(traderJoes)
CREATE (onionWhite1)-[:PURCHASE_AT]->(safeway)
CREATE (onions)-[:PURCHASE_AT]->(traderJoes)
CREATE (orangeJuice)-[:PURCHASE_AT]->(qfc)
CREATE (oranges)-[:PURCHASE_AT]->(dummy)
CREATE (oranges)-[:PURCHASE_AT]->(safeway)
CREATE (oregano)-[:PURCHASE_AT]->(centralCoop)
CREATE (organicSaladFreshHerbBlend)-[:PURCHASE_AT]->(safeway)
CREATE (oysterMushrooms)-[:PURCHASE_AT]->(safeway)
CREATE (oysterSauce)-[:PURCHASE_AT]->(wholeFoods)
CREATE (padThaiSauce)-[:PURCHASE_AT]->(wholeFoods)
CREATE (pancakeMixSnoqualmieFallsLodge)-[:PURCHASE_AT]->(dummy)
CREATE (paprika)-[:PURCHASE_AT]->(nakedGrocer)
CREATE (paprikaSmoked)-[:PURCHASE_AT]->(centralCoop)
CREATE (parmesanCheese)-[:PURCHASE_AT]->(traderJoes)
CREATE (parsley)-[:PURCHASE_AT]->(safeway)
CREATE (pastaFettuccine)-[:PURCHASE_AT]->(groceryOutlet)
CREATE (pastaLinguine)-[:PURCHASE_AT]->(wholeFoods)
CREATE (pastaRigatoni)-[:PURCHASE_AT]->(traderJoes)
CREATE (pastaTrottole)-[:PURCHASE_AT]->(qfc)
CREATE (peanutButterAdamsUnsalted)-[:PURCHASE_AT]->(safeway)
CREATE (peanutButterBulk)-[:PURCHASE_AT]->(qfc)
CREATE (pearsAnjou)-[:PURCHASE_AT]->(safeway)
CREATE (pearsBartlett)-[:PURCHASE_AT]->(safeway)
CREATE (pearsBosc)-[:PURCHASE_AT]->(safeway)
CREATE (pepperBlackBulk)-[:PURCHASE_AT]->(centralCoop)
CREATE (pepperChipotle)-[:PURCHASE_AT]->(wholeFoods)
CREATE (pepperFlakesSpiceyRedPepperFlakes)-[:PURCHASE_AT]->(centralCoop)
CREATE (pepperJalapeno)-[:PURCHASE_AT]->(safeway)
CREATE (pepperSerrano)-[:PURCHASE_AT]->(safeway)
CREATE (peppercornsWholeBlack)-[:PURCHASE_AT]->(nakedGrocer)
CREATE (periPeriSauceGarlic)-[:PURCHASE_AT]->(wholeFoods)
CREATE (perillaOil)-[:PURCHASE_AT]->(m2mMart)
CREATE (perillaOil)-[:PURCHASE_AT]->(m2mMartKoreanGrocer)
CREATE (pineNuts)-[:PURCHASE_AT]->(pcc)
CREATE (pinotGrigioDryWhiteWine)-[:PURCHASE_AT]->(qfc)
CREATE (pistachios)-[:PURCHASE_AT]->(centralCoop)
CREATE (plums)-[:PURCHASE_AT]->(safeway)
CREATE (polenta)-[:PURCHASE_AT]->(safeway)
CREATE (popcorn)-[:PURCHASE_AT]->(centralCoop)
CREATE (pork)-[:PURCHASE_AT]->(safeway)
CREATE (potatoesBabyTriColor)-[:PURCHASE_AT]->(safeway)
CREATE (potatoesRusset2)-[:PURCHASE_AT]->(safeway)
CREATE (primoTaglioCheeseGoat4Oz)-[:PURCHASE_AT]->(traderJoes)
CREATE (prunes)-[:PURCHASE_AT]->(traderJoes)
CREATE (pumpkinSeedsSalted)-[:PURCHASE_AT]->(centralCoop)
CREATE (quickRolledOatsOatsPlu8485)-[:PURCHASE_AT]->(centralCoop)
CREATE (quinoaRed)-[:PURCHASE_AT]->(centralCoop)
CREATE (quinoaWhite)-[:PURCHASE_AT]->(nakedGrocer)
CREATE (radish)-[:PURCHASE_AT]->(safeway)
CREATE (raisinsBulkBabyBulk)-[:PURCHASE_AT]->(centralCoop)
CREATE (ramenNoodlesDry)-[:PURCHASE_AT]->(safeway)
CREATE (redBellPepper)-[:PURCHASE_AT]->(traderJoes)
CREATE (redChilliPeppers)-[:PURCHASE_AT]->(safeway)
CREATE (redGreenYellaPeppers)-[:PURCHASE_AT]->(traderJoes)
CREATE (redLentils)-[:PURCHASE_AT]->(madisonCoop)
CREATE (refriedBeans)-[:PURCHASE_AT]->(safeway)
CREATE (reynoldsParchmentPaperGenuineNonstick45SqFt)-[:PURCHASE_AT]->(safeway)
CREATE (riceBrown)-[:PURCHASE_AT]->(pcc)
CREATE (riceNikoNikoSushiShortGrainRice)-[:PURCHASE_AT]->(uwajimaya)
CREATE (riceNoodleSheets)-[:PURCHASE_AT]->(dummy)
CREATE (riceSticks)-[:PURCHASE_AT]->(hauHauMarket)
CREATE (riceWhiteBasmati)-[:PURCHASE_AT]->(centralCoop)
CREATE (riceWild)-[:PURCHASE_AT]->(centralCoop)
CREATE (riceWineVinegar)-[:PURCHASE_AT]->(uwajimaya)
CREATE (riceWineVinegarKikkomanMirin)-[:PURCHASE_AT]->(safeway)
CREATE (riceWineVinegarSake)-[:PURCHASE_AT]->(m2mMart)
CREATE (ricottaCheese15Oz)-[:PURCHASE_AT]->(qfc)
CREATE (roastBeef)-[:PURCHASE_AT]->(safeway)
CREATE (roastedUnsaltedPeanuts)-[:PURCHASE_AT]->(pcc)
CREATE (rolledOatsOatsOldFashionedPlu8490)-[:PURCHASE_AT]->(nakedGrocer)
CREATE (romaineLettuceHearts)-[:PURCHASE_AT]->(safeway)
CREATE (sage)-[:PURCHASE_AT]->(pcc)
CREATE (salmonCanned)-[:PURCHASE_AT]->(dummy)
CREATE (salmonFresh)-[:PURCHASE_AT]->(wholeFoods)
CREATE (salmonSmoked)-[:PURCHASE_AT]->(dummy)
CREATE (salmonStillFrozenInTheShrinkWrap2Or3Lbs)-[:PURCHASE_AT]->(safeway)
CREATE (salt)-[:PURCHASE_AT]->(qfc)
CREATE (saltinesUnsalted)-[:PURCHASE_AT]->(qfc)
CREATE (sauceForSpaghettis)-[:PURCHASE_AT]->(traderJoes)
CREATE (sausage)-[:PURCHASE_AT]->(traderJoes)
CREATE (savoySpinachUglySpinach)-[:PURCHASE_AT]->(pcc)
CREATE (scallionsOrChives)-[:PURCHASE_AT]->(safeway)
CREATE (seedsSunflower)-[:PURCHASE_AT]->(nakedGrocer)
CREATE (semiSweetChocolateChips)-[:PURCHASE_AT]->(traderJoes)
CREATE (serranos)-[:PURCHASE_AT]->(safeway)
CREATE (sesameButterTahini)-[:PURCHASE_AT]->(safeway)
CREATE (sesameOilToasted)-[:PURCHASE_AT]->(wholeFoods)
CREATE (sesameSeeds)-[:PURCHASE_AT]->(nakedGrocer)
CREATE (sesameSeedsToasted)-[:PURCHASE_AT]->(centralCoop)
CREATE (shallots)-[:PURCHASE_AT]->(safeway)
CREATE (shallotsFried)-[:PURCHASE_AT]->(pcc)
CREATE (shawarmaBeefSirloin)-[:PURCHASE_AT]->(traderJoes)
CREATE (shrimpFrozen)-[:PURCHASE_AT]->(groceryOutletBargainMarket)
CREATE (shrimpLargeNotFrozen)-[:PURCHASE_AT]->(safeway)
CREATE (shrimpLargeNotFrozen)-[:PURCHASE_AT]->(seattleSeafood)
CREATE (signatureSelectBeansGarbanzo15Oz)-[:PURCHASE_AT]->(safeway)
CREATE (signatureSelectCrackersGrahamHoney)-[:PURCHASE_AT]->(safeway)
CREATE (snowPeas)-[:PURCHASE_AT]->(uwajimaya)
CREATE (dishSoap)-[:PURCHASE_AT]->(centralCoop)
CREATE (sonicareSoftBristles)-[:PURCHASE_AT]->(bartell)
CREATE (sourdoughBread)-[:PURCHASE_AT]->(franzBakery)
CREATE (soySauceLiquidAminos)-[:PURCHASE_AT]->(dummy)
CREATE (spinach)-[:PURCHASE_AT]->(centralCoop)
CREATE (spinachFrozen)-[:PURCHASE_AT]->(safeway)
CREATE (squashButternut)-[:PURCHASE_AT]->(dummy)
CREATE (squashYellowCrookneck)-[:PURCHASE_AT]->(safeway)
CREATE (squid)-[:PURCHASE_AT]->(wholeFoods)
CREATE (sriracha)-[:PURCHASE_AT]->(traderJoes)
CREATE (stockVegetableDry)-[:PURCHASE_AT]->(centralCoop)
CREATE (strongRootsKaleQuinoaBurger)-[:PURCHASE_AT]->(wholeFoods)
CREATE (sugarPalm)-[:PURCHASE_AT]->(uwajimaya)
CREATE (sugarPureCane)-[:PURCHASE_AT]->(safeway)
CREATE (sundriedTomatoes)-[:PURCHASE_AT]->(safeway)
CREATE (superGreensBabySpinachBabyChardBabyKale)-[:PURCHASE_AT]->(safeway)
CREATE (syrupMaple)-[:PURCHASE_AT]->(safeway)
CREATE (tapatioHotSauce)-[:PURCHASE_AT]->(qfc)
CREATE (tapePainters)-[:PURCHASE_AT]->(hardwareStore)
CREATE (tarragon)-[:PURCHASE_AT]->(centralCoop)
CREATE (teffFlour)-[:PURCHASE_AT]->(dummy)
CREATE (texturizedVegetableProtein)-[:PURCHASE_AT]->(centralCoop)
CREATE (thaiBasil)-[:PURCHASE_AT]->(uwajimaya)
CREATE (thaiChilies)-[:PURCHASE_AT]->(uwajimaya)
CREATE (thaiEggplant)-[:PURCHASE_AT]->(uwajimaya)
CREATE (thaiKitchenRiceNoodlesStirFry)-[:PURCHASE_AT]->(safeway)
CREATE (thaiRedCurrySauce)-[:PURCHASE_AT]->(traderJoes)
CREATE (thinMiniRiceCrackerSnackers)-[:PURCHASE_AT]->(traderJoes)
CREATE (thinSlicerForShallots)-[:PURCHASE_AT]->(uwajimaya)
CREATE (thyme)-[:PURCHASE_AT]->(pcc)
CREATE (thymeFresh)-[:PURCHASE_AT]->(safeway)
CREATE (tofu)-[:PURCHASE_AT]->(hauHauMarket)
CREATE (tofu)-[:PURCHASE_AT]->(thanhSonTofu)
CREATE (tofuBaked)-[:PURCHASE_AT]->(traderJoes)
CREATE (tofuExtraFirm)-[:PURCHASE_AT]->(traderJoes)
CREATE (tofuSweetBbqPremarinatedSuperFirmBakedTofu)-[:PURCHASE_AT]->(qfc)
CREATE (toiletPaperBathTissue)-[:PURCHASE_AT]->(traderJoes)
CREATE (tomatillo)-[:PURCHASE_AT]->(safeway)
CREATE (tomatoPaste6OzCan)-[:PURCHASE_AT]->(safeway)
CREATE (tomatoSauce15OzCan)-[:PURCHASE_AT]->(safeway)
CREATE (tomatoSauce29OzCan)-[:PURCHASE_AT]->(safeway)
CREATE (tomatoesBeefsteak)-[:PURCHASE_AT]->(traderJoes)
CREATE (tomatoesCherry)-[:PURCHASE_AT]->(traderJoes)
CREATE (tomatoesCrushedInCan28Oz)-[:PURCHASE_AT]->(safeway)
CREATE (tomatoesDicedInBigCan28Oz)-[:PURCHASE_AT]->(safeway)
CREATE (tomatoesHeirloom)-[:PURCHASE_AT]->(traderJoes)
CREATE (tomatoesPeeledInCan28Oz)-[:PURCHASE_AT]->(safeway)
CREATE (tomatoesRoma)-[:PURCHASE_AT]->(traderJoes)
CREATE (tomatoesSunDriedRealBigJar)-[:PURCHASE_AT]->(safeway)
CREATE (tomatosInCan15OzCan)-[:PURCHASE_AT]->(safeway)
CREATE (tortellini)-[:PURCHASE_AT]->(traderJoes)
CREATE (tortillaFlourLargeDiameterDonPanchoOrSafewayBrand)-[:PURCHASE_AT]->(groceryOutletBargainMarket)
CREATE (tumeric)-[:PURCHASE_AT]->(madisonCoop)
CREATE (tumericPowder)-[:PURCHASE_AT]->(centralCoop)
CREATE (tunaInACan)-[:PURCHASE_AT]->(groceryOutletBargainMarket)
CREATE (tunaSteak)-[:PURCHASE_AT]->(dummy)
CREATE (turkey)-[:PURCHASE_AT]->(safeway)
CREATE (turkeyBacon)-[:PURCHASE_AT]->(dummy)
CREATE (turkeyBacon)-[:PURCHASE_AT]->(traderJoes)
CREATE (turkeyGround)-[:PURCHASE_AT]->(dummy)
CREATE (turkeyWhole)-[:PURCHASE_AT]->(dummy)
CREATE (unsaltedTopsUnsaltedSalteens)-[:PURCHASE_AT]->(qfc)
CREATE (vegenaise)-[:PURCHASE_AT]->(wholeFoods)
CREATE (vinegarAppleCider)-[:PURCHASE_AT]->(dummy)
CREATE (vinegarAppleCiderInGlassBottleNonOrgangic)-[:PURCHASE_AT]->(safeway)
CREATE (vinegarBalsamic)-[:PURCHASE_AT]->(traderJoes)
CREATE (vinegarRedWine)-[:PURCHASE_AT]->(safeway)
CREATE (vinegarRiceVinegar)-[:PURCHASE_AT]->(uwajimaya)
CREATE (vinegarWhite)-[:PURCHASE_AT]->(groceryOutletBargainMarket)
CREATE (watermelon)-[:PURCHASE_AT]->(traderJoes)
CREATE (wheatBerries)-[:PURCHASE_AT]->(centralCoop)
CREATE (whitePeppercorns)-[:PURCHASE_AT]->(madisonCoop)
CREATE (wineCharlesShaw)-[:PURCHASE_AT]->(traderJoes)
CREATE (worcestershireSauce)-[:PURCHASE_AT]->(safeway)
CREATE (yams)-[:PURCHASE_AT]->(traderJoes)
CREATE (yeastActivedry)-[:PURCHASE_AT]->(safeway)
CREATE (yogurtFlyingCowCreameryYogurtInReturnableGlassContainer)-[:PURCHASE_AT]->(traderJoes)
CREATE (yogurtNonfatPlainblueBucket)-[:PURCHASE_AT]->(traderJoes)
CREATE (yukonGoldPotatoes)-[:PURCHASE_AT]->(safeway)
CREATE (zucchini)-[:PURCHASE_AT]->(safeway)


CREATE (tsuyu)-[:IS_THE_SAME_AS]->(kikkomanJapaneseNoodleSoupBaseHonTsuyu)

CREATE (eliseBauer)-[:CREATED]->(salsaVerde)
CREATE (pailinChongchitnant)-[:CREATED]->(yellowCurry)
CREATE (pailinChongchitnant)-[:CREATED]->(redCurry)
CREATE (seonkyoungLongest)-[:CREATED]->(sesameNoodleRecipe)
CREATE (joshuaweissman)-[:CREATED]->(thaiCurry1)
CREATE (hanaAsbrink)-[:CREATED]->(coldSobaWithPerillaOilDressing)
CREATE (marionsKitchen)-[:CREATED]->(thaiPanangChickenCurry)
CREATE (recipetineats)-[:CREATED]->(yellowThaiCurry);

MATCH (n) RETURN n
