MATCH (n)
DETACH DELETE n;

// chefs
CREATE (seonkyoungLongest:Person { name: 'Seonkyoung Longest', urls: ["https://www.recipetineats.com", ""] })
CREATE (recipetineats:Person { name: 'Recipetineats', urls: ["https://www.recipetineats.com", ""] })
CREATE (marionsKitchen:Person { name: 'Marionskitchen', ytb: 'https://www.youtube.com/@Marionskitchen'})
CREATE (hanaAsbrink:Person { name: "Hana Asbrink", urls: ['https://www.youtube.com/@Marionskitchen',"https://www.youtube.com/c/HanaAsbrink","https://www.instagram.com/hanaasbrink/"]})
CREATE (joshuaweissman:Person { name: "Joshua Weissman", urls: ['https://www.youtube.com/@JoshuaWeissman']})
CREATE (subha:Person { name: 'Subha', urls: ["https://theflavoursofkitchen.com/about/"] })

// recipes
CREATE (yellowCoconutCurry:Recipe { name: 'Yellow Coconut Curry Chicken', urls: ['https://lifemadesimplebakes.com/wprm_print/25731']})
CREATE (thaiCurry1:Recipe { name: "The Best Green Curry", urls: ["https://www.joshuaweissman.com/post/easy-authentic-thai-green-curry", "https://photos.google.com/photo/AF1QipMJV_m1w-qezTjSZAmu6Vam_PKMR6GICW6TJ883"]})
CREATE (thaiEggplantRecipe:Recipe { name: "Thai Eggplant Recipe", urls: ["https://www.myfoodchannel.com/thai-eggplant-recipe/","https://www.youtube.com/watch?v=7a0IAC7pCgA"]})
CREATE (yellowThaiCurry:Recipe { name: 'Yellow Thai Curry', urls: ['https://www.youtube.com/watch?v=JaB3T4HpGE8']})
CREATE (thaiPanangChickenCurry:Recipe { name: "Thai Panang Chicken Curry", urls: "https://www.youtube.com/watch?v=QraggvxNMrk"})
CREATE (coldSobaWithPerillaOilDressing:Recipe { name: "Cold Soba With Periall Oil dresssing"})
CREATE (sesameNoodleRecipe:Recipe { name: "The Best Sesame Noodles From Korea Under 6 Minutes!",urls:["https://www.youtube.com/watch?v=HZ1VIYNAeR0", "https://seonkyounglongest.com/korean-sesame-noodles/print/46266/"]})
CREATE (koreanSesameNoodles:Recipe {name: 'Korean Sesame Noodles', urls: ['https://seonkyounglongest.com/korean-sesame-noodles/print/46266/']})
CREATE (chickenThaiRedCurry:Recipe { name: 'Chicken Thai Red Curry', urls: ['https://theflavoursofkitchen.com/wprm_print/104534'] })

// stores
CREATE (thanhSonTofu:Store { name: "Thanh Son Tofu" , urls:["https://www.yelp.com/biz/thanh-son-tofu-seattle-3"]})
CREATE (dummy:Store { name: "dummy place holder" })
CREATE (amazon:Store { name: "Amazon" })
CREATE (bartell:Store { name: "Bartell" })
CREATE (centralCoop:Store { name: "Central Co-op" })
CREATE (einsteinBrothersBagels:Store { name: "Einstein Brotheres Bagels" })
CREATE (franzBakery:Store { name: "Franz Bakery" })
CREATE (fredMeyer:Store { name: "Fred Meyer" })
CREATE (groceryOutlet:Store { name: "Grocery Outlet" })
CREATE (groceryOutletBargainMarket:Store { name: "Grocery Outlet Bargain Market" })
CREATE (hardwareStore:Store { name: "Hardware Store" })
CREATE (hauHauMarket:Store { name: "Hau Hau Market" })
CREATE (m2mMart:Store { name: "M2M Mart", notes: ["Korean Grocer"], urls: ["https://www.google.com/search?q=m2m+mart&oq=m2&gs_lcrp=EgZjaHJvbWUqCQgAECMYJxiKBTIJCAAQIxgnGIoFMhAIARAuGK8BGMcBGIAEGI4FMgoIAhAuGLEDGIAEMgoIAxAAGLEDGIAEMg0IBBAuGLEDGIAEGOUEMg0IBRAAGIMBGLEDGIAEMgoIBhAAGLEDGIAEMgoIBxAAGLEDGIAEMgcICBAAGIAEMgcICRAAGI8C0gEIMjI1N2owajeoAgCwAgA&sourceid=chrome&ie=UTF-8#lpg=cid:CgIgAQ%3D%3D,ik:CAoSLEFGMVFpcE15YzlKMF9jRTJzMFVUUHJjaFlvSUVLcnlCcnlXOFo5akpsR0dD"] })
CREATE (macrinaBakery:Store { name: "Macrina Bakery" })
CREATE (madisonCoop:Store { name: "Madison Co-op"})
CREATE (nakedGrocer:Store { name: "Naked Grocer" })
CREATE (pcc:Store { name: "PCC" })
CREATE (qfc:Store { name: "QFC" })
CREATE (safeway:Store { name: "Safeway" })
CREATE (seattleSeafood:Store { name: "Seattle Seafood" })
CREATE (traderJoes:Store { name: "Trader Joe's" })
CREATE (uwajimaya:Store { name: "Uwajimaya", urls: ["https://www.uwajimaya.com/"] })
CREATE (wholeFoods:Store { name: "Whole Foods" })

// products
CREATE (a1Sauce:Product { name: "A.1. Sauce" })
CREATE (allspice:Product { name: "Allspice" })
CREATE (almondMilksPlease:Product { name: "Almond milks please" })
CREATE (almondsBulkRoastedOrRawWhicheverIsCheaper:Product { name: "Almonds - bulk roasted or raw -- whichever is cheaper" })
CREATE (angkorCambodianFoodPasteLemongrass:Product { name: "Angkor Cambodian Food Paste Lemongrass" })
CREATE (apples:Product { name: "Apples" })
CREATE (artichokeHearts:Product { name: "Artichoke Hearts" })
CREATE (asparagus:Product { name: "Asparagus" })
CREATE (avocadosNotInBagStupid:Product { name: "Avocados (not in bag stupid)" })
CREATE (bacon:Product { name: "Bacon" })
CREATE (bakedTofu:Product { name: "Baked Tofu" ,urls:["https://www.google.com/search?sca_esv=579179295&sxsrf=AM9HkKnAjZCHvxR_pYrcL19p0l0Qjk1Zjg:1699032994034&q=Baked+Tofu&tbm=isch&source=lnms&sa=X&ved=2ahUKEwiwrsiQr6iCAxXHHjQIHVGWDjkQ0pQJegQIDRAB&biw=1440&bih=758&dpr=2"]})
CREATE (bakersDozen:Product { name: "Bakers Dozen" })
CREATE (bakingCupsInCakeMixflourAisle:Product { name: "Baking Cups in cake mix/flour aisle" })
CREATE (bakingSoda:Product { name: "Baking Soda" })
CREATE (ballPowderSmellsNice:Product { name: "Ball powder, smells nice" })
CREATE (bambooShoots:Product { name: "Bamboo Shoots" })
CREATE (bananasOrganic:Product { name: "Bananas organic" })
CREATE (barbecueSauceBabyRaysBbqSauce:Product { name: "Barbecue sauce - Baby Rays bbq sauce" })
CREATE (barley:Product { name: "Barley" })
CREATE (basilDry:Product { name: "Basil - Dry" })
CREATE (basilFresh:Product { name: "Basil - Fresh" })
CREATE (bayLeaf:Product { name: "Bay Leaf" })
CREATE (beanCannelloniWhite:Product { name: "Bean - Cannelloni White" })
CREATE (beanGreatNorthernWhite:Product { name: "Bean - Great Northern White" })
CREATE (beanNavyBean:Product { name: "Bean - Navy Bean" })
CREATE (beansBlack15OzCan:Product { name: "Beans - Black 15 oz can" })
CREATE (beansBlackBulk:Product { name: "Beans - Black, Bulk" })
CREATE (beansGreen:Product { name: "Beans - Green" })
CREATE (beansKidneyBulk:Product { name: "Beans - Kidney (Bulk)" })
CREATE (beefChuck:Product { name: "Beef Chuck" })
CREATE (beefChuckShoulderClod:Product { name: "Beef Chuck Shoulder clod" })
CREATE (beerLagger:Product { name: "Beer - Lagger" })
CREATE (beerSessionLager:Product { name: "Beer - Session Lager" })
CREATE (beets:Product { name: "Beets" })
CREATE (beetsCanned:Product { name: "Beets - Canned" })
CREATE (blueberriesFrozenUponinaBag:Product { name: "Blueberries - frozen uponina bag" })
CREATE (bokChoy:Product { name: "Bok Choy" })
CREATE (bonelessChickenThighs:Product {name: 'Boneless Chicken Thighs'})
CREATE (bonitoFlakes:Product {   name: "Bonito Flakes",   urls: ["https://chefjacooks.com/en/wprm_print/7506",          "https://www.amazon.com/Kaneso-Tokuyou-Hanakatsuo-Bonito-Flakes/dp/B0052BGLMS",          "https://www.google.com/search?sca_esv=577907868&sxsrf=AM9HkKmChgo0Ktu9IlnGTSWuzmK5YqQsiQ:1698696041201&q=Bonito+Flakes&tbm=isch&source=lnms&sa=X&ved=2ahUKEwjy0Pfwx56CAxUBODQIHey0BwcQ0pQJegQIDhAB&biw=1440&bih=758&dpr=2"  ]})
CREATE (boullionBeef:Product { name: "Boullion - Beef" })
CREATE (boullionVegetableBrothPowdered:Product { name: "Boullion - Vegetable Broth Powdered" })
CREATE (breadDavesYumsSeedBread:Product { name: "Bread - Dave's Yums Seed Bread" })
CREATE (breadFrench:Product { name: "Bread - French" })
CREATE (breadOlive:Product { name: "Bread - Olive" })
CREATE (breadPurpleNutsAndGrain:Product { name: "Bread - Purple Nuts And Grain" })
CREATE (breadSoda:Product { name: "Bread - Soda" })
CREATE (brewersYeast:Product { name: "Brewers Yeast" })
CREATE (broccoli6oz:Product { name: "Broccoli 6oz" })
CREATE (broccoli:Product { name: "Broccoli" })
CREATE (broccolini:Product { name: "Broccolini" })
CREATE (brothBeefLowSodium:Product { name: "Broth - Beef - low sodium" })
CREATE (brownSugar:Product { name: 'Brown Sugar' })
CREATE (brownieClifBar:Product { name: "brownie clif bar" })
CREATE (brownieMixBettyCrocker:Product { name: "Brownie Mix - Betty Crocker" })
CREATE (brownieMixDuncanHines:Product { name: "Brownie Mix - Duncan Hines" })
CREATE (brownieMixGhirardelli:Product { name: "Brownie Mix - Ghirardelli" })
CREATE (brownieMixPillsbury:Product { name: "Brownie Mix - Pillsbury" })
CREATE (buckwheatSoba:Product { name: "Buckwheat Soba",   urls: ["https://www.amazon.com/gp/product/B00101YEBO",          "https://veggiekinsblog.com/2020/01/13/vegan-zaru-soba/"]})
CREATE (bulgurWheat:Product { name: "Bulgur Wheat" })
CREATE (butterUnsalted:Product { name: "Butter - Unsalted" })
CREATE (cabbageGreenSmall:Product { name: "Cabbage, Green, small" })
CREATE (cabbageRedSmall:Product { name: "Cabbage, Red, small" })
CREATE (calamari:Product { name: "Calamari" })
CREATE (carrots:Product { name: 'Carrots' })
CREATE (cauliflower:Product { name: "Cauliflower" })
CREATE (cayennePepper:Product { name: "Cayenne Pepper" })
CREATE (celery:Product { name: "Celery" })
CREATE (chardonnayTerresDorees:Product { name: "chardonnay - terres dorees" })
CREATE (cheddarSharp:Product { name: "Cheddar - Sharp" })
CREATE (cheeseBlue:Product { name: "Cheese - blue" })
CREATE (cheeseExtraSharpCheddar:Product { name: "Cheese - Extra Sharp Cheddar" })
CREATE (cheeseGruyere:Product { name: "Cheese - Gruyere" })
CREATE (cheesePecorino:Product { name: "Cheese - Pecorino" })
CREATE (cheeseSharpSwiss:Product { name: "Cheese - Sharp Swiss" })
CREATE (cheeseShreddedMozzarella8Oz:Product { name: "Cheese - Shredded Mozzarella - 8 oz" })
CREATE (chicken34Lb:Product { name: "Chicken (3-4 lb)" })
CREATE (chickenBreast:Product { name: "Chicken Breast" })
CREATE (chickenBroth16Oz:Product { name: "Chicken Broth - 16 Oz" })
CREATE (chickenBroth32Oz:Product { name: "Chicken Broth - 32 Oz" })
CREATE (chickenBroth:Product { name: 'Chicken Broth' })
CREATE (chickenBrothSwanson145Oz:Product { name: "Chicken Broth - Swanson, 14.5 Oz" })
CREATE (chickenElectricRotisserie:Product { name: "chicken - electric - rotisserie" })
CREATE (chickenStock:Product { name: "Chicken stock"})
CREATE (chickenTenderloinsRubberDuckies1BagOnly:Product { name: "Chicken Tenderloins / Rubber Duckies / 1 BAG ONLY" })
CREATE (chickenThigh:Product { name: "Chicken thigh"})
CREATE (chilesChipotleInAdobo:Product { name: "Chiles - Chipotle in adobo" })
CREATE (chiliOil:Product {name: 'Chili Oil'})
CREATE (chiliPepperAnchoGround:Product { name: "Chili Pepper, Ancho, Ground" })
CREATE (chiliPepperChipotleGround:Product { name: "Chili Pepper, Chipotle, Ground" })
CREATE (chiliPowder:Product { name: "Chili powder"})
CREATE (chiliThai:Product { name: "Chili - Thai" })
CREATE (chineseBroccoli:Product { name: "Chinese Broccoli" })
CREATE (chips:Product { name: "Chips" })
CREATE (chocolateCoveredCherriesForJoyce:Product { name: "Chocolate covered cherries for Joyce" })
CREATE (choppedCalabrianPeppers:Product { name: "Chopped Calabrian Peppers" })
CREATE (cilantro:Product { name: 'Cilantro' })
CREATE (cinamon:Product { name: "Cinamon" })
CREATE (cinnamon:Product { name: "Cinnamon" })
CREATE (clamChowder:Product { name: "Clam Chowder" })
CREATE (clamJuice:Product { name: "Clam Juice" })
CREATE (clams:Product { name: "Clams" })
CREATE (cleanserBonAmi:Product { name: "Cleanser - Bon Ami" })
CREATE (clovesGarlic:Product { name: "Garlic cloves"})
CREATE (cocoaPowderUnsweetenedHersheysNatural8Oz:Product { name: "Cocoa Powder, Unsweetened, Hersheys Natural - 8 Oz" })
CREATE (coconutFlakes:Product { name: "Coconut Flakes" })
CREATE (coconutMilk135OzCan:Product { name: "Coconut Milk - 13.5 oz can" })
CREATE (coconutMilk:Product { name: "Full fat coconut milk"})
CREATE (coconutOil:Product { name: 'Coconut Oil' })
CREATE (coffeeBbPlu8875LessYumsThan8863:Product { name: "Coffee - BB - PLU 8875 (less yums than 8863)" })
CREATE (coffeeBbs1stPreferenceBbPlu8863EqualExchangePeruvian:Product { name: "Coffee / BB's 1st preference / BB / PLU 8863 / Equal Exchange / Peruvian" })
CREATE (coffeeBbs2ndPreferenceBbPlu3794KalaniCoffeeIndonesianEnyanaSumatra:Product { name: "Coffee / BB's 2nd preference / BB / PLU 3794 / Kalani Coffee / Indonesian Enyana Sumatra" })
CREATE (coffeeMtmKivuDarkEspressoRoast:Product { name: "Coffee - MTM - Kivu Dark Espresso Roast" })
CREATE (coffeeMtmPlu1859FidalgoBayOrganicFairTradeFrenchRoastExtraDark:Product { name: "Coffee - MTM - PLU 1859 - Fidalgo Bay Organic Fair Trade French Roast - Extra Dark" })
CREATE (coffeeMtmPlu5820KivuKivuDarkFrenchRoast:Product { name: "Coffee / MTM / PLU 5820 / Kivu / Kivu Dark French Roast" })
CREATE (coffeeMtmPlu8368DecafDecafDecafKindUnknown:Product { name: "Coffee / MTM / PLU 8368 / Decaf / Decaf / Decaf Kind Unknown" })
CREATE (coffeeTDecaf:Product { name: "Coffee - T - Decaf" })
CREATE (coffeeTPlu8852TLikesItBbSaysYux:Product { name: "Coffee - T - PLU 8852 T likes it, BB says YUX!" })
CREATE (coffeeTPlu8853:Product { name: "Coffee - T - PLU 8853" })
CREATE (coffeeTaylorPlu8868:Product { name: "Coffee - Taylor - PLU 8868" })
CREATE (cokeZero:Product { name: "Coke Zero" })
CREATE (collardGreens:Product { name: "Collard Greens" })
CREATE (coolMintChocolateClifBar:Product { name: "cool mint chocolate clif bar" })
CREATE (coriander:Product { name: "Coriander" })
CREATE (corianderPowder:Product { name: "Coriander powder"})
CREATE (corianderSeeds:Product { name: "Coriander seeds"})
CREATE (cornFrozen:Product { name: "Corn - Frozen" })
CREATE (cornOnCob:Product { name: "Corn on cob" })
CREATE (cornStarch:Product { name: "Corn Starch" })
CREATE (cornmeal:Product { name: "Cornmeal" })
CREATE (cornstarchBabyPowderNotJohnsonsTheyreBaddies:Product { name: "Cornstarch Baby Powder (not Johnson's, they're baddies)" })
CREATE (cottageCheeseLargeCurd:Product { name: "Cottage Cheese - Large Curd" })
CREATE (couscous:Product { name: "Couscous" })
CREATE (couscousIsraeli:Product { name: "Couscous - Israeli" })
CREATE (cranberriesDried:Product { name: "Cranberries (dried)" })
CREATE (creamHeavy:Product { name: "Cream - Heavy" })
CREATE (crest:Product { name: "Crest" })
CREATE (cucumber:Product { name: "Cucumber" })
CREATE (cucumbersEnglish:Product { name: "Cucumbers - English" })
CREATE (cucumbersPersian:Product { name: "Cucumbers - Persian" })
CREATE (cuminGround:Product { name: "Cumin - Ground" })
CREATE (cuminSeedNotGrounddog:Product { name: "Cumin - Seed (not grounddog)" })
CREATE (cuminSeeds:Product { name: "Cumin seeds"})
CREATE (curryPowder:Product { name: "Curry Powder" })
CREATE (dates:Product { name: "Dates" })
CREATE (dill:Product { name: "Dill" })
CREATE (dillPickles:Product { name: "Dill pickles" })
CREATE (dinoKaleUglySpinach:Product { name: "Dino Kale - ugly spinach" })
CREATE (driedSeaweed:Product { name: "WEL-PAC Dashi Kombu Dried Seaweed" })
CREATE (driedShrimp:Product { name: "Dried Shrimp" })
CREATE (driedThaiShrimpPaste:Product { name: "Dried Thai shrimp paste" })
CREATE (dukesMayonnaise:Product { name: "Duke's Mayonnaise" })
CREATE (edamameShelled:Product { name: "Edamame - Shelled" })
CREATE (eggplant:Product { name: "Eggplant" })
CREATE (eggplantChinese:Product { name: "Eggplant - Chinese" })
CREATE (eggplantThai:Product { name: "Eggplant - Thai" })
CREATE (eggsDozen:Product { name: "Eggs (Dozen)" })
CREATE (eggsLiquidEggWhitesBlueChikn:Product { name: "Eggs - Liquid Egg Whites (Blue Chikn)" })
CREATE (enchiladaSauceRed:Product { name: "Enchilada Sauce - Red" })
CREATE (endiveOrEscaroleLettce:Product { name: "Endive or Escarole lettce" })
CREATE (englishMuffins:Product { name: "English Muffins" })
CREATE (farro:Product { name: "Farro" })
CREATE (fetaYums:Product { name: "Feta Yums" })
CREATE (filtersCoffeeSize2:Product { name: "Filters - Coffee size #2" })
CREATE (fishSauce:Product { name: "Fish sauce"})
CREATE (fishSauceRedBoatPremium:Product { name: "Fish Sauce - Red Boat Premium" })
CREATE (fishTilapia:Product { name: "Fish - Tilapia" })
CREATE (flourWhiteAllpurposeUnbleachedIfPossibleButNoBigs:Product { name: "Flour - White, all-purpose (Unbleached if possible but no bigs)" })
CREATE (flourWholeWheatAllpurpose:Product { name: "Flour - Whole wheat, all-purpose" })
CREATE (franciscoInternationalFrenchSandwichRolls6Count:Product { name: "Francisco International French Sandwich Rolls 6 Count" })
CREATE (friedShallots:Product { name: "Fried shallots"})
CREATE (frozenMangos:Product { name: "Frozen Mangos" })
CREATE (frozenPeas:Product { name: "Frozen Peas" })
CREATE (galangal:Product { name: "Galangal"})
CREATE (garamMasala:Product { name: "Garam Masala" })
CREATE (garbanzoBeansDry:Product { name: "Garbanzo Beans - Dry" })
CREATE (garlic:Product { name: 'Garlic' })
CREATE (garlicChivesAlternativeChives:Product { name: "Garlic Chives (alternative: chives)" })
CREATE (garlicCloves:Product { name: "Garlic Cloves" })
CREATE (garlicPowder:Product { name: "Garlic Powder" })
CREATE (ginger:Product { name: "Ginger"})
CREATE (gingerPowder:Product { name: "Ginger Powder" })
CREATE (gingerRoot:Product { name: "Ginger root" })
CREATE (gochugaru:Product { name: "Gochugaru" })
CREATE (grainsOfParadiseSpice:Product { name: "Grains Of Paradise spice" })
CREATE (granolaCookies:Product { name: "Granola 'cookies'" })
CREATE (grapesGrapeShaped:Product { name: "Grapes, grape shaped" })
CREATE (greenOnion:Product {name: 'Green Onion'})
CREATE (gritsQuick:Product { name: "Grits - Quick" })
CREATE (groundBeef:Product { name: "Ground Beef" })
CREATE (habanero:Product { name: "Habanero" })
CREATE (halfgallonHalfHalf:Product { name: "Half-gallon half & half" })
CREATE (hamSliced:Product { name: "ham sliced" })
CREATE (heavyCream:Product { name: "Heavy Cream" })
CREATE (herbsOrSuperGreensLettuce:Product { name: "Herbs or super greens lettuce" })
CREATE (herbsOrSuperGreensLettucesBucket:Product { name: "Herbs or super greens lettuces bucket" })
CREATE (honeyInGlassJar:Product { name: "Honey in glass jar?" })
CREATE (iceCreamChocolateSignatureBrand:Product { name: "Ice cream chocolate - Signature brand" })
CREATE (iceCreamCones:Product { name: "Ice Cream Cones" })
CREATE (iceCreamDoublefudgeBrownieDreyersSlowchurned:Product { name: "Ice cream double-fudge brownie Dreyer's slow-churned" })
CREATE (italianSeasoning:Product { name: "Italian Seasoning" })
CREATE (japaneseNori:Product { name: "Japanese Nori", urls: ["https://www.google.com/search?client=emacs&sca_esv=577922779&sxsrf=AM9HkKkUxzT-KjHg9ziVgvqz5Zsqmn7xdw:1698703946500&q=Japanese+nori&tbm=isch&source=lnms&sa=X&ved=2ahUKEwi647yq5Z6CAxVxMjQIHRW8BBYQ0pQJegQIChAB&biw=1440&bih=758&dpr=2"] })
CREATE (johnsonsCreamyBabyOil:Product { name: "Johnsons Creamy Baby Oil" })
CREATE (kaffirLime:Product { name: "Kaffir Lime", urls: ["https://www.google.com/search?sca_esv=579007228&sxsrf=AM9HkKkqQcpTokvs8EUmjT-DnZNXV9I6Lw:1698970375605&q=kaffir+lime&tbm=isch&source=lnms&sa=X&ved=2ahUKEwiH6eLtxaaCAxVnMDQIHZ94DUYQ0pQJegQIDhAB&biw=1440&bih=758&dpr=2"] })
CREATE (kaffirLimeLeaves:Product { name: "Kaffir lime leaves", urls: ["https://www.wholefoodsmarket.com/product/kaffir-lime%20leaves-b07q8ldbvj", "https://www.youtube.com/watch?v=4Qz5nC-DcKk", "https://www.safeway.com/shop/marketplace/product-details.970537048.html", "https://photos.google.com/photo/AF1QipPI_6_YxYIuCSAvP93sDoRcyFDjekCQjNSb3Ln0", "https://photos.google.com/photo/AF1QipPd_yNuI9VcQAFOwMSuvBx40o_sl4gAmCgBYNIQ"] })
CREATE (kale:Product { name: "Kale" })
CREATE (katchup:Product { name: "Katchup" })
CREATE (kidneyBeansRedOrganic15Oz:Product { name: "Kidney Beans, Red, Organic, 15 Oz" })
CREATE (kidneyBeansSw:Product { name: "Kidney Beans - S&W" })
CREATE (kombucha:Product { name: "Kombucha" })
CREATE (leeKumKeeSoySaucePremiumDarkBottle:Product { name: "Lee Kum Kee Soy Sauce Premium Dark Bottle" })
CREATE (lemon:Product { name: "Lemon" })
CREATE (lemonGrass:Product {name: 'Lemon Grass'})
CREATE (lemonJuice:Product { name: "Lemon Juice" })
CREATE (lemonZestGratedLemonRind:Product { name: "Lemon Zest (grated lemon rind)" })
CREATE (lemongrass3Stalks:Product { name: "Lemongrass - 3 stalks" })
CREATE (lemongrassStalk:Product { name: "Lemongrass stalk" })
CREATE (lentilsBlackBeluga:Product { name: "Lentils - Black, Beluga" })
CREATE (lentilsBrown:Product { name: "Lentils - Brown" })
CREATE (lentilsGreen:Product { name: "Lentils (Green)" })
CREATE (lettucesRomaine:Product { name: "Lettuces - Romaine" })
CREATE (lightBrownSugar:Product {name: 'Light Brown Sugar'})
CREATE (lime:Product { name: "Lime" })
CREATE (limeJuice:Product { name: "Lime juice" })
CREATE (limeLeavesKaffir:Product { name: "Lime Leaves - Kaffir" })
CREATE (limes:Product { name: "Limes" })
CREATE (lobsterCornChowder:Product { name: "Lobster Corn Chowder" })
CREATE (maesriThaiRedCurryPaste:Product { name: 'Maesri Thai Red Curry Paste', urls:["https://www.wholefoodsmarket.com/product/maesri-red-curry-paste-b0013esw84"]})
CREATE (maltomeal:Product { name: "Malt-o-Meal" })
CREATE (marjoramLeaves:Product { name: "Marjoram Leaves" })
CREATE (marketspiceTeaDecaf2OzForMommy:Product { name: "Marketspice Tea Decaf - 2 Oz for Mommy" })
CREATE (martianmallowsLargeButNotGigantic:Product { name: "Martianmallows - Large but not gigantic" })
CREATE (meatSliced:Product { name: "Meat - Sliced" })
CREATE (merlot:Product { name: "Merlot" })
CREATE (mintOrMintExtract:Product { name: "Mint or Mint Extract" })
CREATE (misoPaste:Product { name: "Miso Paste" })
CREATE (misoSweetWhite:Product { name: "Miso - Sweet White" })
CREATE (molasses:Product { name: "Molasses" })
CREATE (mouthwashActRestoring:Product { name: "mouthwash - act restoring" })
CREATE (mushroomsCrimini:Product { name: "Mushrooms, Crimini" })
CREATE (mushroomsPortobello:Product { name: "Mushrooms - Portobello" })
CREATE (mustardGermanMediumHotInJarWHandle:Product { name: "Mustard - German medium hot in jar w/ handle" })
CREATE (mustardSpicyBrownInGlassJarPlease:Product { name: "Mustard - Spicy Brown - in glass jar please" })
CREATE (myntzes:Product { name: "Myntzes" })
CREATE (noodlesLasagna:Product { name: "Noodles - Lasagna" })
CREATE (nutmeg:Product { name: "Nutmeg" })
CREATE (oOrganicsOrganicCoconutOilVirginUnrefined:Product { name: "O Organics Organic Coconut Oil Virgin Unrefined" })
CREATE (oil:Product {name: 'Oil'})
CREATE (oilAvocado:Product { name: "Oil - Avocado" })
CREATE (oilOliveExtraVirgin:Product { name: "Oil - Olive - Extra Virgin" })
CREATE (oliveOrCoconutOil:Product { name: "Olive or coconut oil" })
CREATE (olivesCastelvetrano:Product { name: "Olives - Castelvetrano" })
CREATE (olivesKalamataPitted:Product { name: "Olives Kalamata Pitted" })
CREATE (onePercentMilkYellowCarton:Product { name: "One Percent milk yellow carton" })
CREATE (onePercentOr2PercentMilkInGlassJarNotRedCapWholeMilk:Product { name: "One Percent or 2 Percent milk in glass jar (not red cap whole milk)" })
CREATE (onion:Product { name: "Onion" })
CREATE (onionPowder:Product { name: "Onion Powder" })
CREATE (onionRed:Product { name: "Onion - Red" })
CREATE (onionSweet:Product { name: "Onion - Sweet" })
CREATE (onionWhite1:Product { name: "Onion - White (1)" })
CREATE (onions:Product { name: "Onions" })
CREATE (orangeJuice:Product { name: "Orange Juice" })
CREATE (oranges:Product { name: "Oranges" })
CREATE (oregano:Product { name: "Oregano" })
CREATE (organicSaladFreshHerbBlend:Product { name: "Organic Salad Fresh Herb Blend" })
CREATE (oysterMushrooms:Product { name: "Oyster Mushrooms" })
CREATE (oysterSauce:Product { name: "Oyster Sauce" })
CREATE (padThaiSauce:Product { name: "Pad Thai Sauce" })
CREATE (palmSugar:Product { name: "Palm sugar" })
CREATE (pancakeMixSnoqualmieFallsLodge:Product { name: "Pancake Mix - Snoqualmie Falls Lodge" })
CREATE (paprika:Product { name: "Paprika" })
CREATE (paprikaSmoked:Product { name: "Paprika - Smoked" })
CREATE (parmesanCheese:Product { name: "Parmesan Cheese" })
CREATE (parsley:Product { name: "Parsley" })
CREATE (pastaFettuccine:Product { name: "Pasta - Fettuccine" })
CREATE (pastaLinguine:Product { name: "Pasta - Linguine" })
CREATE (pastaRigatoni:Product { name: "Pasta - Rigatoni" })
CREATE (pastaTrottole:Product { name: "Pasta - Trottole" })
CREATE (peanutButterAdamsUnsalted:Product { name: "Peanut Butter - Adams Unsalted" })
CREATE (peanutButterBulk:Product { name: "Peanut butter - bulk" })
CREATE (pearsAnjou:Product { name: "Pears - Anjou" })
CREATE (pearsBartlett:Product { name: "Pears - Bartlett" })
CREATE (pearsBosc:Product { name: "Pears - Bosc" })
CREATE (pepperBlackBulk:Product { name: "Pepper - Black, Bulk" })
CREATE (pepperChipotle:Product { name: "Pepper - Chipotle" })
CREATE (pepperFlakesSpiceyRedPepperFlakes:Product { name: "Pepper Flakes - Spicey Red Pepper Flakes" })
CREATE (pepperJalapeno:Product { name: "Pepper - Jalapeno" })
CREATE (pepperSerrano:Product { name: "Pepper - Serrano" })
CREATE (peppercornsWholeBlack:Product { name: "Peppercorns, Whole, Black" })
CREATE (periPeriSauceGarlic:Product { name: "Peri Peri Sauce - Garlic" })
CREATE (perillaOil:Product { name: "Perilla Oil", urls: ["https://www.youtube.com/watch?v=VpAS3RarPi8", "https://megakfood.com/products/8801045448503", "https://photos.google.com/photo/AF1QipNe7d-KXSpC90FJ1uJNMnH1fMFZ6E8Qlzr_j3Q0", "https://photos.google.com/photo/AF1QipOLrXnJ8Bj20xFh5lg5yhm71ApUoRlT1z6_ZqnB", "https://photos.google.com/photo/AF1QipP8OZZvarZPkNnnaOOv3k_ng9doQzMeVZgONlxK"] })
CREATE (pineNuts:Product { name: "Pine Nuts" })
CREATE (pinotGrigioDryWhiteWine:Product { name: "Pinot Grigio - dry white wine" })
CREATE (pistachios:Product { name: "Pistachios" })
CREATE (plums:Product { name: "Plums" })
CREATE (polenta:Product { name: "Polenta" })
CREATE (popcorn:Product { name: "Popcorn" })
CREATE (pork:Product { name: "Pork" })
CREATE (potatoesBabyTriColor:Product { name: "Potatoes - Baby / Tri Color" })
CREATE (potatoesRusset2:Product { name: "Potatoes - Russet (2)" })
CREATE (primoTaglioCheeseGoat4Oz:Product { name: "Primo Taglio Cheese Goat - 4 Oz" })
CREATE (prunes:Product { name: "Prunes" })
CREATE (pumpkinSeedsSalted:Product { name: "Pumpkin seeds - Salted" })
CREATE (quickRolledOatsOatsPlu8485:Product { name: "Quick Rolled Oats / Oats PLU 8485" })
CREATE (quinoaRed:Product { name: "Quinoa - Red" })
CREATE (quinoaWhite:Product { name: "Quinoa - White" })
CREATE (radish:Product { name: "Radish" })
CREATE (raisinsBulkBabyBulk:Product { name: "Raisins - Bulk baby, bulk" })
CREATE (ramenNoodlesDry:Product { name: "Ramen Noodles - Dry" })
CREATE (redBellPepper:Product { name: "Red bell pepper" })
CREATE (redChili:Product {name: 'Red Chili'})
CREATE (redChilliPeppers:Product { name: "Red Chilli peppers" })
CREATE (redCurryPaste:Product {name: 'Red Curry Paste'})
CREATE (redGreenYellaPeppers:Product { name: "Red, Green, Yella Peppers" })
CREATE (redLentils:Product { name: "Red Lentils" ,urls: ["https://images.albertsons-media.com/is/image/ABS/127100073-ECOM","https://www.google.com/search?q=don+pancho+gorditas&sxsrf=ALiCzsbRwUHe7CL6uuSFX0okDfWkDvjqnQ:1665076315963&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjO0djSjMz6AhVLMjQIHZGcAbAQ_AUoAXoECAIQAw&biw=1107&bih=574&dpr=2.5#imgrc=Z2KBPh70c6uKAM"]})
CREATE (refriedBeansVegetarianNoLardTard:Product { name: "Refried beans - vegetarian / no lard tard!" })
CREATE (reynoldsParchmentPaperGenuineNonstick45SqFt:Product { name: "Reynolds Parchment Paper Genuine Non-Stick 45 Sq. Ft." })
CREATE (rice:Product { name: 'Rice' })
CREATE (riceBrown:Product { name: "Rice - Brown" })
CREATE (riceNikoNikoSushiShortGrainRice:Product { name: "Rice - Niko Niko - Sushi - Short Grain rice" })
CREATE (riceNoodleSheets:Product { name: "Rice Noodle Sheets" })
CREATE (riceSticks:Product { name: "Rice Sticks" })
CREATE (riceWhiteBasmati:Product { name: "Rice - White Basmati" })
CREATE (riceWild:Product { name: "Rice - Wild" })
CREATE (riceWineVinegar:Product { name: "Rice Wine Vinegar" })
CREATE (riceWineVinegarKikkomanMirin:Product { name: "Rice Wine Vinegar - Kikkoman Mirin" })
CREATE (riceWineVinegarSake:Product { name: "Rice Wine Vinegar - Sake" })
CREATE (ricottaCheese15Oz:Product { name: "Ricotta Cheese - 15 oz" })
CREATE (roastBeef:Product { name: "Roast Beef" })
CREATE (roastedUnsaltedPeanuts:Product { name: "Roasted unsalted Peanuts" })
CREATE (rolledOatsOatsOldFashionedPlu8490:Product { name: "Rolled Oats / Oats / Old fashioned / PLU 8490" })
CREATE (romaineLettuceHearts:Product { name: "Romaine Lettuce Hearts" })
CREATE (russetPotatoes:Product { name: 'Russet Potatoes' })
CREATE (sage:Product { name: "Sage" })
CREATE (salmonCanned:Product { name: "Salmon - Canned" })
CREATE (salmonFresh:Product { name: "Salmon - Fresh" })
CREATE (salmonSmoked:Product { name: "Salmon - Smoked" })
CREATE (salmonStillFrozenInTheShrinkWrap2Or3Lbs:Product { name: "Salmon - Still frozen in the shrink wrap, 2 or 3 lbs" })
CREATE (salt:Product { name: "Salt" })
CREATE (saltRegularIodizedTableSalt:Product { name: "Salt - regular iodized table salt" })
CREATE (saltinesUnsalted:Product { name: "Saltines - Unsalted" })
CREATE (sauceForSpaghettis:Product { name: "Sauce for spaghettis" })
CREATE (sausage:Product { name: "Sausage" })
CREATE (savoySpinachUglySpinach:Product { name: "Savoy Spinach - Ugly spinach" })
CREATE (scallionsOrChives:Product { name: "Scallions or Chives" })
CREATE (seaweed:Product {name: 'Toasted Seaweed'})
CREATE (seedsSunflower:Product { name: "Seeds - Sunflower" })
CREATE (semiSweetChocolateChips:Product { name: "Semi Sweet Chocolate Chips" })
CREATE (serranos:Product { name: "Serranos" })
CREATE (sesameButterTahini:Product { name: "Sesame Butter Tahini" })
CREATE (sesameOil:Product {name: 'Korean Wild Sesame Oil'})
CREATE (sesameOilToasted:Product { name: "Sesame Oil - Toasted" })
CREATE (sesameSeeds:Product { name: "Sesame Seeds" })
CREATE (sesameSeedsToasted:Product { name: "Sesame Seeds - Toasted" })
CREATE (shallotX1:Product { name: "Shallot x1" })
CREATE (shallots:Product { name: "Shallots" })
CREATE (shallotsFried:Product { name: "Shallots, fried" })
CREATE (shawarmaBeefSirloin:Product { name: "Shawarma Beef Sirloin" })
CREATE (shrimpFrozen:Product { name: "Shrimp - Frozen" })
CREATE (shrimpLargeNotFrozen:Product { name: "Shrimp - Large (not frozen)" })
CREATE (signatureSelectBeansGarbanzo15Oz:Product { name: "Signature SELECT Beans Garbanzo - 15 Oz" })
CREATE (signatureSelectCrackersGrahamHoney:Product { name: "Signature Select Crackers Graham Honey" })
CREATE (snowPeas:Product { name: "Snow peas" })
CREATE (soap:Product { name: "Soap" })
CREATE (sobaNoodles:Product {name: 'Soba Noodles'})
CREATE (sonicareSoftBristles:Product { name: "Sonicare soft bristles" })
CREATE (sourdoughBread:Product { name: "Sourdough bread" })
CREATE (soySauceLiquidAminos:Product { name: "Soy Sauce - Liquid Aminos" })
CREATE (spinach:Product { name: "Spinach" })
CREATE (spinachFrozen:Product { name: "Spinach - Frozen" })
CREATE (squashButternut:Product { name: "Squash - Butternut" })
CREATE (squashYellowCrookneck:Product { name: "Squash - Yellow Crookneck" })
CREATE (squid:Product { name: "Squid" })
CREATE (sriracha:Product { name: "Sriracha" })
CREATE (stockVegetableDry:Product { name: "Stock - Vegetable - dry" })
CREATE (stockWater:Product {name: 'Stock / Water'})
CREATE (strongRootsKaleQuinoaBurger:Product { name: "Strong Roots Kale & Quinoa Burger" })
CREATE (sugarPalm:Product { name: "Sugar - Palm" })
CREATE (sugarPureCane:Product { name: "Sugar - Pure Cane" })
CREATE (sundriedTomatoes:Product { name: "Sundried Tomatoes" })
CREATE (superGreensBabySpinachBabyChardBabyKale:Product { name: "Super Greens Baby Spinach Baby Chard Baby Kale" })
CREATE (syrupMaple:Product { name: "Syrup - Maple" })
CREATE (tapatioHotSauce:Product { name: "Tapatio Hot Sauce" })
CREATE (tapePainters:Product { name: "Tape - Painters" })
CREATE (tarragon:Product { name: "Tarragon" })
CREATE (teffFlour:Product { name: "Teff flour" })
CREATE (texturizedVegetableProtein:Product { name: "texturized vegetable protein" })
CREATE (thaiBasil:Product { name: "Thai basil" ,urls: ["https://www.fredmeyer.com/p/simple-truth-organic-thai-basil/0001111001922"]})
CREATE (thaiChilies:Product { name: "Thai chilies"})
CREATE (thaiEggplant:Product { name: "Thai Eggplant" })
CREATE (thaiKitchenRiceNoodlesStirFry:Product { name: "Thai Kitchen Rice Noodles Stir Fry" })
CREATE (thaiRedCurrySauce:Product { name: "Thai Red Curry Sauce" })
CREATE (thaiShrimpPaste:Product { name: "Dried Thai shrimp paste", urls: ["https://www.eatingthaifood.com/thai-nam-prik-kapi-recipe/"], comments: ["thaiShrimpPasteComment1", "thaiShrimpPasteComment2"], google: ["shrimp paste kapi OR gabi OR gkabi"] })
CREATE (thinMiniRiceCrackerSnackers:Product { name: "Thin mini rice cracker snackers" })
CREATE (thinSlicerForShallots:Product { name: "Thin slicer for Shallots" })
CREATE (thyme:Product { name: "Thyme" })
CREATE (thymeFresh:Product { name: "Thyme - Fresh" })
CREATE (tofu:Product { name: "Tofu" })
CREATE (tofuBaked:Product { name: "Tofu - Baked" })
CREATE (tofuExtraFirm:Product { name: "Tofu - extra firm" })
CREATE (tofuSweetBbqPremarinatedSuperFirmBakedTofu:Product { name: "Tofu - Sweet BBQ Pre-Marinated Super Firm Baked Tofu" })
CREATE (toiletPaperBathTissue:Product { name: "Toilet Paper bath tissue" })
CREATE (tomatillo:Product { name: "Tomatillo" })
CREATE (tomatoPaste6OzCan:Product { name: "Tomato Paste - 6 oz can" })
CREATE (tomatoSauce15OzCan:Product { name: "Tomato Sauce - 15 oz can" })
CREATE (tomatoSauce29OzCan:Product { name: "Tomato Sauce - 29 oz can" })
CREATE (tomatoesBeefsteak:Product { name: "Tomatoes - Beefsteak" })
CREATE (tomatoesCherry:Product { name: "Tomatoes - Cherry" })
CREATE (tomatoesCrushedInCan28Oz:Product { name: "Tomatoes - Crushed in can 28 Oz" })
CREATE (tomatoesDicedInBigCan28Oz:Product { name: "Tomatoes - Diced in big can 28 Oz" })
CREATE (tomatoesHeirloom:Product { name: "Tomatoes - Heirloom" })
CREATE (tomatoesPeeledInCan28Oz:Product { name: "Tomatoes - Peeled in can 28 Oz" })
CREATE (tomatoesRoma:Product { name: "Tomatoes - Roma" })
CREATE (tomatoesSunDriedRealBigJar:Product { name: "Tomatoes - sun dried - real big jar" })
CREATE (tomatosInCan15OzCan:Product { name: "Tomatos in can (15 oz can)" })
CREATE (tortellini:Product { name: "Tortellini" })
CREATE (tortillaFlourLargeDiameterDonPanchoOrSafewayBrand:Product { name: "Tortilla - Flour large diameter Don Pancho or Safeway brand" })
CREATE (tsuyu:Product {name: 'Tsuyu', googleSearch: "tsuyu, soup seasoning sauce", urls:["https://www.google.com/search?q=tsuyu+soup+seasoning+sauce&oq=tsuyu+soup+seasoning+sauce"]})
CREATE (kikkomanJapaneseNoodleSoupBaseHonTsuyu:Product {   name: "Kikkoman Japanese Noodle Soup Base (Hon Tsuyu)",   manufacturer: "Kikkoman",   urls: ["https://www.amazon.com/Kikkoman-Japanese-Noodle-Soup-Tsuyu/dp/B002Z3F0IW",  "https://www.google.com/search?q=kikkoman+japanese+noodle+soup+base(hon+tsuyu)&oq=Kikkoman+Japanese+Noodle+Soup+Base(Hon+Tsuyu)&gs_lcrp=EgZjaHJvbWUqBwgAEAAYgAQyBwgAEAAYgAQyBwgBEAAYgAQyCggCEAAYhgMYigUyCggDEAAYhgMYigUyBggEEEUYPDIGCAUQRRg9MgYIBhBFGD3SAQc0NzBqMGo0qAIAsAIA&sourceid=chrome&ie=UTF-8", "https://www.youtube.com/watch?v=61nPpDkz1AI"] })

CREATE (tumeric:Product { name: "Tumeric"})
CREATE (tumericPowder:Product { name: "Tumeric Powder" })
CREATE (tunaInACan:Product { name: "Tuna in a can" })
CREATE (tunaSteak:Product { name: "Tuna - Steak" })
CREATE (turkey:Product { name: "Turkey" })
CREATE (turkeyBacon:Product { name: "Turkey bacon" })
CREATE (turkeyGround:Product { name: "Turkey - Ground" })
CREATE (turkeyWhole:Product { name: "Turkey - Whole" })
CREATE (turmeric:Product { name: "Turmeric"})
CREATE (unsaltedTopsUnsaltedSalteens:Product { name: "Unsalted Tops (unsalted salteens)" })
CREATE (vegenaise:Product { name: "Vegenaise", detail: "Vegenaise - Follow Your Heart Dressing Vegenaise For Vegetarians - 16 Fl. Oz.",urls: ["https://www.qfc.com/p/duke-s-real-mayonnaise/0005250005005?fulfillment=PICKUP&searchType=mktg+attribute","https://www.youtube.com/watch?v=dZLkmXCAK8w"] })
CREATE (vinegarAppleCider:Product { name: "Vinegar - Apple Cider" })
CREATE (vinegarAppleCiderInGlassBottleNonOrgangic:Product { name: "Vinegar - Apple Cider in glass bottle / Non organgic" })
CREATE (vinegarBalsamic:Product { name: "Vinegar - Balsamic" })
CREATE (vinegarRedWine:Product { name: "Vinegar - Red Wine" })
CREATE (vinegarRiceVinegar:Product { name: "Vinegar - Rice Vinegar" })
CREATE (vinegarWhite:Product { name: "Vinegar - White" })
CREATE (watermelon:Product { name: "Watermelon" })
CREATE (wheatBerries:Product { name: "Wheat Berries" })
CREATE (whitePeppercorn:Product { name: "White peppercorn" })
CREATE (wineCharlesShaw:Product { name: "Wine - Charles Shaw" })
CREATE (worcestershireSauce:Product { name: "Worcestershire Sauce" })
CREATE (yams:Product { name: "Yams" })
CREATE (yeastActivedry:Product { name: "Yeast (ActiveDry)" })
CREATE (yellowCurryPowder:Product { name: 'Yellow Curry Powder', urls: ["https://www.google.com/search?q=Yellow+Curry+Powder+near+me&tbm=isch&ved=2ahUKEwiVxLm7h6mCAxWIFjQIHTNwBKoQ2-cCegQIABAA&oq=Yellow+Curry+Powder+near+me&gs_lcp=CgNpbWcQAzIHCAAQGBCABDoECCMQJzoGCAAQBxAeOgYIABAIEB46BAgAEB46BggAEAUQHlDIBViIEGD3EWgAcAB4AIABS4gBkQSSAQE5mAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=QoxFZZWbEYit0PEPs-CR0Ao&bih=758&biw=1440&client=emacs"]})
CREATE (yellowOnion:Product { name: 'Yellow Onion' })
CREATE (yogurtFlyingCowCreameryYogurtInReturnableGlassContainer:Product { name: "Yogurt - Flying Cow Creamery - Yogurt in returnable glass container" })
CREATE (yogurtNonfatPlainblueBucket:Product { name: "Yogurt - Nonfat (Plain/Blue Bucket)" })
CREATE (yukonGoldPotatoes:Product { name: "Yukon Gold Potatoes" })
CREATE (zucchini:Product { name: "Zucchini" })

CREATE (coldSobaWithPerillaOilDressing)-[:CONTAINS]->(buckwheatSoba)
CREATE (coldSobaWithPerillaOilDressing)-[:CONTAINS]->(japaneseNori)
CREATE (coldSobaWithPerillaOilDressing)-[:CONTAINS]->(perillaOil)

CREATE (koreanSesameNoodles)-[:CONTAINS {quantity: '1 portion'}]->(sobaNoodles)
CREATE (koreanSesameNoodles)-[:CONTAINS {quantity: '1 1/2 tbsp'}]->(tsuyu)
CREATE (koreanSesameNoodles)-[:CONTAINS {quantity: '1 tbsp'}]->(sesameOil)
CREATE (koreanSesameNoodles)-[:CONTAINS {quantity: '1 green onion or chive, chopped'}]->(greenOnion)
CREATE (koreanSesameNoodles)-[:CONTAINS {quantity: '1 tsp'}]->(sesameSeedsToasted)
CREATE (koreanSesameNoodles)-[:CONTAINS {quantity: '1 sheet (optional)'}]->(seaweed)
CREATE (koreanSesameNoodles)-[:CONTAINS {quantity: '1 tbsp'}]->(chiliOil)
CREATE (koreanSesameNoodles)-[:CONTAINS {quantity: '1 green onion or chive, chopped'}]->(greenOnion)
CREATE (koreanSesameNoodles)-[:CONTAINS {quantity: '1 tsp'}]->(sesameSeeds)
CREATE (koreanSesameNoodles)-[:CONTAINS {quantity: 'a few slices (optional)'}]->(redChili)

CREATE (chickenThaiRedCurry)-[:CONTAINS { quantity: '500 grams' }]->(bonelessChickenThighs)
CREATE (chickenThaiRedCurry)-[:CONTAINS { quantity: '2 tablespoons' }]->(oil)
CREATE (chickenThaiRedCurry)-[:CONTAINS { quantity: '4 tablespoons' }]->(redCurryPaste)
CREATE (chickenThaiRedCurry)-[:CONTAINS { quantity: '½ Onion sliced' }]->(onion)
CREATE (chickenThaiRedCurry)-[:CONTAINS { quantity: '½ tablespoon Garlic minced' }]->(garlic)
CREATE (chickenThaiRedCurry)-[:CONTAINS { quantity: '1 teaspoon Ginger minced' }]->(ginger)
CREATE (chickenThaiRedCurry)-[:CONTAINS { quantity: '1 stalk' }]->(lemonGrass)
CREATE (chickenThaiRedCurry)-[:CONTAINS { quantity: '2 teaspoon' }]->(fishSauce)
CREATE (chickenThaiRedCurry)-[:CONTAINS { quantity: '½ tablespoon' }]->(lightBrownSugar)
CREATE (chickenThaiRedCurry)-[:CONTAINS { quantity: '1 Red Bell Pepper' }]->(redBellPepper)
CREATE (chickenThaiRedCurry)-[:CONTAINS { quantity: '1 cup' }]->(zucchini)
CREATE (chickenThaiRedCurry)-[:CONTAINS { quantity: '1.5 cup' }]->(coconutMilk)
CREATE (chickenThaiRedCurry)-[:CONTAINS { quantity: '½ cup' }]->(stockWater)
CREATE (chickenThaiRedCurry)-[:CONTAINS { quantity: '2 teaspoon' }]->(lemonJuice)
CREATE (chickenThaiRedCurry)-[:CONTAINS { quantity: '8-10 leaves' }]->(thaiBasil)
CREATE (yellowCoconutCurry)-[:CONTAINS { quantity: '1 tbsp.' }]->(coconutOil)
CREATE (yellowCoconutCurry)-[:CONTAINS { quantity: '1/2' }]->(yellowOnion)
CREATE (yellowCoconutCurry)-[:CONTAINS { quantity: '2 cloves' }]->(garlic)
CREATE (yellowCoconutCurry)-[:CONTAINS { quantity: '1 lb.' }]->(chickenBreast)
CREATE (yellowCoconutCurry)-[:CONTAINS { quantity: '3' }]->(carrots)
CREATE (yellowCoconutCurry)-[:CONTAINS { quantity: '2' }]->(russetPotatoes)
CREATE (yellowCoconutCurry)-[:CONTAINS { quantity: '3 tbsp.' }]->(yellowCurryPowder)
CREATE (yellowCoconutCurry)-[:CONTAINS { quantity: '1 1/2 tbsp.' }]->(maesriThaiRedCurryPaste)
CREATE (yellowCoconutCurry)-[:CONTAINS { quantity: '1 14 oz. can' }]->(coconutMilk)
CREATE (yellowCoconutCurry)-[:CONTAINS { quantity: '3 c.' }]->(chickenBroth)
CREATE (yellowCoconutCurry)-[:CONTAINS { quantity: '2 tbsp.' }]->(brownSugar)
CREATE (yellowCoconutCurry)-[:CONTAINS { quantity: '1 tsp.' }]->(fishSauce)
CREATE (yellowCoconutCurry)-[:CONTAINS { quantity: 'if desired' }]->(cilantro)
CREATE (yellowCoconutCurry)-[:CONTAINS { quantity: 'with rice' }]->(rice)
CREATE (thaiCurry1)-[:CONTAINS]->(cilantro)
CREATE (thaiCurry1)-[:CONTAINS]->(clovesGarlic)
CREATE (thaiCurry1)-[:CONTAINS]->(chickenStock)
CREATE (thaiCurry1)-[:CONTAINS]->(chickenThigh)
CREATE (thaiCurry1)-[:CONTAINS]->(coconutMilk)
CREATE (thaiCurry1)-[:CONTAINS]->(corianderSeeds)
CREATE (thaiCurry1)-[:CONTAINS]->(fishSauce)
CREATE (thaiCurry1)-[:CONTAINS]->(friedShallots)
CREATE (thaiCurry1)-[:CONTAINS]->(galangal)
CREATE (thaiCurry1)-[:CONTAINS]->(kaffirLime)
CREATE (thaiCurry1)-[:CONTAINS]->(cuminSeeds)
CREATE (thaiCurry1)-[:CONTAINS]->(kaffirLimeLeaves)
CREATE (thaiCurry1)-[:CONTAINS]->(lemongrassStalk)
CREATE (thaiCurry1)-[:CONTAINS]->(lime)
CREATE (thaiCurry1)-[:CONTAINS]->(palmSugar)
CREATE (thaiCurry1)-[:CONTAINS]->(serranos)
CREATE (thaiCurry1)-[:CONTAINS]->(shallots)
CREATE (thaiCurry1)-[:CONTAINS]->(snowPeas)
CREATE (thaiCurry1)-[:CONTAINS]->(thaiBasil)
CREATE (thaiCurry1)-[:CONTAINS]->(thaiEggplant)
CREATE (thaiCurry1)-[:CONTAINS]->(thaiShrimpPaste)
CREATE (thaiCurry1)-[:CONTAINS]->(whitePeppercorn)

CREATE (thaiEggplantRecipe)-[:CONTAINS]->(coconutMilk)
CREATE (thaiEggplantRecipe)-[:CONTAINS]->(thaiChilies)
CREATE (thaiEggplantRecipe)-[:CONTAINS]->(chiliPowder)
CREATE (thaiEggplantRecipe)-[:CONTAINS]->(corianderPowder)
CREATE (thaiEggplantRecipe)-[:CONTAINS]->(clovesGarlic)
CREATE (thaiEggplantRecipe)-[:CONTAINS]->(ginger)
CREATE (thaiEggplantRecipe)-[:CONTAINS]->(lemonGrassStalk)
CREATE (thaiEggplantRecipe)-[:CONTAINS]->(chickenStock)
CREATE (thaiEggplantRecipe)-[:CONTAINS]->(limeJuice)
CREATE (thaiEggplantRecipe)-[:CONTAINS]->(oliveOrCoconutOil)
CREATE (thaiEggplantRecipe)-[:CONTAINS]->(onion)
CREATE (thaiEggplantRecipe)-[:CONTAINS]->(redBellPepper)
CREATE (thaiEggplantRecipe)-[:CONTAINS]->(salt)
CREATE (thaiEggplantRecipe)-[:CONTAINS]->(thaiBasil)
CREATE (thaiEggplantRecipe)-[:CONTAINS]->(thaiEggplant)
CREATE (thaiEggplantRecipe)-[:CONTAINS]->(turmeric)

CREATE (yellowThaiCurry)-[:CONTAINS]->(kaffirLime)

CREATE (maesriThaiRedCurryPaste)-[:PURCHASE_AT]->(wholeFoods)
CREATE (a1Sauce)-[:PURCHASE_AT]->(dummy)
CREATE (allspice)-[:PURCHASE_AT]->(centralCoop)
CREATE (almondMilksPlease)-[:PURCHASE_AT]->(traderJoes)
CREATE (almondsBulkRoastedOrRawWhicheverIsCheaper)-[:PURCHASE_AT]->(traderJoes)
CREATE (angkorCambodianFoodPasteLemongrass)-[:PURCHASE_AT]->(qfc)
CREATE (apples)-[:PURCHASE_AT]->(safeway)
CREATE (artichokeHearts)-[:PURCHASE_AT]->(safeway)
CREATE (asparagus)-[:PURCHASE_AT]->(dummy)
CREATE (asparagus)-[:PURCHASE_AT]->(traderJoes)
CREATE (avocadosNotInBagStupid)-[:PURCHASE_AT]->(traderJoes)
CREATE (bacon)-[:PURCHASE_AT]->(safeway)
CREATE (bakedTofu)-[:PURCHASE_AT]->(thanhSonTofu)
CREATE (bakersDozen)-[:PURCHASE_AT]->(einsteinBrotheresBagels)
CREATE (bakingCupsInCakeMixflourAisle)-[:PURCHASE_AT]->(safeway)
CREATE (bakingSoda)-[:PURCHASE_AT]->(safeway)
CREATE (ballPowderSmellsNice)-[:PURCHASE_AT]->(safeway)
CREATE (bambooShoots)-[:PURCHASE_AT]->(safeway)
CREATE (bananasOrganic)-[:PURCHASE_AT]->(traderJoes)
CREATE (barbecueSauceBabyRaysBbqSauce)-[:PURCHASE_AT]->(safeway)
CREATE (barley)-[:PURCHASE_AT]->(centralCoop)
CREATE (basilDry)-[:PURCHASE_AT]->(centralCoop)
CREATE (basilFresh)-[:PURCHASE_AT]->(hauHauMarket)
CREATE (bayLeaf)-[:PURCHASE_AT]->(dummy)
CREATE (beanCannelloniWhite)-[:PURCHASE_AT]->(centralCoop)
CREATE (beanGreatNorthernWhite)-[:PURCHASE_AT]->(centralCoop)
CREATE (beanNavyBean)-[:PURCHASE_AT]->(dummy)
CREATE (beansBlack15OzCan)-[:PURCHASE_AT]->(safeway)
CREATE (beansBlackBulk)-[:PURCHASE_AT]->(centralCoop)
CREATE (beansGreen)-[:PURCHASE_AT]->(safeway)
CREATE (beansKidneyBulk)-[:PURCHASE_AT]->(centralCoop)
CREATE (beefChuck)-[:PURCHASE_AT]->(safeway)
CREATE (beefChuckShoulderClod)-[:PURCHASE_AT]->(wholeFoods)
CREATE (beerLagger)-[:PURCHASE_AT]->(safeway)
CREATE (beerSessionLager)-[:PURCHASE_AT]->(traderJoes)
CREATE (beets)-[:PURCHASE_AT]->(safeway)
CREATE (beetsCanned)-[:PURCHASE_AT]->(safeway)
CREATE (blueberriesFrozenUponinaBag)-[:PURCHASE_AT]->(groceryOutletBargainMarketBargainMarket)
CREATE (bokChoy)-[:PURCHASE_AT]->(safeway)
CREATE (bonitoFlakes)-[:PURCHASE_AT]->(m2mMart)
CREATE (boullionBeef)-[:PURCHASE_AT]->(dummy)
CREATE (boullionVegetableBrothPowdered)-[:PURCHASE_AT]->(centralCoop)
CREATE (breadDavesYumsSeedBread)-[:PURCHASE_AT]->(dummy)
CREATE (breadFrench)-[:PURCHASE_AT]->(qfc)
CREATE (breadOlive)-[:PURCHASE_AT]->(centralCoop)
CREATE (breadPurpleNutsAndGrain)-[:PURCHASE_AT]->(safeway)
CREATE (breadSoda)-[:PURCHASE_AT]->(macrinaBakery)
CREATE (brewersYeast)-[:PURCHASE_AT]->(centralCoop)
CREATE (broccoli)-[:PURCHASE_AT]->(safeway)
CREATE (broccoli6oz)-[:PURCHASE_AT]->(safeway)
CREATE (broccolini)-[:PURCHASE_AT]->(safeway)
CREATE (brothBeefLowSodium)-[:PURCHASE_AT]->(safeway)
CREATE (brownieClifBar)-[:PURCHASE_AT]->(traderJoes)
CREATE (brownieMixBettyCrocker)-[:PURCHASE_AT]->(dummy)
CREATE (brownieMixDuncanHines)-[:PURCHASE_AT]->(dummy)
CREATE (brownieMixGhirardelli)-[:PURCHASE_AT]->(dummy)
CREATE (brownieMixPillsbury)-[:PURCHASE_AT]->(dummy)
CREATE (bulgurWheat)-[:PURCHASE_AT]->(centralCoop)
CREATE (butterUnsalted)-[:PURCHASE_AT]->(traderJoes)
CREATE (cabbageGreenSmall)-[:PURCHASE_AT]->(pcc)
CREATE (cabbageRedSmall)-[:PURCHASE_AT]->(pcc)
CREATE (calamari)-[:PURCHASE_AT]->(wholeFoods)
CREATE (carrots)-[:PURCHASE_AT]->(safeway)
CREATE (cauliflower)-[:PURCHASE_AT]->(safeway)
CREATE (cayennePepper)-[:PURCHASE_AT]->(centralCoop)
CREATE (celery)-[:PURCHASE_AT]->(safeway)
CREATE (chardonnayTerresDorees)-[:PURCHASE_AT]->(qfc)
CREATE (cheddarSharp)-[:PURCHASE_AT]->(traderJoes)
CREATE (cheeseBlue)-[:PURCHASE_AT]->(traderJoes)
CREATE (cheeseExtraSharpCheddar)-[:PURCHASE_AT]->(dummy)
CREATE (cheeseGruyere)-[:PURCHASE_AT]->(traderJoes)
CREATE (cheesePecorino)-[:PURCHASE_AT]->(traderJoes)
CREATE (cheeseSharpSwiss)-[:PURCHASE_AT]->(dummy)
CREATE (cheeseShreddedMozzarella8Oz)-[:PURCHASE_AT]->(qfc)
CREATE (chicken34Lb)-[:PURCHASE_AT]->(centralCoop)
CREATE (chickenBreast)-[:PURCHASE_AT]->(qfc)
CREATE (chickenBroth16Oz)-[:PURCHASE_AT]->(safeway)
CREATE (chickenBroth32Oz)-[:PURCHASE_AT]->(safeway)
CREATE (chickenBrothSwanson145Oz)-[:PURCHASE_AT]->(safeway)
CREATE (chickenElectricRotisserie)-[:PURCHASE_AT]->(wholeFoods)
CREATE (chickenStock)-[:PURCHASE_AT]->(safeway)
CREATE (chickenTenderloinsRubberDuckies1BagOnly)-[:PURCHASE_AT]->(traderJoes)
CREATE (chickenThigh)-[:PURCHASE_AT]->(madisonCoop)
CREATE (chilesChipotleInAdobo)-[:PURCHASE_AT]->(dummy)
CREATE (chiliPepperAnchoGround)-[:PURCHASE_AT]->(pcc)
CREATE (chiliPepperChipotleGround)-[:PURCHASE_AT]->(pcc)
CREATE (chiliPowder)-[:PURCHASE_AT]->(centralCoop)
CREATE (chiliPowder)-[:PURCHASE_AT]->(madisonCoop)
CREATE (chiliThai)-[:PURCHASE_AT]->(safeway)
CREATE (chineseBroccoli)-[:PURCHASE_AT]->(hauHauMarket)
CREATE (chips)-[:PURCHASE_AT]->(traderJoes)
CREATE (chocolateCoveredCherriesForJoyce)-[:PURCHASE_AT]->(traderJoes)
CREATE (choppedCalabrianPeppers)-[:PURCHASE_AT]->(wholeFoods)
CREATE (cilantro)-[:PURCHASE_AT]->(safeway)
CREATE (cinamon)-[:PURCHASE_AT]->(centralCoop)
CREATE (cinnamon)-[:PURCHASE_AT]->(centralCoop)
CREATE (clamChowder)-[:PURCHASE_AT]->(dummy)
CREATE (clamJuice)-[:PURCHASE_AT]->(wholeFoods)
CREATE (clams)-[:PURCHASE_AT]->(dummy)
CREATE (cleanserBonAmi)-[:PURCHASE_AT]->(bartell)
CREATE (clovesGarlic)-[:PURCHASE_AT]->(traderJoes)
CREATE (cocoaPowderUnsweetenedHersheysNatural8Oz)-[:PURCHASE_AT]->(safeway)
CREATE (coconutFlakes)-[:PURCHASE_AT]->(centralCoop)
CREATE (coconutMilk135OzCan)-[:PURCHASE_AT]->(safeway)
CREATE (coffeeBbPlu8875LessYumsThan8863)-[:PURCHASE_AT]->(centralCoop)
CREATE (coffeeBbs1stPreferenceBbPlu8863EqualExchangePeruvian)-[:PURCHASE_AT]->(centralCoop)
CREATE (coffeeBbs2ndPreferenceBbPlu3794KalaniCoffeeIndonesianEnyanaSumatra)-[:PURCHASE_AT]->(pcc)
CREATE (coffeeMtmKivuDarkEspressoRoast)-[:PURCHASE_AT]->(qfc)
CREATE (coffeeMtmPlu1859FidalgoBayOrganicFairTradeFrenchRoastExtraDark)-[:PURCHASE_AT]->(pcc)
CREATE (coffeeMtmPlu5820KivuKivuDarkFrenchRoast)-[:PURCHASE_AT]->(fredMeyer)
CREATE (coffeeMtmPlu8368DecafDecafDecafKindUnknown)-[:PURCHASE_AT]->(centralCoop)
CREATE (coffeeTDecaf)-[:PURCHASE_AT]->(safeway)
CREATE (coffeeTPlu8852TLikesItBbSaysYux)-[:PURCHASE_AT]->(centralCoop)
CREATE (coffeeTPlu8853)-[:PURCHASE_AT]->(centralCoop)
CREATE (coffeeTaylorPlu8868)-[:PURCHASE_AT]->(centralCoop)
CREATE (cokeZero)-[:PURCHASE_AT]->(safeway)
CREATE (collardGreens)-[:PURCHASE_AT]->(qfc)
CREATE (coolMintChocolateClifBar)-[:PURCHASE_AT]->(traderJoes)
CREATE (coriander)-[:PURCHASE_AT]->(centralCoop)
CREATE (corianderPowder)-[:PURCHASE_AT]->(madisonCoop)
CREATE (corianderSeeds)-[:PURCHASE_AT]->(safeway)
CREATE (cornFrozen)-[:PURCHASE_AT]->(safeway)
CREATE (cornOnCob)-[:PURCHASE_AT]->(safewqy)
CREATE (cornStarch)-[:PURCHASE_AT]->(dummy)
CREATE (cornmeal)-[:PURCHASE_AT]->(safeway)
CREATE (cornstarchBabyPowderNotJohnsonsTheyreBaddies)-[:PURCHASE_AT]->(qfc)
CREATE (cottageCheeseLargeCurd)-[:PURCHASE_AT]->(safeway)
CREATE (couscous)-[:PURCHASE_AT]->(centralCoop)
CREATE (couscousIsraeli)-[:PURCHASE_AT]->(centralCoop)
CREATE (cranberriesDried)-[:PURCHASE_AT]->(centralCoop)
CREATE (creamHeavy)-[:PURCHASE_AT]->(safeway)
CREATE (crest)-[:PURCHASE_AT]->(bartell)
CREATE (cucumber)-[:PURCHASE_AT]->(safeway)
CREATE (cucumbersEnglish)-[:PURCHASE_AT]->(safeway)
CREATE (cucumbersPersian)-[:PURCHASE_AT]->(traderJoes)
CREATE (cuminGround)-[:PURCHASE_AT]->(centralCoop)
CREATE (cuminSeedNotGrounddog)-[:PURCHASE_AT]->(centralCoop)
CREATE (cuminSeeds)-[:PURCHASE_AT]->(madisonCoop)
CREATE (curryPowder)-[:PURCHASE_AT]->(centralCoop)
CREATE (dates)-[:PURCHASE_AT]->(traderJoes)
CREATE (dill)-[:PURCHASE_AT]->(centralCoop)
CREATE (dillPickles)-[:PURCHASE_AT]->(safeway)
CREATE (dinoKaleUglySpinach)-[:PURCHASE_AT]->(dummy)
CREATE (driedShrimp)-[:PURCHASE_AT]->(safeway)
CREATE (driedThaiShrimpPaste)-[:PURCHASE_AT]->(uwajimaya)
CREATE (dukesMayonnaise)-[:PURCHASE_AT]->(dummy)
CREATE (edamameShelled)-[:PURCHASE_AT]->(safeway)
CREATE (eggplant)-[:PURCHASE_AT]->(safeway)
CREATE (eggplantChinese)-[:PURCHASE_AT]->(uwajimaya)
CREATE (eggplantThai)-[:PURCHASE_AT]->(uwajimaya)
CREATE (eggsDozen)-[:PURCHASE_AT]->(traderJoes)
CREATE (eggsLiquidEggWhitesBlueChikn)-[:PURCHASE_AT]->(safeway)
CREATE (enchiladaSauceRed)-[:PURCHASE_AT]->(dummy)
CREATE (endiveOrEscaroleLettce)-[:PURCHASE_AT]->(safeway)
CREATE (englishMuffins)-[:PURCHASE_AT]->(franzBakery)
CREATE (farro)-[:PURCHASE_AT]->(pcc)
CREATE (fetaYums)-[:PURCHASE_AT]->(traderJoes)
CREATE (filtersCoffeeSize2)-[:PURCHASE_AT]->(qfc)
CREATE (fishSauceRedBoatPremium)-[:PURCHASE_AT]->(safeway)
CREATE (fishTilapia)-[:PURCHASE_AT]->(safeway)
CREATE (flourWhiteAllpurposeUnbleachedIfPossibleButNoBigs)-[:PURCHASE_AT]->(safeway)
CREATE (flourWholeWheatAllpurpose)-[:PURCHASE_AT]->(safeway)
CREATE (franciscoInternationalFrenchSandwichRolls6Count)-[:PURCHASE_AT]->(safeway)
CREATE (frozenMangos)-[:PURCHASE_AT]->(groceryOutletBargainMarketBargainMarket)
CREATE (frozenPeas)-[:PURCHASE_AT]->(safeway)
CREATE (galangal)-[:PURCHASE_AT]->(uwajimaya)
CREATE (galangal)-[:PURCHASE_AT]->(uwajimaya)
CREATE (garamMasala)-[:PURCHASE_AT]->(centralCoop)
CREATE (garbanzoBeansDry)-[:PURCHASE_AT]->(centralCoop)
CREATE (garlic)-[:PURCHASE_AT]->(traderJoes)
CREATE (garlicChivesAlternativeChives)-[:PURCHASE_AT]->(hauHauMarket)
CREATE (garlicCloves)-[:PURCHASE_AT]->(traderJoes)
CREATE (garlicPowder)-[:PURCHASE_AT]->(centralCoop)
CREATE (ginger)-[:PURCHASE_AT]->(safeway)
CREATE (gingerPowder)-[:PURCHASE_AT]->(centralCoop)
CREATE (gingerRoot)-[:PURCHASE_AT]->(traderJoes)
CREATE (gochugaru)-[:PURCHASE_AT]->(amazon)
CREATE (grainsOfParadiseSpice)-[:PURCHASE_AT]->(centralCoop)
CREATE (granolaCookies)-[:PURCHASE_AT]->(centralCoop)
CREATE (grapesGrapeShaped)-[:PURCHASE_AT]->(safeway)
CREATE (gritsQuick)-[:PURCHASE_AT]->(safeway)
CREATE (groundBeef)-[:PURCHASE_AT]->(safeway)
CREATE (habanero)-[:PURCHASE_AT]->(safeway)
CREATE (halfgallonHalfHalf)-[:PURCHASE_AT]->(safeway)
CREATE (hamSliced)-[:PURCHASE_AT]->(safeway)
CREATE (heavyCream)-[:PURCHASE_AT]->(safeway)
CREATE (herbsOrSuperGreensLettuce)-[:PURCHASE_AT]->(centralCoop)
CREATE (herbsOrSuperGreensLettucesBucket)-[:PURCHASE_AT]->(safeway)
CREATE (honeyInGlassJar)-[:PURCHASE_AT]->(traderJoes)
CREATE (iceCreamChocolateSignatureBrand)-[:PURCHASE_AT]->(safeway)
CREATE (iceCreamCones)-[:PURCHASE_AT]->(safeway)
CREATE (iceCreamDoublefudgeBrownieDreyersSlowchurned)-[:PURCHASE_AT]->(safeway)
CREATE (italianSeasoning)-[:PURCHASE_AT]->(centralCoop)
CREATE (johnsonsCreamyBabyOil)-[:PURCHASE_AT]->(dummy)
CREATE (kaffirLimeLeaves)-[:PURCHASE_AT]->(uwajimaya)
CREATE (kale)-[:PURCHASE_AT]->(pcc)
CREATE (katchup)-[:PURCHASE_AT]->(safeway)
CREATE (kidneyBeansRedOrganic15Oz)-[:PURCHASE_AT]->(pcc)
CREATE (kidneyBeansSw)-[:PURCHASE_AT]->(dummy)
CREATE (kombucha)-[:PURCHASE_AT]->(centralCoop)
CREATE (kombucha)-[:PURCHASE_AT]->(groceryOutletBargainMarket)
CREATE (leeKumKeeSoySaucePremiumDarkBottle)-[:PURCHASE_AT]->(uwajimaya)
CREATE (lemon)-[:PURCHASE_AT]->(traderJoes)
CREATE (lemonJuice)-[:PURCHASE_AT]->(wholeFoods)
CREATE (lemonZestGratedLemonRind)-[:PURCHASE_AT]->(traderJoes)
CREATE (lemongrass3Stalks)-[:PURCHASE_AT]->(safeway)
CREATE (lemongrassStalk)-[:PURCHASE_AT]->(safeway)
CREATE (lentilsBlackBeluga)-[:PURCHASE_AT]->(pcc)
CREATE (lentilsBrown)-[:PURCHASE_AT]->(pcc)
CREATE (lentilsGreen)-[:PURCHASE_AT]->(centralCoop)
CREATE (lettucesRomaine)-[:PURCHASE_AT]->(safeway)
CREATE (lime)-[:PURCHASE_AT]->(traderJoes)
CREATE (lime)-[:PURCHASE_AT]->(traderJoes)
CREATE (limeJuice)-[:PURCHASE_AT]->(wholeFoods)
CREATE (limeLeavesKaffir)-[:PURCHASE_AT]->(uwajimaya)
CREATE (limes)-[:PURCHASE_AT]->(traderJoes)
CREATE (lobsterCornChowder)-[:PURCHASE_AT]->(wholeFoods)
CREATE (maltomeal)-[:PURCHASE_AT]->(safeway)
CREATE (marjoramLeaves)-[:PURCHASE_AT]->(centralCoop)
CREATE (marketspiceTeaDecaf2OzForMommy)-[:PURCHASE_AT]->(bartell)
CREATE (martianmallowsLargeButNotGigantic)-[:PURCHASE_AT]->(safeway)
CREATE (meatSliced)-[:PURCHASE_AT]->(qfc)
CREATE (merlot)-[:PURCHASE_AT]->(traderJoes)
CREATE (mintOrMintExtract)-[:PURCHASE_AT]->(nakedGrocer)
CREATE (misoPaste)-[:PURCHASE_AT]->(qfc)
CREATE (misoSweetWhite)-[:PURCHASE_AT]->(wholeFoods)
CREATE (molasses)-[:PURCHASE_AT]->(wholeFoods)
CREATE (mouthwashActRestoring)-[:PURCHASE_AT]->(bartell)
CREATE (mushroomsCrimini)-[:PURCHASE_AT]->(safeway)
CREATE (mushroomsPortobello)-[:PURCHASE_AT]->(qfc)
CREATE (mustardGermanMediumHotInJarWHandle)-[:PURCHASE_AT]->(groceryOutletBargainMarket)
CREATE (mustardSpicyBrownInGlassJarPlease)-[:PURCHASE_AT]->(groceryOutletBargainMarketBargainMarket)
CREATE (myntzes)-[:PURCHASE_AT]->(traderJoes)
CREATE (noodlesLasagna)-[:PURCHASE_AT]->(safeway)
CREATE (nutmeg)-[:PURCHASE_AT]->(centralCoop)
CREATE (oOrganicsOrganicCoconutOilVirginUnrefined)-[:PURCHASE_AT]->(safeway)
CREATE (oilAvocado)-[:PURCHASE_AT]->(wholeFoods)
CREATE (oilOliveExtraVirgin)-[:PURCHASE_AT]->(groceryOutletBargainMarket)
CREATE (olivesCastelvetrano)-[:PURCHASE_AT]->(dummy)
CREATE (olivesKalamataPitted)-[:PURCHASE_AT]->(groceryOutletBargainMarket)
CREATE (onePercentMilkYellowCarton)-[:PURCHASE_AT]->(safeway)
CREATE (onePercentOr2PercentMilkInGlassJarNotRedCapWholeMilk)-[:PURCHASE_AT]->(centralCoop)
CREATE (onion)-[:PURCHASE_AT]->(traderJoes)
CREATE (onionPowder)-[:PURCHASE_AT]->(centralCoop)
CREATE (onionRed)-[:PURCHASE_AT]->(traderJoes)
CREATE (onionSweet)-[:PURCHASE_AT]->(traderJoes)
CREATE (onionWhite1)-[:PURCHASE_AT]->(safeway)
CREATE (onions)-[:PURCHASE_AT]->(traderJoes)
CREATE (orangeJuice)-[:PURCHASE_AT]->(qfc)
CREATE (oranges)-[:PURCHASE_AT]->(dummy)
CREATE (oranges)-[:PURCHASE_AT]->(safeway)
CREATE (oregano)-[:PURCHASE_AT]->(centralCoop)
CREATE (organicSaladFreshHerbBlend)-[:PURCHASE_AT]->(safeway)
CREATE (oysterMushrooms)-[:PURCHASE_AT]->(safeway)
CREATE (oysterSauce)-[:PURCHASE_AT]->(wholeFoods)
CREATE (padThaiSauce)-[:PURCHASE_AT]->(wholeFoods)
CREATE (pancakeMixSnoqualmieFallsLodge)-[:PURCHASE_AT]->(dummy)
CREATE (paprika)-[:PURCHASE_AT]->(nakedGrocer)
CREATE (paprikaSmoked)-[:PURCHASE_AT]->(centralCoop)
CREATE (parmesanCheese)-[:PURCHASE_AT]->(traderJoes)
CREATE (parsley)-[:PURCHASE_AT]->(safeway)
CREATE (pastaFettuccine)-[:PURCHASE_AT]->(groceryOutlet)
CREATE (pastaLinguine)-[:PURCHASE_AT]->(wholeFoods)
CREATE (pastaRigatoni)-[:PURCHASE_AT]->(traderJoes)
CREATE (pastaTrottole)-[:PURCHASE_AT]->(qfc)
CREATE (peanutButterAdamsUnsalted)-[:PURCHASE_AT]->(safeway)
CREATE (peanutButterBulk)-[:PURCHASE_AT]->(qfc)
CREATE (pearsAnjou)-[:PURCHASE_AT]->(safeway)
CREATE (pearsBartlett)-[:PURCHASE_AT]->(safeway)
CREATE (pearsBosc)-[:PURCHASE_AT]->(safeway)
CREATE (pepperBlackBulk)-[:PURCHASE_AT]->(centralCoop)
CREATE (pepperChipotle)-[:PURCHASE_AT]->(wholeFoods)
CREATE (pepperFlakesSpiceyRedPepperFlakes)-[:PURCHASE_AT]->(centralCoop)
CREATE (pepperJalapeno)-[:PURCHASE_AT]->(safeway)
CREATE (pepperSerrano)-[:PURCHASE_AT]->(safeway)
CREATE (peppercornsWholeBlack)-[:PURCHASE_AT]->(nakedGrocer)
CREATE (periPeriSauceGarlic)-[:PURCHASE_AT]->(wholeFoods)
CREATE (perillaOil)-[:PURCHASE_AT]->(m2mMart)
CREATE (perillaOil)-[:PURCHASE_AT]->(m2mMartKoreanGrocer)
CREATE (pineNuts)-[:PURCHASE_AT]->(pcc)
CREATE (pinotGrigioDryWhiteWine)-[:PURCHASE_AT]->(qfc)
CREATE (pistachios)-[:PURCHASE_AT]->(centralCoop)
CREATE (plums)-[:PURCHASE_AT]->(safeway)
CREATE (polenta)-[:PURCHASE_AT]->(safeway)
CREATE (popcorn)-[:PURCHASE_AT]->(centralCoop)
CREATE (pork)-[:PURCHASE_AT]->(safeway)
CREATE (potatoesBabyTriColor)-[:PURCHASE_AT]->(safeway)
CREATE (potatoesRusset2)-[:PURCHASE_AT]->(safeway)
CREATE (primoTaglioCheeseGoat4Oz)-[:PURCHASE_AT]->(traderJoes)
CREATE (prunes)-[:PURCHASE_AT]->(traderJoes)
CREATE (pumpkinSeedsSalted)-[:PURCHASE_AT]->(centralCoop)
CREATE (quickRolledOatsOatsPlu8485)-[:PURCHASE_AT]->(centralCoop)
CREATE (quinoaRed)-[:PURCHASE_AT]->(centralCoop)
CREATE (quinoaWhite)-[:PURCHASE_AT]->(nakedGrocer)
CREATE (radish)-[:PURCHASE_AT]->(safeway)
CREATE (raisinsBulkBabyBulk)-[:PURCHASE_AT]->(centralCoop)
CREATE (ramenNoodlesDry)-[:PURCHASE_AT]->(safeway)
CREATE (redBellPepper)-[:PURCHASE_AT]->(traderJoes)
CREATE (redChilliPeppers)-[:PURCHASE_AT]->(safeway)
CREATE (redGreenYellaPeppers)-[:PURCHASE_AT]->(traderJoes)
CREATE (redLentils)-[:PURCHASE_AT]->(madisonCoop)
CREATE (refriedBeansVegetarianNoLardTard)-[:PURCHASE_AT]->(safeway)
CREATE (reynoldsParchmentPaperGenuineNonstick45SqFt)-[:PURCHASE_AT]->(safeway)
CREATE (riceBrown)-[:PURCHASE_AT]->(pcc)
CREATE (riceNikoNikoSushiShortGrainRice)-[:PURCHASE_AT]->(uwajimaya)
CREATE (riceNoodleSheets)-[:PURCHASE_AT]->(dummy)
CREATE (riceSticks)-[:PURCHASE_AT]->(hauHauMarket)
CREATE (riceWhiteBasmati)-[:PURCHASE_AT]->(centralCoop)
CREATE (riceWild)-[:PURCHASE_AT]->(centralCoop)
CREATE (riceWineVinegar)-[:PURCHASE_AT]->(uwajimaya)
CREATE (riceWineVinegarKikkomanMirin)-[:PURCHASE_AT]->(safeway)
CREATE (riceWineVinegarSake)-[:PURCHASE_AT]->(m2mMart)
CREATE (ricottaCheese15Oz)-[:PURCHASE_AT]->(qfc)
CREATE (roastBeef)-[:PURCHASE_AT]->(safeway)
CREATE (roastedUnsaltedPeanuts)-[:PURCHASE_AT]->(pcc)
CREATE (rolledOatsOatsOldFashionedPlu8490)-[:PURCHASE_AT]->(nakedGrocer)
CREATE (romaineLettuceHearts)-[:PURCHASE_AT]->(safeway)
CREATE (sage)-[:PURCHASE_AT]->(pcc)
CREATE (salmonCanned)-[:PURCHASE_AT]->(dummy)
CREATE (salmonFresh)-[:PURCHASE_AT]->(wholeFoods)
CREATE (salmonSmoked)-[:PURCHASE_AT]->(dummy)
CREATE (salmonStillFrozenInTheShrinkWrap2Or3Lbs)-[:PURCHASE_AT]->(safeway)
CREATE (saltRegularIodizedTableSalt)-[:PURCHASE_AT]->(qfc)
CREATE (saltinesUnsalted)-[:PURCHASE_AT]->(qfc)
CREATE (sauceForSpaghettis)-[:PURCHASE_AT]->(traderJoes)
CREATE (sausage)-[:PURCHASE_AT]->(traderJoes)
CREATE (savoySpinachUglySpinach)-[:PURCHASE_AT]->(pcc)
CREATE (scallionsOrChives)-[:PURCHASE_AT]->(safeway)
CREATE (seedsSunflower)-[:PURCHASE_AT]->(nakedGrocer)
CREATE (semiSweetChocolateChips)-[:PURCHASE_AT]->(traderJoes)
CREATE (serranos)-[:PURCHASE_AT]->(safeway)
CREATE (sesameButterTahini)-[:PURCHASE_AT]->(safeway)
CREATE (sesameOilToasted)-[:PURCHASE_AT]->(wholeFoods)
CREATE (sesameSeeds)-[:PURCHASE_AT]->(nakedGrocer)
CREATE (sesameSeedsToasted)-[:PURCHASE_AT]->(centralCoop)
CREATE (shallotX1)-[:PURCHASE_AT]->(safeway)
CREATE (shallotsFried)-[:PURCHASE_AT]->(pcc)
CREATE (shawarmaBeefSirloin)-[:PURCHASE_AT]->(traderJoes)
CREATE (shrimpFrozen)-[:PURCHASE_AT]->(groceryOutletBargainMarket)
CREATE (shrimpLargeNotFrozen)-[:PURCHASE_AT]->(safeway)
CREATE (shrimpLargeNotFrozen)-[:PURCHASE_AT]->(seattleSeafood)
CREATE (signatureSelectBeansGarbanzo15Oz)-[:PURCHASE_AT]->(safeway)
CREATE (signatureSelectCrackersGrahamHoney)-[:PURCHASE_AT]->(safeway)
CREATE (snowPeas)-[:PURCHASE_AT]->(uwajimaya)
CREATE (soap)-[:PURCHASE_AT]->(centralCoop)
CREATE (sonicareSoftBristles)-[:PURCHASE_AT]->(bartell)
CREATE (sourdoughBread)-[:PURCHASE_AT]->(franzBakery)
CREATE (soySauceLiquidAminos)-[:PURCHASE_AT]->(dummy)
CREATE (spinach)-[:PURCHASE_AT]->(centralCoop)
CREATE (spinachFrozen)-[:PURCHASE_AT]->(safeway)
CREATE (squashButternut)-[:PURCHASE_AT]->(dummy)
CREATE (squashYellowCrookneck)-[:PURCHASE_AT]->(safeway)
CREATE (squid)-[:PURCHASE_AT]->(wholeFoods)
CREATE (sriracha)-[:PURCHASE_AT]->(traderJoes)
CREATE (stockVegetableDry)-[:PURCHASE_AT]->(centralCoop)
CREATE (strongRootsKaleQuinoaBurger)-[:PURCHASE_AT]->(wholeFoods)
CREATE (sugarPalm)-[:PURCHASE_AT]->(uwajimaya)
CREATE (sugarPureCane)-[:PURCHASE_AT]->(safeway)
CREATE (sundriedTomatoes)-[:PURCHASE_AT]->(safeway)
CREATE (superGreensBabySpinachBabyChardBabyKale)-[:PURCHASE_AT]->(safeway)
CREATE (syrupMaple)-[:PURCHASE_AT]->(safeway)
CREATE (tapatioHotSauce)-[:PURCHASE_AT]->(qfc)
CREATE (tapePainters)-[:PURCHASE_AT]->(hardwareStore)
CREATE (tarragon)-[:PURCHASE_AT]->(centralCoop)
CREATE (teffFlour)-[:PURCHASE_AT]->(dummy)
CREATE (texturizedVegetableProtein)-[:PURCHASE_AT]->(centralCoop)
CREATE (thaiBasil)-[:PURCHASE_AT]->(uwajimaya)
CREATE (thaiChilies)-[:PURCHASE_AT]->(uwajimaya)
CREATE (thaiEggplant)-[:PURCHASE_AT]->(uwajimaya)
CREATE (thaiKitchenRiceNoodlesStirFry)-[:PURCHASE_AT]->(safeway)
CREATE (thaiRedCurrySauce)-[:PURCHASE_AT]->(traderJoes)
CREATE (thinMiniRiceCrackerSnackers)-[:PURCHASE_AT]->(traderJoes)
CREATE (thinSlicerForShallots)-[:PURCHASE_AT]->(uwajimaya)
CREATE (thyme)-[:PURCHASE_AT]->(pcc)
CREATE (thymeFresh)-[:PURCHASE_AT]->(safeway)
CREATE (tofu)-[:PURCHASE_AT]->(hauHauMarket)
CREATE (tofu)-[:PURCHASE_AT]->(thanhSonTofu)
CREATE (tofuBaked)-[:PURCHASE_AT]->(traderJoes)
CREATE (tofuExtraFirm)-[:PURCHASE_AT]->(traderJoes)
CREATE (tofuSweetBbqPremarinatedSuperFirmBakedTofu)-[:PURCHASE_AT]->(qfc)
CREATE (toiletPaperBathTissue)-[:PURCHASE_AT]->(traderJoes)
CREATE (tomatillo)-[:PURCHASE_AT]->(safeway)
CREATE (tomatoPaste6OzCan)-[:PURCHASE_AT]->(safeway)
CREATE (tomatoSauce15OzCan)-[:PURCHASE_AT]->(safeway)
CREATE (tomatoSauce29OzCan)-[:PURCHASE_AT]->(safeway)
CREATE (tomatoesBeefsteak)-[:PURCHASE_AT]->(traderJoes)
CREATE (tomatoesCherry)-[:PURCHASE_AT]->(traderJoes)
CREATE (tomatoesCrushedInCan28Oz)-[:PURCHASE_AT]->(safeway)
CREATE (tomatoesDicedInBigCan28Oz)-[:PURCHASE_AT]->(safeway)
CREATE (tomatoesHeirloom)-[:PURCHASE_AT]->(traderJoes)
CREATE (tomatoesPeeledInCan28Oz)-[:PURCHASE_AT]->(safeway)
CREATE (tomatoesRoma)-[:PURCHASE_AT]->(traderJoes)
CREATE (tomatoesSunDriedRealBigJar)-[:PURCHASE_AT]->(safeway)
CREATE (tomatosInCan15OzCan)-[:PURCHASE_AT]->(safeway)
CREATE (tortellini)-[:PURCHASE_AT]->(traderJoes)
CREATE (tortillaFlourLargeDiameterDonPanchoOrSafewayBrand)-[:PURCHASE_AT]->(groceryOutletBargainMarket)
CREATE (tumeric)-[:PURCHASE_AT]->(madisonCoop)
CREATE (tumericPowder)-[:PURCHASE_AT]->(centralCoop)
CREATE (tunaInACan)-[:PURCHASE_AT]->(groceryOutletBargainMarket)
CREATE (tunaSteak)-[:PURCHASE_AT]->(dummy)
CREATE (turkey)-[:PURCHASE_AT]->(safeway)
CREATE (turkeyBacon)-[:PURCHASE_AT]->(dummy)
CREATE (turkeyBacon)-[:PURCHASE_AT]->(traderJoes)
CREATE (turkeyGround)-[:PURCHASE_AT]->(dummy)
CREATE (turkeyWhole)-[:PURCHASE_AT]->(dummy)
CREATE (unsaltedTopsUnsaltedSalteens)-[:PURCHASE_AT]->(qfc)
CREATE (vegenaise)-[:PURCHASE_AT]->(wholeFoods)
CREATE (vinegarAppleCider)-[:PURCHASE_AT]->(dummy)
CREATE (vinegarAppleCiderInGlassBottleNonOrgangic)-[:PURCHASE_AT]->(safeway)
CREATE (vinegarBalsamic)-[:PURCHASE_AT]->(traderJoes)
CREATE (vinegarRedWine)-[:PURCHASE_AT]->(safeway)
CREATE (vinegarRiceVinegar)-[:PURCHASE_AT]->(uwajimaya)
CREATE (vinegarWhite)-[:PURCHASE_AT]->(groceryOutletBargainMarket)
CREATE (watermelon)-[:PURCHASE_AT]->(traderJoes)
CREATE (wheatBerries)-[:PURCHASE_AT]->(centralCoop)
CREATE (whitePeppercorn)-[:PURCHASE_AT]->(madisonCoop)
CREATE (wineCharlesShaw)-[:PURCHASE_AT]->(traderJoes)
CREATE (worcestershireSauce)-[:PURCHASE_AT]->(safeway)
CREATE (yams)-[:PURCHASE_AT]->(traderJoes)
CREATE (yeastActivedry)-[:PURCHASE_AT]->(safeway)
CREATE (yogurtFlyingCowCreameryYogurtInReturnableGlassContainer)-[:PURCHASE_AT]->(traderJoes)
CREATE (yogurtNonfatPlainblueBucket)-[:PURCHASE_AT]->(traderJoes)
CREATE (yukonGoldPotatoes)-[:PURCHASE_AT]->(safeway)
CREATE (zucchini)-[:PURCHASE_AT]->(safeway)

CREATE (tsuyu)-[:IS_THE_SAME_AS]->(kikkomanJapaneseNoodleSoupBaseHonTsuyu)

CREATE (seonkyoungLongest)-[:CREATED]->(sesameNoodleRecipe)
CREATE (joshuaweissman)-[:CREATED]->(thaiCurry1)
CREATE (hanaAsbrink)-[:CREATED]->(coldSobaWithPerillaOilDressing)
CREATE (marionsKitchen)-[:CREATED]->(thaiPanangChickenCurry)
CREATE (recipetineats)-[:CREATED]->(yellowThaiCurry);

MATCH (n) RETURN n
